archetypes_Ids = {
    # PHB
    "Armormech Engineering": "2Cloz2rrPw76ACn0",
    "Armstech Engineering": "Mbe9qsurpJ0mb4F2",
    "Assault Specialist": "vWCA4gae11g8s1xq",
    "Ballistic Approach": "hlZPMF7NjGemaw66",
    "Beguiler Practice": "xUUk8lINd1wpQrIh",
    "Bulwark Technique": "hJfD06NmantavchV",
    "Deadeye Technique": "ZDNCB88TzeMFGY6i",
    "Doctor Pursuit": "PI1B9vYofzCXU9so",
    "Echani Order": "0s8yk4E0Kneqe4zt",
    "Form Ii: Makashi": "rW7zqxiNXePBLnui",
    "Form Iii: Soresu": "ECxUMB1p8nu6WAGL",
    "Form V: Shien/Djem So": "i0AaMWBnSREQdQsg",
    "Form Vi: Niman": "w1XQ5LzJNpk6PT0F",
    "Gadgeteer Engineering": "SsvsNMkJX1wW2rs6",
    "Gunslinger Practice": "HAbjFjbdRHO3mBss",
    "Hunter Technique": "Ls55Gc4qha7Muacz",
    "Lethality Practice": "G1F7NBAvLma5Aot4",
    "Marauder Approach": "Fo2ZNwCWXfWuDJji",
    "Nightsister Order": "igjYYoVyL95UNC0c",
    "Path Of Aggression": "3GmBJl9h0FpyIKFg",
    "Path Of Focus": "xIgy4jaHPhmry1Ub",
    "Path Of Shadows": "X3FsoSbXFXkvJvZO",
    "Path Of The Forceblade": "4afEpKVpPAUq3lMe",
    "Politician Pursuit": "UZCwqqLLp7IBjqku",
    "Precision Approach": "q4cqalPyT4rkroVr",
    "Sharpshooter Practice": "YByrgf4R9lfeVVBQ",
    "Shield Specialist": "huTTmKT9yzE89Go1",
    "Slayer Technique": "EEBl6B5YPcztiGRm",
    "Stalker Technique": "EipqN28Px01dBfmH",
    "Tactical Specialist": "SKluJRGJzsX03qlx",
    "Tactician Pursuit": "OZ0ln6ZxQgdEUxoy",
    "Unstable Engineering": "KDx2Pjxk4RZQD05d",
    "Warchief Approach": "pSIVnxwvRlyNoFM4",
    "Way Of Balance": "kqAxtz1x4ydhppPG",
    "Way Of Lightning": "e1tObWwWnq5gt9zE",
    "Way Of Suggestion": "Wdi8eckrcxpxQL3p",
    "Way Of The Sage": "FLN1Vqb53UECBMVu"
}
