archetypes_Ids = {
    # PHB
    "Armormech Engineering": "2Cloz2rrPw76ACn0",
    "Armstech Engineering": "Mbe9qsurpJ0mb4F2",
    "Assault Specialist": "vWCA4gae11g8s1xq",
    "Ballistic Approach": "hlZPMF7NjGemaw66",
    "Beguiler Practice": "xUUk8lINd1wpQrIh",
    "Bulwark Technique": "hJfD06NmantavchV",
    "Deadeye Technique": "ZDNCB88TzeMFGY6i",
    "Doctor Pursuit": "PI1B9vYofzCXU9so",
    "Echani Order": "0s8yk4E0Kneqe4zt",
    "Form Ii: Makashi": "rW7zqxiNXePBLnui",
    "Form Iii: Soresu": "ECxUMB1p8nu6WAGL",
    "Form V: Shien/Djem So": "i0AaMWBnSREQdQsg",
    "Form Vi: Niman": "w1XQ5LzJNpk6PT0F",
    "Gadgeteer Engineering": "SsvsNMkJX1wW2rs6",
    "Gunslinger Practice": "HAbjFjbdRHO3mBss",
    "Hunter Technique": "Ls55Gc4qha7Muacz",
    "Lethality Practice": "G1F7NBAvLma5Aot4",
    "Marauder Approach": "Fo2ZNwCWXfWuDJji",
    "Nightsister Order": "igjYYoVyL95UNC0c",
    "Path Of Aggression": "3GmBJl9h0FpyIKFg",
    "Path Of Focus": "xIgy4jaHPhmry1Ub",
    "Path Of Shadows": "X3FsoSbXFXkvJvZO",
    "Path Of The Forceblade": "4afEpKVpPAUq3lMe",
    "Politician Pursuit": "UZCwqqLLp7IBjqku",
    "Precision Approach": "q4cqalPyT4rkroVr",
    "Sharpshooter Practice": "YByrgf4R9lfeVVBQ",
    "Shield Specialist": "huTTmKT9yzE89Go1",
    "Slayer Technique": "EEBl6B5YPcztiGRm",
    "Stalker Technique": "EipqN28Px01dBfmH",
    "Tactical Specialist": "SKluJRGJzsX03qlx",
    "Tactician Pursuit": "OZ0ln6ZxQgdEUxoy",
    "Unstable Engineering": "KDx2Pjxk4RZQD05d",
    "Warchief Approach": "pSIVnxwvRlyNoFM4",
    "Way Of Balance": "kqAxtz1x4ydhppPG",
    "Way Of Lightning": "e1tObWwWnq5gt9zE",
    "Way Of Suggestion": "Wdi8eckrcxpxQL3p",
    "Way Of The Sage": "FLN1Vqb53UECBMVu",

    # EC
    "Acquisitions Practice": "uKs4nEUZxYJ6iAd7",
    "Addicted Approach": "PCwepUZqHYlxr4T3",
    "Adept Specialist": "6HRxOPMOmOiKmuIG",
    "Aing-Tii Order": "f6laKRexQAH7Oa3b",
    "Artificer Engineering": "F3eJbFw1kKde9Zg9",
    "Artillerist Technique": "sgoAH5OjfxsXf2fp",
    "Astrotech Engineering": "avFn1m9oUpDgKAAF",
    "Audiotech Engineering": "UsIUJiNPmFWbEgjK",
    "Biochem Engineering": "uqpzyWm3JoIJlHrb",
    "Biotech Engineering": "2yiTq2k7xFpjcLVv",
    "Blademaster Specialist": "7OqolLOiiu5K59rD",
    "Bloodstorm Approach": "cjI8o9tAfKsuSGAP",
    "Brawling Approach": "XxG8t5Tr9agbjytr",
    "Chef Pursuit": "jTIquPrCJE4cdUTt",
    "Crimson Order": "5ZfztAWnxh7mqTL7",
    "Cybertech Engineering": "m0oQQxDCTO6nqWnz",
    "Cyclone Approach": "bBMsNrnCUOXGfb0h",
    "Demolitions Specialist": "V4vCxmTwJFxi0HGM",
    "Disabling Practice": "KXH9dZsv2CAXAa6X",
    "Enhancement Specialist": "dY9gPH2vjYpS9onW",
    "Explorer Pursuit": "rhte8G7Duf9dtKLV",
    "Form I: Shii-Cho": "cROcc25Zj1MT6Yf6",
    "Form Iv: Ataru": "9Hva27QHj2ruQXTA",
    "Form Ix: Tràkata": "ucmQpCjxdEN6tpxD",
    "Form Vii: Juyo/Vapaad": "3yOiMsM439IfwEBm",
    "Form Viii: Sokan": "t5LS6epj3270S38n",
    "Form X: Jar'Kai": "pr7Xe82MOaof0IXj",
    "Frenzied Approach": "4zUolY92dTrk3e5B",
    "Gambler Pursuit": "lGoI3XalF3gv8el4",
    "Geneticist Pursuit": "nP8lpZPBh0HGKUJR",
    "Heavy Weapons Specialist": "n46s1RsRnnQjxHvX",
    "Illusionist Technique": "174qCi5FWBd5LDP0",
    "Industrial Approach": "jEXfkSLXZvy0BQG7",
    "Inquisitor Technique": "BEMJgPn6JKghk2zh",
    "Jal Shey Order": "PoyYtrej7B5BZRRG",
    "Juggernaut Approach": "QRwypM2cIYxW0NVN",
    "Kage Order": "MorU2Jy5yx77N9QO",
    "Kyuzo Order": "Vtk1Pw4AILqZk27u",
    "Mastermind Technique": "EOnRnPaACPP1vRTQ",
    "Matukai Order": "taNiZralaSUdH6a2",
    "Mounted Specialist": "uV3tG38Fo7JAXF0W",
    "Path Of Communion": "qlg4myujDRxt6FXB",
    "Path Of Etherealness": "pnWaHtbho4xgFpIU",
    "Path Of Synthesis": "tND6Q1akd5unb3jf",
    "Path Of Tenacity": "BtUr8K0noVfAE11J",
    "Path Of The Corsair": "9AQImD6JBpd9c1UK",
    "Path Of Witchcraft": "VRfBQKAhumWExGiy",
    "Performance Practice": "owhXRBD1NnGWXdr6",
    "Praetorian Specialist": "zxnST2OeLGmt8buI",
    "Predator Technique": "xAObT0H9SNxYOQh2",
    "Ruffian Practice": "A3MyNIRoyvE9fP64",
    "Saboteur Practice": "lETcZuQWPZg3n2u0",
    "Sawbones Practice": "TgUiU6MrAP7Xyj3H",
    "Scrapper Practice": "RulD3rQZqDk5H0Pl",
    "Slicer Pursuit": "ovm5WJyAM317IC4K",
    "Teleportation Technique": "np8PlkH43bFHGOjq",
    "Totem Specialist": "CRRgJPKHIHD72CEt",
    "Trickster Order": "OPVska67MO0Zauct",
    "Way Of Confluence": "Lz0gdQ5ou3k5E7Fo",
    "Way Of Endurance": "Y1JjyA1CuOSRCjAb",
    "Way Of Manipulation": "q208WP2Lacp7dG6v",
    "Way Of Negation": "6JrXY2jDqQiuuUGq",
    "Way Of Technology": "oYAXrbXaFVAoGDLM",
    "Way Of Telekinetics": "r7BKY5yWig2vhW5i",
    "Way Of The Seer": "12fYGPcLSITUYHMK",
    "Whills Order": "gbP89R34SpttnfPb",
    "Ysannanite Form": "VXmVX5a3ac4kKAIT",
    "Zoologist Pursuit": "c89hsFFZG4WGlYcV"
}
