forcepowers_Ids = {
    # PHB
    "Affect Mind": "b2MvrTaXlisYe2A4",
    "Affliction": "KCVdYOoxu0kfkSCn",
    "Animate Weapon": "WG79exTllchDSK6M",
    "Aura Of Purity": "HPtgWP83jKSyFWFp",
    "Aura Of Vigor": "ucLQqgu3XZCePdJg",
    "Battle Meditation": "EXK4sg6gKXfMnLnf",
    "Battle Precognition": "1ARPmaD7aZ3Pjxt2",
    "Beacon Of Hope": "qkBzg8ZIJpglVMvi",
    "Beast Trick": "AvkOVXIYVgJTsytl",
    "Bestow Curse": "1hXmkUOjNtkCtS8T",
    "Breath Control": "4a18XmMOExlwDAYF",
    "Burst Of Speed": "tAs3ogXXwpDkpZvF",
    "Burst": "vmzC47AY66cx1LwU",
    "Calm Emotions": "qIelaqr9e9Cn0W8O",
    "Choke": "QyZogGty2DfkYnHF",
    "Cloud Mind": "BJDl4AQjFfR1RTxc",
    "Coerce Mind": "YFbfva5hY5FOxmdw",
    "Convultion": "5lOXTZUiRmL7aZi9",
    "Crush": "Nefsi9cHQFG04LBx",
    "Curse": "XJSLZaP9Nix5EJHY",
    "Danger Sense": "WBNy29tnkclypOVZ",
    "Dark Shear": "vRl7zVJ9XwndAme3",
    "Dark Side Tendrils": "XizLBCti6XKTlkmM",
    "Darkness": "TLEOcYzzQWvAOWsT",
    "Death Field": "InyoZTjdAijUms7e",
    "Denounce": "81kLSpx80zEEr0O2",
    "Destroy Droid": "eYw6j0VVVD0vEH7l",
    "Disable Droid": "KJ7bSmk9W4AImGRm",
    "Disperse Force": "ebWGew0oR2CG7S43",
    "Dominate Beast": "JBd2XatPjBGxjimU",
    "Dominate Mind": "YguQH8fuWTnHMPcK",
    "Dominate Monster": "AnqVVfHnV36f7OnA",
    "Drain Life": "RDZdXmMpJqUEn7LX",
    "Drain Vitality": "kLwHklnrWPw9jKm6",
    "Earthquake": "faTYDaOejYHPfXdl",
    "Enfeeble": "L8CJ1QEXfKztMyCX",
    "Eruption": "ZeVEHfAVZrq79B6I",
    "Fear": "haGnWeBa6QhTG9Dh",
    "Feedback": "Pf4e5uRdTd4VuUjU",
    "Force Barrier": "T5nzsISIa6ep9YRX",
    "Force Blind/deafen": "bDdyZTL7KCiz2zXR",  # TODO: Fix caps
    "Force Body": "iWTTNyNi2mwVDlUF",
    "Force Breach": "d3nRwoHE7vUvWqG0",
    "Force Camoflage": "i1N033vPzDom3Kpj",
    "Force Chain Lightning": "C0XOY6bm7NkP5cDW",
    "Force Confusion": "KG7ajXisDV6UGlHg",
    "Force Disarm": "5o01ADUmNyzy470b",
    "Force Enlightenment": "di7rHBW59w6cS1WM",
    "Force Immunity": "f41D14g0yIBuXUka",
    "Force Jump": "oPi4Y7zezP7MxNDK",
    "Force Lightning Cone": "NrMpYXddHnoPKHT2",
    "Force Lightning": "Yn07n957VuJ39xk3",
    "Force Link": "MEcTbI8Y4xotnJwl",
    "Force Mask": "Vsnr0aVZQIcRD0Ed",
    "Force Mend": "u91uDdCIN7FvEBzx",
    "Force Project": "KVY80cxeW955U6mG",
    "Force Propel": "3KGdCbHATzaghiwo",
    "Force Push/pull": "kNiT2BD3eIgE1zys",  # TODO: Fix caps
    "Force Repulse": "It12G2wROx7ojgwu",
    "Force Scream": "UTCkJSnF7R7V2bqF",
    "Force Sight": "PUHY0RrLsi4tAnZx",
    "Force Suppression": "XYHAKmU4gHSzRK3I",
    "Force Technique": "qykEFT52bywaQrNO",
    "Force Throw": "bzvLe859r7CDWFIv",
    "Force Trance": "esyvxlavJubgPNmj",
    "Freedom Of Movement": "BqGw2Mt7mBqqVclc",
    "Give Life": "6sfPioKWjx1VOqwF",
    "Grasping Vine": "gtBIhjewL9Ie8Qdx",
    "Greater Feedback": "Zt3Aw0RkTFY2bwW8",
    "Greater Heal": "K0AsOF4VRvKvftYD",
    "Guidance": "C2ROn2KK2QTLm9DW",
    "Hallucination": "B3wzjcXwEAfTxhQW",
    "Heal": "7dqNYNqMphGLIm5T",
    "Heroism": "LdtNnD37NnOsg8oF",
    "Horror": "5koTRABu4ER8g6Wo",
    "Hysteria": "peef6HzwqX0231BB",
    "Improved Battle Meditation": "Oxb3dpusa4SmIKQd",
    "Improved Dark Side Tendrils": "eVl00unU1rsuQ0MN",
    "Improved Feedback": "GBJRx32gU9xU1Q6s",
    "Improved Force Camouflage": "I2EsFwBa7AyIwX1v",
    "Improved Force Immunities": "6xaiD7x8L4RLpXKv",
    "Improved Force Scream": "sXl6Pkz2dGsDUuOc",
    "Improved Heal": "FrOqLsVBWUSvka4X",
    "Improved Phasestrike": "ENNhFJKCcxrg481J",
    "Improved Phasewalk": "6tJDkxz5pyPHVJvT",
    "Improved Restoration": "F02pFj62Grlr9sdF",
    "Improved Revitalize": "gpUbIaRtv1y7qinF",
    "Insanity": "VIi9ZD8Ha669UYRw",
    "Kill": "OYQAqS6rjVy6o5Oa",
    "Knight Speed": "BbTpLPyPoucTsEdA",
    "Lightning Charge": "MkDRzlCkK2hDdtvi",
    "Locate Creature": "bsTG22DqTxo7WQta",
    "Locate Object": "SmMJBkUl0oGmhbhu",
    "Maddening Darkness": "2EdyvNwmyRD9yhmn",
    "Mass Animation": "wqMkp6WYkBCFVVA8",
    "Mass Coerce Mind": "jmFTPxWQXJENvQtQ",
    "Mass Hysteria": "3odfJsD1RezuxzDG",
    "Master Battle Meditation": "wYU8UqUwJVpOQpRK",
    "Master Feedback": "DFpooO6icOfTdG5C",
    "Master Force Barrier": "3IoaQSSoAtFsoavO",
    "Master Force Immunity": "G5mI31lc5lBqMT4V",
    "Master Force Scream": "b0fmnYMO3bLtarhk",
    "Master Heal": "l2O0YEzxgHek0gpL",
    "Master Revitalize": "SbgYZsKp6FwiLhQA",
    "Master Speed": "28uF6yN4NLoc1Mf7",
    "Mind Blank": "uJrlI81nVVpRgYHP",
    "Mind Trap": "WWCvfD4ldEZoR5fn",
    "Mind Trick": "1svmnRR3v0KEGeDZ",
    "Phasestrike": "G8UVHP4MXW6Dudky",
    "Phasewalk": "or5ZY4T4t1wJJ5ad",
    "Plant Surge": "YTSbLoD7dnvql2H3",
    "Precognition": "HqxcYlFOZJZ91a98",
    "Project": "FLBRnexpCEIneqy2",
    "Rage": "ABfdZpL0iC2Osioj",
    "Remove Curse": "1IFr14Wc4sA1833o",
    "Rescue": "uMJVdxqiNS8h120G",
    "Resistance": "fcs6lsi5hMfPOgRb",
    "Restoration": "4Tmt6Bb06vqS7cCM",
    "Revitalize": "5Gxqh2j4A258jCSY",
    "Ruin": "tHwhXwiRAOciNqfO",
    "Saber Reflect": "CuAbwhIt3j2V30Ey",
    "Saber Throw": "cCTaCxvsBcbEvbw2",
    "Saber Ward": "RfhP3KotZcqIBmC9",
    "Sanctuary": "1hCkZcduMjx91kSe",
    "Sap Vitality": "ecDdTd9MW0z4h8Hb",
    "Scourge": "6d2wwUGy40FlGqaY",
    "Sense Emotion": "Ns34rjyKzqeydYBH",
    "Sense Force": "O5J8TTpTW7eHLDgG",
    "Sever Force": "LhMmIUjsFrytp0wc",
    "Share Life": "ntUNXx3Uag6BjJJH",
    "Shock": "bF7e5kbzwXj3b2LP",
    "Skill Empowerment": "5tAwilkRcZsTc62q",
    "Slow Descent": "L3P0wzW7j61XpKZc",
    "Slow": "maQoLsCcelDb2hWJ",
    "Sonic Charge": "BMCJlnRZ5j4MlUnU",
    "Spare The Dying": "CJR5SlWKoaCtY1bq",
    "Stasis Field": "oF7fFDz9xqC9ICzm",
    "Stasis": "H51uSnFY6eyBTXRJ",
    "Stun Droid": "83VXTwWszl8bMlW6",
    "Stun": "8UOBsZEV8esbx6IG",
    "Telekinesis": "mnwPexAofsIOp8dD",
    "Telekinetic Burst": "qYnIKhpoJpSflVZh",
    "Telekinetic Storm": "5raHPlhouud0Jpr4",
    "Telekinetic Wave": "T44CmiqinqUjdbHc",
    "Tremor": "CsLjEyQtegNiXKIZ",
    "True Sight": "4bBmcQgYLFIO9GCn",
    "Valor": "2MaAEt5XSnjEurWK",
    "Wall Of Light": "kY1b6BbuiWdIkeYq",
    "Whirlwind": "anxCi1ypITMC1F9Y",
    "Wrack": "sFLwKTBxnM6YfboP"
}
