classfeatures_Ids = {
    # PHB
    "Ability Score Improvement (Berserker)": "9oyy0MMqEws2qoil",
    "Ability Score Improvement (Fighter)": "lKdZc6xD5FCHns3V",
    "Ability Score Improvement (General)": "VYgkXCFMjyEWG41H",
    "Ability Score Improvement (Monk, Operative)": "vLTVWcYw3cnW56OW",
    "Absorb Damage": "UjIepYOFwxWzpBqS",
    "Academic Superiority": "I3UvZaGNY7D1Vyl3",
    "Accomplished Ambusher": "vjzKXTUin4nIeIDJ",
    "Acklay'S Instinct": "FbSpxpXm1xONn0na",
    "Action Surge": "5lGNQ7HmWwhWL9Gf",
    "Adaptable Intellectual": "FI0WoZIEr8HBzXRA",
    "Adaptive Barrier (Engineer: Gadgeteer)": "utG47h4qqKWblu3A",
    "Adaptive Barrier (Scout: Bulwark)": "WvP6k5LuXOxqbn7o",
    "Adaptive Barrier": "vjAOfKzmrVFcwYTh",
    "Additional Fighting Style": "AHnF54FJ2CIZCm0u",
    "Additional Maneuvers (Scholar: Archaeologist)": "psCyhE5cHf06gu6A",
    "Additional Maneuvers (Scholar: Doctor)": "3QWti3hBCcOHMenb",
    "Additional Maneuvers (Scholar: Gambler)": "g8vHPN6X8xr2itzg",
    "Additional Maneuvers (Scholar: Politician)": "1Bo0I3J0R9yjjQIc",
    "Additional Maneuvers (Scholar: Tactician)": "zJffmk1ndwbjk0GH",
    "All-Out Attack": "xq3FuL9roeEDhh6b",
    "Armormech'S Celerity": "go2e9gqD5AnLGKMK",
    "Armstech'S Salvo": "NT36vTfi6iPC2zWL",
    "Armstech'S Strike": "MsKvBWDJd2LV1tvM",
    "Assume The Position": "KdCHmY58LTMxkQbq",
    "At-Will Barrier": "FaWspZu3NJBAI3FS",
    "Bad Feeling": "9rYXdlFyt1WcN5KL",
    "Bantha'S Instinct": "oiT3TJxzRWPKAX9E",
    "Battle Anticipation": "PtL7M75J3a8akz4a",
    "Battle Proficiencies": "hlkmuaFndbYGFtKX",
    "Battle Readiness": "6Sr3sIGSmzAIr5mW",
    "Battlefield Survey": "75l3fkh2X6MP7YQF",
    "Beguiling Presence": "chowZyYpKve4eOGc",
    "Berserker Instincts": "hMiA075EKBBOL2cv",
    "Blade Dance": "6qm81RP5SF3fL6V7",
    "Blade Storm": "htJjJBm0HosLswj9",
    "Blessed By The Force": "GBcVbMG0BBWL0DGC",
    "Blessed Healer": "cXHHpzCSGKw8vRQ8",
    "Blindsense": "NijIH9UDcIlwYmWM",
    "Blistering Rebuke": "w8lV2PlpwsbT2Idf",
    "Blurrg'S Instinct": "cdCx5Hvq2rYRMzRj",
    "Boggdo'S Instinct": "QRnYiJmRk18ekE9v",
    "Bonus Proficiencies (Engineer: Armormech)": "UJVTP58YyoNqEbg6",
    "Bonus Proficiencies (Engineer: Armstech)": "ZUYgGHpQpiGmxo3A",
    "Bonus Proficiencies (Engineer: Gadgeteer)": "Np87HjZydd8pWvrs",
    "Bonus Proficiencies (Engineer: Unstable)": "G1J65CCBk5FuKhf5",
    "Bonus Proficiencies (Fighter: Tactical)": "wIHplALcnef15uBd",
    "Bonus Proficiencies (Guardian: Shien/Djem So)": "SQ38NMuSGq1UFgYZ",
    "Bonus Proficiencies (Guardian: Soresu)": "ECFvPwnnPH2U6Muj",
    "Bonus Proficiencies (Scout: Bulwark)": "zNvb5e1XZ8ItSe75",
    "Bonus Proficiencies (Scout: Slayer)": "MBU2BGh78FZAN3b2",
    "Borrowed Luck": "Y78JOUdUxUJXEfa5",
    "Brawn": "LMvbZfbx0lih3Dbu",
    "Brutal Critical": "bi8G8H5Ur9B3BAyM",
    "Brute Force": "aOjtP2LVp16Q6TeQ",
    "Brutish Durability": "L53F8iKgUHmRpoX4",
    "Bulwark": "nAhvOtXjT3qlVXzp",
    "Calm And Collected": "ZtPzMR1E5kqylmVY",
    "Calm Within The Storm": "p1EP6FF3RmWNr44d",
    "Careful Steps": "anLxaTAHmPqQkmiZ",
    "Center Of The Force": "YQbpwkUPMTaSkhNq",
    "Channel The Force (Makashi)": "2HMgRTnCktSPFpgt",
    "Channel The Force (Niman)": "5PS62OPmM18ws0x9",
    "Channel The Force (Shien/Djem So)": "LEgw0NzwPPkIVWuw",
    "Channel The Force (Soresu)": "G0I4d2dP4K1N4715",
    "Channel The Force": "eBQa0CrHLZmy2bn1",
    "Chirodactyl'S Instinct": "qWV5YogZcpZ3Y3xj",
    "Circle Of Shelter": "MfjwCjpo3JhUZ0SH",
    "Cleansing Touch": "h8JMyCjhTP4Lny10",
    "Cloak Of Shadows": "RljVTnR1IclXnqAv",
    "Close Call": "RFU6FQawnVy3w4TO",
    "Combat Superiority": "liI3fHP0qjCq0N5X",
    "Combat Tech": "nov1Wc7APmyVdzJ4",
    "Commanding Rage": "SlaMlkc4jk0s5dj1",
    "Commando": "FzjcJryoe9J0CEkq",
    "Concealment": "IUjkAqQo7ZvR4IQp",
    "Control The Field": "A8471DUw2PpOmFGi",
    "Creative Destruction": "wgEc1fPVzUOOLiY7",
    "Crimson Armaments": "UeB3t6DmMaGzNijo",
    "Crimson Squall": "8c7Qdhh9vBX7Thxz",
    "Critical Analysis": "snqkp9af24pxhQcv",
    "Cunning Action": "C2RNF2QF8YETIN9a",
    "Damage Absorption": "F2YSxjXkd8Lilvmu",
    "Danger Sense": "kzwSN9SabKgWZZvU",
    "Dark Magick": "NhtBNHmzliOdF3A3",
    "Dead Silence": "gFrxQc1zr8iYeTDA",
    "Defensive Tactics": "CmoydMRbZqwp2VN5",
    "Deflect Missiles": "4XaA12U40vAZxRhi",
    "Deft Hands": "Au1ZMI2rNkielpDK",
    "Delayed Effect": "NHNG6Y6n0xnhSQzs",
    "Delicate Potency": "e59ckcbfMkeZMDqn",
    "Determination": "6eMAnnFSy2Em1tyB",
    "Devastating Critical": "U3ukuB66gtdm8C7V",
    "Dewback'S Instinct": "h1uDhP1tEOuvjRw6",
    "Diamond Soul": "yyGo3f49AlXermtP",
    "Disciple Of Life": "ba3N86GYUCNFQHKm",
    "Discoveries (Doctor)": "lHfSIS1I14hKp6wO",
    "Discoveries (Gambler)": "2F3RlN4VyyAG2XrU",
    "Discoveries (Politician)": "bRDz6yfrDH3IA5F9",
    "Discoveries (Tactician)": "IlZ1K1GB0hW4YaSq",
    "Discovery": "GcqKzVpUB8P50O4u",
    "Disruptive Throw": "BuYICkux4graA2wP",
    "Distracting Countenance": "d7wAQPshxavsna3o",
    "Distracting Shot": "p3pkLOyrjIOHwMQS",
    "Dive For Cover": "9yuZhwF1bwFRb1xj",
    "Double Tap (Operative: Sharpshooter)": "7oDo92yMLpT66oRw",
    "Down, Not Out": "Ml6ZJY0Lubl3zk94",
    "Electric Attunement": "yZcoaSioqe8qda2D",
    "Elusive": "NlVBCeG99JoWF7QP",
    "Empty Body": "ERwe3KxzfhCnh70G",
    "Engineering Bombardment": "boJLDGKWXUcLVjT6",
    "Enhanced Strikes": "RoBYgglH8V1FjCSV",
    "Enlightened Evasion": "bfI8uiDYajYnDMXR",
    "Enlightenment": "LRGphxf8XUI9MDwb",
    "Enthralling Vigor": "qE8tqnNJQQYekBrS",
    "Entropic Rush": "oyj6hBqv5Qk4rJVQ",
    "Evasion": "HdWZ2lQgsbEnra24",
    "Experimental Overrides": "oVrxpyekQy3Wnito",
    "Expertise (Operative)": "UlaeWMHJ5WJ1BHbV",
    "Expertise (Scholar)": "orh1WLvpakTpsitA",
    "Expertise (Scout)": "IB1sPazhmp63mLHF",
    "Explosive": "DCz99P3FezIv9TqP",
    "Extra Attack (Berserker)": "dPWmHiWmpnhHTsgd",
    "Extra Attack (Engineer: Armormech)": "ScLH8xRV8QXmxeRh",
    "Extra Attack": "XunBynvxZH9qkNEs",
    "Fascinating Display": "Qz3oXfqQ35dbneST",
    "Fast And Agile": "IkM7PeTwXZA5XHk8",
    "Feral Impulse": "pMEmIt3NWThbee8k",
    "Field Surgeon": "5RNqaMT7MouwaybB",
    "Fighter'S Instinct": "KDiQ8O2evV2Z1YTo",
    "Fighting Mastery": "xWOwi6l4lIQ33Qi0",
    "Fighting Style (Fighter)": "X4PnDFr2JiWjuYEl",
    "Fighting Style (Guardian)": "5LIZH5J156FPC8Ar",
    "Fighting Style (Scout)": "vzwNHMqfV57Lr252",
    "Fire As One": "vIBCNYhk5Z7GWVyL",
    "Firestorm": "8siCD9NgvKURO3WW",
    "Focus": "k6PmkEsEbxKy6xAs",
    "Focused Burst": "OWtFvWvqcOQFnh4M",
    "Focused Flow": "rFN0AQJq70DP6qpS",
    "Focused Rage": "zZz07JN0gA6nsAPa",
    "Foe Slayer": "mNXuHAozg3qRMjRW",
    "Force Affinity": "clqWkMqYU6AWbbz9",
    "Force Of Personality": "SAbD83Dx58emp6OY",
    "Force Purity": "AN9BrAR4d9f3fopu",
    "Force Recovery": "3qzL7p1j5m4LlIah",
    "Force Shield": "sQ9c8Bnuj93ozEPr",
    "Force Storm": "dtp98aDdpaAZHTnu",
    "Force-Empowered Casting": "vqxJzX2jON1LZuAS",
    "Force-Empowered Self": "2jowNrxwqUrXnIlu",
    "Force-Empowered Strikes": "pd9SrIEnZ04Ihwtw",
    "Force-Enhanced Strikes": "6yrORGVIi0v9jqNx",
    "Forceblade Bond": "0jI04KjGE8eJ8NFk",
    "Forceblade Mastery": "P5jlHfbFfEgppwin",
    "Forcecasting (Beguiler)": "9WqFDIoxzXWbOsYD",
    "Forcecasting (Berserker: Marauder)": "EPGAauN1vsRbA4lV",
    "Forcecasting (Consular)": "OwFJ3XWTg2ECPPqS",
    "Forcecasting (Guardian)": "MtepDwfpKxdqXPXv",
    "Forcecasting (Operative: Beguiler)": "3jBAw3l2ulXKcqLV",
    "Forcecasting (Sentinel)": "OPmnvVAKt8P3mRzr",
    "Form Basics (Makashi)": "iezmgPTeM1wL1JCR",
    "Form Basics (Niman)": "nyjlNDLKGtETTzDY",
    "Form Basics (Shien/Djem So)": "C5m7AvcNqJiFAi5P",
    "Form Basics (Soresu)": "jepI5WREQw8jlEtg",
    "Furious Force": "PysR7YJIeMZG5ACJ",
    "Fyrnock'S Instinct": "v4CZJ8LBMl5PYZCO",
    "Gadgeteer Harness": "6SND1rFXxTWOyREh",
    "Gambler'S Aptitude": "bSfH6gmGAeJWWSwq",
    "Glancing Blow": "qEB0qRRtzWUeHji7",
    "Greater Extra Attack": "Qqp4sbAvV5R3xgO4",
    "Greater Inspiring Surge": "m15815dwhOhsvV9M",
    "Greater Signature Maneuver": "VI7yPQlf403Sc2kx",
    "Guardian Aura": "TE8Ntdf1x7zULfHU",
    "Hawk'S Instinct": "WTBhKJgkArQI3Tgv",
    "Head Shot": "n6vcm8JRdZFZCA2t",
    "Hunter'S Prey": "mwFCS2UnVVoYdhzx",
    "Ichor Lightning": "0S9V08vxNWCytOmw",
    "Improved Aerial Agility": "JXn1yWPzzWjQfuq8",
    "Improved Combat Superiority": "FgzDinvrDELxPNhc",
    "Improved Danger Sense": "4xUvdPmOAggsvACD",
    "Improved Force-Empowered Strikes": "hYDyNw2x54iCf0nL",
    "Improved Suppression": "lodf5wG7aGu4dWW0",
    "Indomitable (Sentinel: Tenacity)": "c5gqtKDUKlaW0IFw",
    "Indomitable Might": "fFKNqUAWh0ZOhvRc",
    "Indomitable": "9S5WXTvLPUjhP6Qy",
    "Infuse Item": "5MSNIuwM4DtqFzxV",
    "Inspiring Presence": "HBT87umTugPVJBT7",
    "Inspiring Surge": "kHgHQIqjp3X6v93c",
    "Instinctive Leap": "GzfX3ZSoFVyyHbH1",
    "Katarn'S Instinct": "sgJdISZMtwv08WPJ",
    "Know Your Enemy": "GuyZIHUnTINGFLXQ",
    "Knowledge Unbound": "6SyXNLWcjSmB8Z0l",
    "Led By The Force": "pnIrrDmqB5GosVJC",
    "Living Current": "xLmHLKF5gZn3nX0n",
    "Llothcat'S Instinct": "DlYiCiG39R0goG9u",
    "Lucky Number 7": "Ek37RSvjDaJp3MkR",
    "Maneuver Mastery": "RQnRq0u0DbUJcO58",
    "Mark Of The Bulwark": "9NuNAt7XM4a8n426",
    "Mark Of The Hunter": "jkV1oThkNziwTd9W",
    "Mark Of The Slayer": "Ln96Hf2aqqbYiy9o",
    "Mark Of The Stalker": "78p9F2BB4sD7ojAn",
    "Martial Arts": "aR0lm7tWLj6TSFj5",
    "Master Of Combat": "0L38TGkU8ViI7klt",
    "Master Of Contention": "8s1p8tD0y0e3Fcm6",
    "Master Of Moderation": "1a5Un991dfb6whRr",
    "Master Of Perseverance": "UvMKVj608ijSAfgd",
    "Master Of Resilience": "g1r7gEz0DT78nTIf",
    "Master Strike": "2gNENhRMngBSCGae",
    "Mastery Of Death": "lmeny3CW1A6YZ9KH",
    "Maximum Output": "zEnd8MGQwyOOZ0dI",
    "Medical Practitioner": "4kLXvFjUFd6BJGkS",
    "Mesmerizing Presence": "fwO5oavJvDKyoMTS",
    "Modified Armor": "PNV1FnFfvmg1jYIe",
    "Modified Tinkercannon": "u6LYZxy7ZKsD0LY5",
    "Modified Weaponry": "OEiv2Yjz1QhM3osS",
    "Monastic Vows": "Wfc2dF25ZJ2TLNID",
    "Motivating Diplomat": "9NWkUxgMtOIo0qgh",
    "Multiattack": "kk16fzUU7IFma2Vj",
    "Multitasker": "raPAMeGzpxc3NrXj",
    "My Little Friend Says Hello There": "f9JvCohVnIKR3kXb",
    "Nemesis": "mMHcv3kuR9Ef8Sin",
    "One With The Blade": "8a0uFLTBNeZWDHqO",
    "One With The Force (Consular)": "SRvdjRxU3cpcEdcw",
    "One With The Force": "gSGeitc98ItAwhfF",
    "Operative Exploits": "cbdn2Isx1w9y50pQ",
    "Out Of Mind": "1Ddq2hwpr2dTJI2C",
    "Overwhelm": "bPPhHr2oAZGmovhh",
    "Panacea": "oj5YJYw3sN0iB3An",
    "Path Of The Echani": "7EFy4psVKFV8Txr5",
    "Pathfinder": "M6DPXcwX644UAsW3",
    "Perfect Body": "F6c5xj10sxAKo4nX",
    "Persistent Rage": "YHPUv9lN3nCapAgP",
    "Personal Barrier": "FM20QrLGK4qb1mbb",
    "Phasethrow": "zvvBD6LZuu9tdrUV",
    "Placed Shots": "xLWuR3Z2WROW7Ggm",
    "Potent Aptitude": "Cs1w1VQtleVIrrIn",
    "Potent Lightning": "iAXtCCtwP3ecc8OF",
    "Powerful Presence": "aGAQYc3CH95QAgm5",
    "Predator'S Instinct": "dTdbL8dypa6BAdnP",
    "Presence": "cmlYUe6Bod6p8iOm",
    "Preserve Life": "ZU13gEZVPufJ7Csp",
    "Primal Champion": "IWTDawTUf79eWbEV",
    "Projected Barrier (Consular: Balance)": "E2udC6wpGwnihK6M",
    "Projected Barrier (Engineer: Gadgeteer)": "yahaPxpXfPalRqxt",
    "Projected Barrier (Scout: Bulwark)": "TlH3uqCgobccF5zp",
    "Projected Barrier": "g1UHScqDJ7djuTcg",
    "Projected Barrier": "xlWuywb2jzmQV9MC",
    "Pure Performance": "073Ve3axeog6D1eO",
    "Purity Of Body": "wBdYcwBoZm5KFnSn",
    "Quick Thinking": "04YaNAIpdScc9WuJ",
    "Quickdraw": "AlQqDDigFMnrLi7h",
    "Rage": "rPOLy96fW96N2UPg",
    "Raid Planning": "Rii7wMd3z3cG9bk4",
    "Rallying Cry": "2dNKCtW7jCM0xNgT",
    "Rampage": "zxw8tBx6Z30RKyLr",
    "Rancor'S Instinct": "yGC9VzT840qQWxca",
    "Ranger'S Quarry": "hWwTW7oKFDE41JWj",
    "Reassemble": "X4Q1XRpCIyxBk9qy",
    "Reckless Attack": "Q1JyHnVs9iIEBs91",
    "Reckless Power": "SU5JDQ8GNySPSphF",
    "Redirect": "uiG3g9c7gdpYNrD0",
    "Regenerative Shielding": "D58MeVMuebapihem",
    "Reinforced Barriers": "Wegdgh47OgwcBgBD",
    "Relentless Rage": "eWbTifdXJvvXT4CV",
    "Relentless": "TuoWxmjG9LjToCSX",
    "Reliable Talent": "FZRJYmLnbF0tIoAK",
    "Remarkable Athlete": "ejRFTWGKdTdtU1gH",
    "Remote Healer": "TyzlB0iUbeeyXPVk",
    "Resuscitate": "IrkHv7duOnw3Ilgy",
    "Retaliatory Strike": "shHFJ7KWhcnoOrQF",
    "Ricochet Shot": "ojtZlS89GEGWXnwP",
    "Risk Versus Reward": "RBJTHUlo3FTY2RNR",
    "Rock Steady": "lzjIEK50kr1cwqUt",
    "Sage Advice": "WlSOL3kItS4UFnij",
    "Savage Diplomat": "qT7NSLR6mY5yk2xc",
    "Scout Routine": "pW0ObQnHARhqg4V0",
    "Scout Routines": "QwDExZ4sYBdx4d4o",
    "Second Wind": "bMmeeDNTAIqgqH4f",
    "Sentinel Ideals": "xFgXRg2qF3SlvNfF",
    "Shadow Step": "7OeCPWLGtPieEOxx",
    "Shadow Strike": "u07a2ZXQlokyBClQ",
    "Shadow'S Wrath": "UALQWbDzmp6H8Uiq",
    "Sharpen The Blade": "fWurALtwA2SByaXb",
    "Shatterpoint": "V5fEHh7NEGB6h0ei",
    "Shocking Affinity": "w2fcITzwIWxmBuLs",
    "Signature Maneuver": "DfcV6ep6pokDQmlk",
    "Silver Tongue": "VX0o502nLafrWzbA",
    "Slayer'S Counter": "21o2m4T6nKInTyiI",
    "Slayer'S Pride": "r2ZOqWzZzhkUmSoV",
    "Slippery Mind": "SfWAWVfaCZJChcx2",
    "Slow Fall": "TH8uVHJVECGYQeO1",
    "Sneak Attack": "DOR6WSQLFSFTURno",
    "Sovereign Protector": "dLfWtRWtN2DVPXtT",
    "Spinning Flourish": "IfkarBD3hTnNQJ14",
    "Spirit Blade Assault": "yMSvK9SmLoLI29p2",
    "Stalker'S Dodge": "neI83QoBohA6gEqz",
    "Stalker'S Fury": "0vKdMFsjX0vU9vaw",
    "Stand Against The Tide": "j9tueB66NHAi9XRK",
    "Stay In Formation": "PWRce8jzPuXlGfPE",
    "Stillness Of Mind": "71u1CPfFOBP2UZgi",
    "Straight Through": "DVBWZvttZhH2ZECU",
    "Stroke Of Luck": "jjkfkR3y4ZzLvhRc",
    "Stunning Strike": "YO47dPo3A0QCh006",
    "Subtle Control": "cGv4yOyQ5ZPihigt",
    "Subtle Presence": "pWu7ql7UFckNjgmK",
    "Suit Reliability": "VCwqg2o0ePLxL0s3",
    "Superior Hunter'S Defense": "LLSeCmTx42FanV5K",
    "Supernatural Defense": "fDrprD1zPyK36J4Q",
    "Supreme Awareness": "x1TSm5F0CtGuX7u4",
    "Supreme Healing": "ow8lboCU7nSy3dyd",
    "Supreme Sneak": "6bY5UEP9vMlJjmvA",
    "Survivor": "mUQpy94CIAOkbxC1",
    "Tactical Mastery": "quoqL3EKsr7gMDCP",
    "Tactician'S Instinct": "ROdICoWR82v6A2Rf",
    "Targeting Matrix": "vxR8oI3jyjVUt5sJ",
    "Tech Mastery": "f1XeMafaqejD02MW",
    "Techcasting (Engineer)": "2cPRZiAJPegsDJEt",
    "Techcasting (Fighter: Shield)": "qNNFQgODkmI77xfE",
    "Techcasting (Scout)": "F4I387qfbiqbeaOO",
    "Tell Me The Odds": "vABtgK0Jau0b6cTl",
    "Terentatek'S Instinct": "Hg8zYh1iXL0DGUVq",
    "The Way Of The Mynock": "GqrLoLcbeHSTnGaD",
    "The Way Of The Rancor": "D3B5ASfcxCsFbpj1",
    "The Way Of They Krayt Dragon": "HgO4Lo3fbWIRyhlp",
    "Thief'S Reflexes": "0QBWeM5Z0iSgUShC",
    "Thunderous Momentum": "1oiBleXKcbvKHz4e",
    "Timeless Vessel": "ZoEt4JpvUya3an75",
    "Tool Expertise": "B2qE4c6O2D4uhKjl",
    "Tracker'S Instinct": "Cid5ujSdnooH0vMm",
    "Trick Shooter": "lLNBqCC6iexP68We",
    "Twin Saber Throw": "6VhggjCLnsuOPBiO",
    "Unarmored Defense (Berserker)": "1P7kIHNyx9mc8CX0",
    "Unarmored Defense (Monk)": "ESaIFP1ov25wZCMi",
    "Unarmored Defense": "IDt6duVrBzL8euRc",
    "Unarmored Movement": "zzbwoqUNCb6U0lRK",
    "Uncanny Dodge": "szBvqoou8yziMCmN",
    "Unerring Accuracy": "xsN7QCSQmiloh5oF",
    "Unlimited Power": "s0Bf6Sv2exQNH7vK",
    "Unstable Volley": "aT3vCPrH46ei2O6v",
    "Unstoppable Force": "Uysua3MJxqqdHu0i",
    "Varactyl'S Instinct": "sfEr8ZBFVddlfLeF",
    "Versatile Direction": "ZuL4WCeoY7TvBdZx",
    "Vigilant Sentinel": "jCEl3lIz7FBJMAMa",
    "Voltaic Slash": "iFg9kA5mtj22OgKf",
    "War Chant": "UYWFpXz6HKecYIC2"
}
