classfeatures_Ids = {
    # PHB
    "Ability Score Improvement (Berserker)": "9oyy0MMqEws2qoil",
    "Ability Score Improvement (Fighter)": "lKdZc6xD5FCHns3V",
    "Ability Score Improvement (General)": "VYgkXCFMjyEWG41H",
    "Ability Score Improvement (Monk, Operative)": "vLTVWcYw3cnW56OW",
    "Absorb Damage": "UjIepYOFwxWzpBqS",
    "Academic Superiority": "I3UvZaGNY7D1Vyl3",
    "Accomplished Ambusher": "vjzKXTUin4nIeIDJ",
    "Acklay's Instinct": "FbSpxpXm1xONn0na",
    "Action Surge": "5lGNQ7HmWwhWL9Gf",
    "Adaptable Intellectual": "FI0WoZIEr8HBzXRA",
    "Adaptive Barrier (Engineer: Gadgeteer)": "utG47h4qqKWblu3A",
    "Adaptive Barrier (Scout: Bulwark)": "WvP6k5LuXOxqbn7o",
    "Adaptive Barrier": "vjAOfKzmrVFcwYTh",
    "Additional Fighting Style": "AHnF54FJ2CIZCm0u",
    "Additional Maneuvers (Scholar: Archaeologist)": "psCyhE5cHf06gu6A",
    "Additional Maneuvers (Scholar: Doctor)": "3QWti3hBCcOHMenb",
    "Additional Maneuvers (Scholar: Gambler)": "g8vHPN6X8xr2itzg",
    "Additional Maneuvers (Scholar: Politician)": "1Bo0I3J0R9yjjQIc",
    "Additional Maneuvers (Scholar: Tactician)": "zJffmk1ndwbjk0GH",
    "All-out Attack": "xq3FuL9roeEDhh6b",
    "Armormech's Celerity": "go2e9gqD5AnLGKMK",
    "Armstech's Salvo": "NT36vTfi6iPC2zWL",
    "Armstech's Strike": "MsKvBWDJd2LV1tvM",
    "Assume The Position": "KdCHmY58LTMxkQbq",
    "At-will Barrier": "FaWspZu3NJBAI3FS",
    "Bad Feeling": "9rYXdlFyt1WcN5KL",
    "Bantha's Instinct": "oiT3TJxzRWPKAX9E",
    "Battle Anticipation": "PtL7M75J3a8akz4a",
    "Battle Proficiencies": "hlkmuaFndbYGFtKX",
    "Battle Readiness": "6Sr3sIGSmzAIr5mW",
    "Battlefield Survey": "75l3fkh2X6MP7YQF",
    "Beguiling Presence": "chowZyYpKve4eOGc",
    "Berserker Instincts": "hMiA075EKBBOL2cv",
    "Blade Dance": "6qm81RP5SF3fL6V7",
    "Blade Storm": "htJjJBm0HosLswj9",
    "Blessed By The Force": "GBcVbMG0BBWL0DGC",
    "Blessed Healer": "cXHHpzCSGKw8vRQ8",
    "Blindsense": "NijIH9UDcIlwYmWM",
    "Blistering Rebuke": "w8lV2PlpwsbT2Idf",
    "Blurrg's Instinct": "cdCx5Hvq2rYRMzRj",
    "Boggdo's Instinct": "QRnYiJmRk18ekE9v",
    "Bonus Proficiencies (Engineer: Armormech)": "UJVTP58YyoNqEbg6",
    "Bonus Proficiencies (Engineer: Armstech)": "ZUYgGHpQpiGmxo3A",
    "Bonus Proficiencies (Engineer: Gadgeteer)": "Np87HjZydd8pWvrs",
    "Bonus Proficiencies (Engineer: Unstable)": "G1J65CCBk5FuKhf5",
    "Bonus Proficiencies (Fighter: Tactical)": "wIHplALcnef15uBd",
    "Bonus Proficiencies (Guardian: Shien/djem So)": "SQ38NMuSGq1UFgYZ",  # TODO: Fix caps
    "Bonus Proficiencies (Guardian: Soresu)": "ECFvPwnnPH2U6Muj",
    "Bonus Proficiencies (Scout: Bulwark)": "zNvb5e1XZ8ItSe75",
    "Bonus Proficiencies (Scout: Slayer)": "MBU2BGh78FZAN3b2",
    "Borrowed Luck": "Y78JOUdUxUJXEfa5",
    "Brawn": "LMvbZfbx0lih3Dbu",
    "Brutal Critical": "bi8G8H5Ur9B3BAyM",
    "Brute Force": "aOjtP2LVp16Q6TeQ",
    "Brutish Durability": "L53F8iKgUHmRpoX4",
    "Bulwark": "nAhvOtXjT3qlVXzp",
    "Calm And Collected": "ZtPzMR1E5kqylmVY",
    "Calm Within The Storm": "p1EP6FF3RmWNr44d",
    "Careful Steps": "anLxaTAHmPqQkmiZ",
    "Center Of The Force": "YQbpwkUPMTaSkhNq",
    "Channel The Force (Makashi)": "2HMgRTnCktSPFpgt",
    "Channel The Force (Niman)": "5PS62OPmM18ws0x9",
    "Channel The Force (Shien/djem So)": "LEgw0NzwPPkIVWuw",  # TODO: Fix caps
    "Channel The Force (Soresu)": "G0I4d2dP4K1N4715",
    "Channel The Force": "eBQa0CrHLZmy2bn1",
    "Chirodactyl's Instinct": "qWV5YogZcpZ3Y3xj",
    "Circle Of Shelter": "MfjwCjpo3JhUZ0SH",
    "Cleansing Touch": "h8JMyCjhTP4Lny10",
    "Cloak Of Shadows": "RljVTnR1IclXnqAv",
    "Close Call": "RFU6FQawnVy3w4TO",
    "Combat Superiority": "liI3fHP0qjCq0N5X",
    "Combat Tech": "nov1Wc7APmyVdzJ4",
    "Commanding Rage": "SlaMlkc4jk0s5dj1",
    "Commando": "FzjcJryoe9J0CEkq",
    "Concealment": "IUjkAqQo7ZvR4IQp",
    "Control The Field": "A8471DUw2PpOmFGi",
    "Creative Destruction": "wgEc1fPVzUOOLiY7",
    "Crimson Armaments": "UeB3t6DmMaGzNijo",
    "Crimson Squall": "8c7Qdhh9vBX7Thxz",
    "Critical Analysis": "snqkp9af24pxhQcv",
    "Cunning Action": "C2RNF2QF8YETIN9a",
    "Damage Absorption": "F2YSxjXkd8Lilvmu",
    "Danger Sense": "kzwSN9SabKgWZZvU",
    "Dark Magick": "NhtBNHmzliOdF3A3",
    "Dead Silence": "gFrxQc1zr8iYeTDA",
    "Defensive Tactics": "CmoydMRbZqwp2VN5",
    "Deflect Missiles": "4XaA12U40vAZxRhi",
    "Deft Hands": "Au1ZMI2rNkielpDK",
    "Delayed Effect": "NHNG6Y6n0xnhSQzs",
    "Delicate Potency": "e59ckcbfMkeZMDqn",
    "Determination": "6eMAnnFSy2Em1tyB",
    "Devastating Critical": "U3ukuB66gtdm8C7V",
    "Dewback's Instinct": "h1uDhP1tEOuvjRw6",
    "Diamond Soul": "yyGo3f49AlXermtP",
    "Disciple Of Life": "ba3N86GYUCNFQHKm",
    "Discoveries (Doctor)": "lHfSIS1I14hKp6wO",
    "Discoveries (Gambler)": "2F3RlN4VyyAG2XrU",
    "Discoveries (Politician)": "bRDz6yfrDH3IA5F9",
    "Discoveries (Tactician)": "IlZ1K1GB0hW4YaSq",
    "Discovery": "GcqKzVpUB8P50O4u",
    "Disruptive Throw": "BuYICkux4graA2wP",
    "Distracting Countenance": "d7wAQPshxavsna3o",
    "Distracting Shot": "p3pkLOyrjIOHwMQS",
    "Dive For Cover": "9yuZhwF1bwFRb1xj",
    "Double Tap (Operative: Sharpshooter)": "7oDo92yMLpT66oRw",
    "Down, Not Out": "Ml6ZJY0Lubl3zk94",
    "Electric Attunement": "yZcoaSioqe8qda2D",
    "Elusive": "NlVBCeG99JoWF7QP",
    "Empty Body": "ERwe3KxzfhCnh70G",
    "Engineering Bombardment": "boJLDGKWXUcLVjT6",
    "Enhanced Strikes": "RoBYgglH8V1FjCSV",
    "Enlightened Evasion": "bfI8uiDYajYnDMXR",
    "Enlightenment": "LRGphxf8XUI9MDwb",
    "Enthralling Vigor": "qE8tqnNJQQYekBrS",
    "Entropic Rush": "oyj6hBqv5Qk4rJVQ",
    "Evasion": "HdWZ2lQgsbEnra24",
    "Experimental Overrides": "oVrxpyekQy3Wnito",
    "Expertise (Operative)": "UlaeWMHJ5WJ1BHbV",
    "Expertise (Scholar)": "orh1WLvpakTpsitA",
    "Expertise (Scout)": "IB1sPazhmp63mLHF",
    "Explosive": "DCz99P3FezIv9TqP",
    "Extra Attack (Berserker)": "dPWmHiWmpnhHTsgd",
    "Extra Attack (Engineer: Armormech)": "ScLH8xRV8QXmxeRh",
    "Extra Attack": "XunBynvxZH9qkNEs",
    "Fascinating Display": "Qz3oXfqQ35dbneST",
    "Fast And Agile": "IkM7PeTwXZA5XHk8",
    "Feral Impulse": "pMEmIt3NWThbee8k",
    "Field Surgeon": "5RNqaMT7MouwaybB",
    "Fighter's Instinct": "KDiQ8O2evV2Z1YTo",
    "Fighting Mastery": "xWOwi6l4lIQ33Qi0",
    "Fighting Style (Fighter)": "X4PnDFr2JiWjuYEl",
    "Fighting Style (Guardian)": "5LIZH5J156FPC8Ar",
    "Fighting Style (Scout)": "vzwNHMqfV57Lr252",
    "Fire As One": "vIBCNYhk5Z7GWVyL",
    "Firestorm": "8siCD9NgvKURO3WW",
    "Focus": "k6PmkEsEbxKy6xAs",
    "Focused Burst": "OWtFvWvqcOQFnh4M",
    "Focused Flow": "rFN0AQJq70DP6qpS",
    "Focused Rage": "zZz07JN0gA6nsAPa",
    "Foe Slayer": "mNXuHAozg3qRMjRW",
    "Force Affinity": "clqWkMqYU6AWbbz9",
    "Force Of Personality": "SAbD83Dx58emp6OY",
    "Force Purity": "AN9BrAR4d9f3fopu",
    "Force Recovery": "3qzL7p1j5m4LlIah",
    "Force Shield": "sQ9c8Bnuj93ozEPr",
    "Force Storm": "dtp98aDdpaAZHTnu",
    "Force-empowered Casting": "vqxJzX2jON1LZuAS",
    "Force-empowered Self": "2jowNrxwqUrXnIlu",
    "Force-empowered Strikes": "pd9SrIEnZ04Ihwtw",
    "Force-enhanced Strikes": "6yrORGVIi0v9jqNx",
    "Forceblade Bond": "0jI04KjGE8eJ8NFk",
    "Forceblade Mastery": "P5jlHfbFfEgppwin",
    "Forcecasting (Beguiler)": "9WqFDIoxzXWbOsYD",
    "Forcecasting (Berserker: Marauder)": "EPGAauN1vsRbA4lV",
    "Forcecasting (Consular)": "OwFJ3XWTg2ECPPqS",
    "Forcecasting (Guardian)": "MtepDwfpKxdqXPXv",
    "Forcecasting (Operative: Beguiler)": "3jBAw3l2ulXKcqLV",
    "Forcecasting (Sentinel)": "OPmnvVAKt8P3mRzr",
    "Form Basics (Makashi)": "iezmgPTeM1wL1JCR",
    "Form Basics (Niman)": "nyjlNDLKGtETTzDY",
    "Form Basics (Shien/djem So)": "C5m7AvcNqJiFAi5P",  # TODO: Fix caps
    "Form Basics (Soresu)": "jepI5WREQw8jlEtg",
    "Furious Force": "PysR7YJIeMZG5ACJ",
    "Fyrnock's Instinct": "v4CZJ8LBMl5PYZCO",
    "Gadgeteer Harness": "6SND1rFXxTWOyREh",
    "Gambler's Aptitude": "bSfH6gmGAeJWWSwq",
    "Glancing Blow": "qEB0qRRtzWUeHji7",
    "Greater Extra Attack": "Qqp4sbAvV5R3xgO4",
    "Greater Inspiring Surge": "m15815dwhOhsvV9M",
    "Greater Signature Maneuver": "VI7yPQlf403Sc2kx",
    "Guardian Aura": "TE8Ntdf1x7zULfHU",
    "Hawk's Instinct": "WTBhKJgkArQI3Tgv",
    "Head Shot": "n6vcm8JRdZFZCA2t",
    "Hunter's Prey": "mwFCS2UnVVoYdhzx",
    "Ichor Lightning": "0S9V08vxNWCytOmw",
    "Improved Aerial Agility": "JXn1yWPzzWjQfuq8",
    "Improved Combat Superiority": "FgzDinvrDELxPNhc",
    "Improved Danger Sense": "4xUvdPmOAggsvACD",
    "Improved Force-empowered Strikes": "hYDyNw2x54iCf0nL",
    "Improved Suppression": "lodf5wG7aGu4dWW0",
    "Indomitable (Sentinel: Tenacity)": "c5gqtKDUKlaW0IFw",
    "Indomitable Might": "fFKNqUAWh0ZOhvRc",
    "Indomitable": "9S5WXTvLPUjhP6Qy",
    "Infuse Item": "5MSNIuwM4DtqFzxV",
    "Inspiring Presence": "HBT87umTugPVJBT7",
    "Inspiring Surge": "kHgHQIqjp3X6v93c",
    "Instinctive Leap": "GzfX3ZSoFVyyHbH1",
    "Katarn's Instinct": "sgJdISZMtwv08WPJ",
    "Know Your Enemy": "GuyZIHUnTINGFLXQ",
    "Knowledge Unbound": "6SyXNLWcjSmB8Z0l",
    "Led By The Force": "pnIrrDmqB5GosVJC",
    "Living Current": "xLmHLKF5gZn3nX0n",
    "Llothcat's Instinct": "DlYiCiG39R0goG9u",
    "Lucky Number 7": "Ek37RSvjDaJp3MkR",
    "Maneuver Mastery": "RQnRq0u0DbUJcO58",
    "Mark Of The Bulwark": "9NuNAt7XM4a8n426",
    "Mark Of The Hunter": "jkV1oThkNziwTd9W",
    "Mark Of The Slayer": "Ln96Hf2aqqbYiy9o",
    "Mark Of The Stalker": "78p9F2BB4sD7ojAn",
    "Martial Arts": "aR0lm7tWLj6TSFj5",
    "Master Of Combat": "0L38TGkU8ViI7klt",
    "Master Of Contention": "8s1p8tD0y0e3Fcm6",
    "Master Of Moderation": "1a5Un991dfb6whRr",
    "Master Of Perseverance": "UvMKVj608ijSAfgd",
    "Master Of Resilience": "g1r7gEz0DT78nTIf",
    "Master Strike": "2gNENhRMngBSCGae",
    "Mastery Of Death": "lmeny3CW1A6YZ9KH",
    "Maximum Output": "zEnd8MGQwyOOZ0dI",
    "Medical Practitioner": "4kLXvFjUFd6BJGkS",
    "Mesmerizing Presence": "fwO5oavJvDKyoMTS",
    "Modified Armor": "PNV1FnFfvmg1jYIe",
    "Modified Tinkercannon": "u6LYZxy7ZKsD0LY5",
    "Modified Weaponry": "OEiv2Yjz1QhM3osS",
    "Monastic Vows": "Wfc2dF25ZJ2TLNID",
    "Motivating Diplomat": "9NWkUxgMtOIo0qgh",
    "Multiattack": "kk16fzUU7IFma2Vj",
    "Multitasker": "raPAMeGzpxc3NrXj",
    "My Little Friend Says Hello There": "f9JvCohVnIKR3kXb",
    "Nemesis": "mMHcv3kuR9Ef8Sin",
    "One With The Blade": "8a0uFLTBNeZWDHqO",
    "One With The Force (Consular)": "SRvdjRxU3cpcEdcw",
    "One With The Force": "gSGeitc98ItAwhfF",
    "Operative Exploits": "cbdn2Isx1w9y50pQ",
    "Out Of Mind": "1Ddq2hwpr2dTJI2C",
    "Overwhelm": "bPPhHr2oAZGmovhh",
    "Panacea": "oj5YJYw3sN0iB3An",
    "Path Of The Echani": "7EFy4psVKFV8Txr5",
    "Pathfinder": "M6DPXcwX644UAsW3",
    "Perfect Body": "F6c5xj10sxAKo4nX",
    "Persistent Rage": "YHPUv9lN3nCapAgP",
    "Personal Barrier": "FM20QrLGK4qb1mbb",
    "Phasethrow": "zvvBD6LZuu9tdrUV",
    "Placed Shots": "xLWuR3Z2WROW7Ggm",
    "Potent Aptitude": "Cs1w1VQtleVIrrIn",
    "Potent Lightning": "iAXtCCtwP3ecc8OF",
    "Powerful Presence": "aGAQYc3CH95QAgm5",
    "Predator's Instinct": "dTdbL8dypa6BAdnP",
    "Presence": "cmlYUe6Bod6p8iOm",
    "Preserve Life": "ZU13gEZVPufJ7Csp",
    "Primal Champion": "IWTDawTUf79eWbEV",
    "Projected Barrier (Consular: Balance)": "E2udC6wpGwnihK6M",
    "Projected Barrier (Engineer: Gadgeteer)": "yahaPxpXfPalRqxt",
    "Projected Barrier (Scout: Bulwark)": "TlH3uqCgobccF5zp",
    "Projected Barrier": "g1UHScqDJ7djuTcg",
    "Projected Barrier": "xlWuywb2jzmQV9MC",
    "Pure Performance": "073Ve3axeog6D1eO",
    "Purity Of Body": "wBdYcwBoZm5KFnSn",
    "Quick Thinking": "04YaNAIpdScc9WuJ",
    "Quickdraw": "AlQqDDigFMnrLi7h",
    "Rage": "rPOLy96fW96N2UPg",
    "Raid Planning": "Rii7wMd3z3cG9bk4",
    "Rallying Cry": "2dNKCtW7jCM0xNgT",
    "Rampage": "zxw8tBx6Z30RKyLr",
    "Rancor's Instinct": "yGC9VzT840qQWxca",
    "Ranger's Quarry": "hWwTW7oKFDE41JWj",
    "Reassemble": "X4Q1XRpCIyxBk9qy",
    "Reckless Attack": "Q1JyHnVs9iIEBs91",
    "Reckless Power": "SU5JDQ8GNySPSphF",
    "Redirect": "uiG3g9c7gdpYNrD0",
    "Regenerative Shielding": "D58MeVMuebapihem",
    "Reinforced Barriers": "Wegdgh47OgwcBgBD",
    "Relentless Rage": "eWbTifdXJvvXT4CV",
    "Relentless": "TuoWxmjG9LjToCSX",
    "Reliable Talent": "FZRJYmLnbF0tIoAK",
    "Remarkable Athlete": "ejRFTWGKdTdtU1gH",
    "Remote Healer": "TyzlB0iUbeeyXPVk",
    "Resuscitate": "IrkHv7duOnw3Ilgy",
    "Retaliatory Strike": "shHFJ7KWhcnoOrQF",
    "Ricochet Shot": "ojtZlS89GEGWXnwP",
    "Risk Versus Reward": "RBJTHUlo3FTY2RNR",
    "Rock Steady": "lzjIEK50kr1cwqUt",
    "Sage Advice": "WlSOL3kItS4UFnij",
    "Savage Diplomat": "qT7NSLR6mY5yk2xc",
    "Scout Routine": "pW0ObQnHARhqg4V0",
    "Scout Routines": "QwDExZ4sYBdx4d4o",
    "Second Wind": "bMmeeDNTAIqgqH4f",
    "Sentinel Ideals": "xFgXRg2qF3SlvNfF",
    "Shadow Step": "7OeCPWLGtPieEOxx",
    "Shadow Strike": "u07a2ZXQlokyBClQ",
    "Shadow's Wrath": "UALQWbDzmp6H8Uiq",
    "Sharpen The Blade": "fWurALtwA2SByaXb",
    "Shatterpoint": "V5fEHh7NEGB6h0ei",
    "Shocking Affinity": "w2fcITzwIWxmBuLs",
    "Signature Maneuver": "DfcV6ep6pokDQmlk",
    "Silver Tongue": "VX0o502nLafrWzbA",
    "Slayer's Counter": "21o2m4T6nKInTyiI",
    "Slayer's Pride": "r2ZOqWzZzhkUmSoV",
    "Slippery Mind": "SfWAWVfaCZJChcx2",
    "Slow Fall": "TH8uVHJVECGYQeO1",
    "Sneak Attack": "DOR6WSQLFSFTURno",
    "Sovereign Protector": "dLfWtRWtN2DVPXtT",
    "Spinning Flourish": "IfkarBD3hTnNQJ14",
    "Spirit Blade Assault": "yMSvK9SmLoLI29p2",
    "Stalker's Dodge": "neI83QoBohA6gEqz",
    "Stalker's Fury": "0vKdMFsjX0vU9vaw",
    "Stand Against The Tide": "j9tueB66NHAi9XRK",
    "Stay In Formation": "PWRce8jzPuXlGfPE",
    "Stillness Of Mind": "71u1CPfFOBP2UZgi",
    "Straight Through": "DVBWZvttZhH2ZECU",
    "Stroke Of Luck": "jjkfkR3y4ZzLvhRc",
    "Stunning Strike": "YO47dPo3A0QCh006",
    "Subtle Control": "cGv4yOyQ5ZPihigt",
    "Subtle Presence": "pWu7ql7UFckNjgmK",
    "Suit Reliability": "VCwqg2o0ePLxL0s3",
    "Superior Hunter's Defense": "LLSeCmTx42FanV5K",
    "Supernatural Defense": "fDrprD1zPyK36J4Q",
    "Supreme Awareness": "x1TSm5F0CtGuX7u4",
    "Supreme Healing": "ow8lboCU7nSy3dyd",
    "Supreme Sneak": "6bY5UEP9vMlJjmvA",
    "Survivor": "mUQpy94CIAOkbxC1",
    "Tactical Mastery": "quoqL3EKsr7gMDCP",
    "Tactician's Instinct": "ROdICoWR82v6A2Rf",
    "Targeting Matrix": "vxR8oI3jyjVUt5sJ",
    "Tech Mastery": "f1XeMafaqejD02MW",
    "Techcasting (Engineer)": "2cPRZiAJPegsDJEt",
    "Techcasting (Fighter: Shield)": "qNNFQgODkmI77xfE",
    "Techcasting (Scout)": "F4I387qfbiqbeaOO",
    "Tell Me The Odds": "vABtgK0Jau0b6cTl",
    "Terentatek's Instinct": "Hg8zYh1iXL0DGUVq",
    "The Way Of The Mynock": "GqrLoLcbeHSTnGaD",
    "The Way Of The Rancor": "D3B5ASfcxCsFbpj1",
    "The Way Of They Krayt Dragon": "HgO4Lo3fbWIRyhlp",
    "Thief's Reflexes": "0QBWeM5Z0iSgUShC",
    "Thunderous Momentum": "1oiBleXKcbvKHz4e",
    "Timeless Vessel": "ZoEt4JpvUya3an75",
    "Tool Expertise": "B2qE4c6O2D4uhKjl",
    "Tracker's Instinct": "Cid5ujSdnooH0vMm",
    "Trick Shooter": "lLNBqCC6iexP68We",
    "Twin Saber Throw": "6VhggjCLnsuOPBiO",
    "Unarmored Defense (Berserker)": "1P7kIHNyx9mc8CX0",
    "Unarmored Defense (Monk)": "ESaIFP1ov25wZCMi",
    "Unarmored Defense": "IDt6duVrBzL8euRc",
    "Unarmored Movement": "zzbwoqUNCb6U0lRK",
    "Uncanny Dodge": "szBvqoou8yziMCmN",
    "Unerring Accuracy": "xsN7QCSQmiloh5oF",
    "Unlimited Power": "s0Bf6Sv2exQNH7vK",
    "Unstable Volley": "aT3vCPrH46ei2O6v",
    "Unstoppable Force": "Uysua3MJxqqdHu0i",
    "Varactyl's Instinct": "sfEr8ZBFVddlfLeF",
    "Versatile Direction": "ZuL4WCeoY7TvBdZx",
    "Vigilant Sentinel": "jCEl3lIz7FBJMAMa",
    "Voltaic Slash": "iFg9kA5mtj22OgKf",
    "War Chant": "UYWFpXz6HKecYIC2",

    # EC
    "Aberrant Resilience": "8GhHyN7gwQWVQZNN",
    "Aberrant Self": "fkw2xa0qoE9CkFDy",
    "Adaptable Applications": "B2yy36IjZoHpIgt0",
    "Adaptive Fighting": "1TSgLZzmLQooG1nX",
    "Adaptive Techie": "m1wUOAShOy5PFr5Q",
    "Additional Maneuvers (Scholar: Chef)": "58xYGURGvkKad7it",
    "Additional Maneuvers (Scholar: Explorer)": "w7Hb4Rru8t27O2uL",
    "Additional Maneuvers (Scholar: Geneticist)": "Fgf59MnnITFoccIZ",
    "Additional Maneuvers (Scholar: Slicer)": "2orm91vcgAPZOZHE",
    "Additional Maneuvers (Scholar: Zoologist)": "J4Fm8fhsVnEE6BVK",
    "Adrenaline Rush": "d9GIIame3PCH16jj",
    "Ammunition Upgrades": "ZbwvEeTXEPwoApqc",
    "Archaic Diagnostics": "j4hLztoaiHnwzbMc",
    "Armored Brute": "VRZeRYIBfLzZwlCw",
    "Artful Dancer": "KP18jV9KrOFrjfAo",
    "Assassinate": "1cbhX1bPuP09q5Rp",
    "Assuming Direct Control": "G9NlcRAQ2yP8Dkmc",
    "Back Blast": "xyLkSZxNcvNJ2Wxm",
    "Backup Plans": "w9G3JY7dSOaXJIAh",
    "Balanced Diet": "hVX363yaqEKE2VhY",
    "Battlefront": "j2mJ1wVjN04WYs8c",
    "Beast Companion (Scholar: Zoologist)": "9L18fSxRtMWu0c5E",
    "Beast Companion (Sentinel: Witchcraft)": "Sa2j1pJb7C7ur1YI",
    "Beast Companion": "SDh3G0VxVlI8wPLh",
    "Beastwarden": "rIVFUzh21M87bRkp",
    "Biochemist's Touch": "K9OJoAsCEOp31gkH",
    "Bladestorm": "EfJ4aU0mNUVGYHbd",
    "Blessing Of The Tree Of Light": "TeEN1l7snHIuHxn6",
    "Bombard": "YWsDFY7hQEabL8PH",
    "Bonus Proficiencies (Consular: Tutelage)": "n2T7oiP0MfoQ0Sds",
    "Bonus Proficiencies (Engineer: Artificer)": "8Pf5riC9RKGwLk7L",
    "Bonus Proficiencies (Engineer: Astrotech)": "sDqQ6apF5bfbS6GS",
    "Bonus Proficiencies (Engineer: Audiotech)": "YFrVQpPzar30Wpgx",
    "Bonus Proficiencies (Engineer: Biochem)": "9X6YtmYcL3tHOoGL",
    "Bonus Proficiencies (Engineer: Biotech)": "JvAFnMZezc5jTUz6",
    "Bonus Proficiencies (Engineer: Cybertech)": "PGd9fFv1SpyvJXdq",
    "Bonus Proficiencies (Fighter: Demolitions)": "Gk13kprJhzXYmwAM",
    "Bonus Proficiencies (Fighter: Mounted)": "P44Rcdvtp5HH7DgM",
    "Bonus Proficiencies (Fighter: Praetorian)": "S5I4RdNHNMm7ao0X",
    "Bonus Proficiencies (Fighter: Totem)": "GBG4HGrj9mP6LGu7",
    "Bonus Proficiencies (Guardian: Juyo/vapaad)": "MDW5aHJQ7jr8qf84",  # TODO: Fix caps
    "Bonus Proficiencies (Guardian: Sokan)": "wm5BdvpgkfRziN7Q",
    "Bonus Proficiencies (Guardian: Vonil/ishu)": "ODDIoJe6dsXI0Fzl",  # TODO: Fix caps
    "Bonus Proficiencies (Guardian: Ysannanite)": "diDFFE9tEqoibD43",
    "Bonus Proficiencies (Operative: Lethality)": "wgwQXhnekGSa9kt3",
    "Bonus Proficiencies (Operative: Saboteur)": "ia9lgfaaek84rjIc",
    "Bonus Proficiencies (Scholar: Archaeologist)": "SatF0UL3wd2y7udQ",
    "Bonus Proficiencies (Scout: Artillerist)": "33W0D0BvrvQpk5kw",
    "Bonus Proficiencies (Scout: Predator)": "fll4aLidhhf9Ihvg",
    "Bonus Proficiencies (Sentinel: Witchcraft)": "pwueAEbCrrWYKDFy",
    "Born To The Saddle": "iaedYkfIIcYQCCOZ",
    "Boundless Vitality": "KXDSrYHAZQZcglVz",
    "Bumbling Technique": "3OqwFmlRSb2bklnK",
    "Cause And Effect": "U07y3DHxu9EddHoC",
    "Channel The Force (Ataru)": "h4qwVuxZNtdOiH75",
    "Channel The Force (Jar'kai)": "MtBq5A0JoE67MU3l",
    "Channel The Force (Juyo/vapaad)": "nM3c4otxIdL30PoV",  # TODO: Fix caps
    "Channel The Force (Shii-cho)": "I7MvCDQ8E7E81U9j",
    "Channel The Force (Sokan)": "iEBfiKgSzaepLBZO",
    "Channel The Force (Trakata)": "kb7C9eq9tnRGKw98",
    "Channel The Force (Vonil/ishu)": "6xJyPg0dy64TKDGQ",  # TODO: Fix caps
    "Channel The Force (Ysannanite)": "im5At63Kt4o7Ea2B",
    "Charged Illusions": "tOo3ExbyW5uQdHJk",
    "Chimeric Adaption": "AAIu6uSn4bW00mHp",
    "Clarity Of Vision": "s9N0SbnOiNitLT5W",
    "Clinch Strike": "0FaZl14DvyIdfyIx",
    "Clumsy Sway": "CX7c2sq6wfgEYhpV",
    "Combat Contrivances": "WBTcdgZAjskgfJ9Y",
    "Comfort Food": "OqdAc34c0Db1huf7",
    "Comic Frenzy": "WtSaGz0yfKeuVPZQ",
    "Concussive Blast": "ZAGjuz5DZXFXIRjn",
    "Conflux": "havX5d7ZZfqzntdn",
    "Coordinated Attack": "hGvWvw1M1Gf6OvQv",
    "Corsair Weapons": "Hr4a2dhMPKm4sbU7",
    "Cover To Cover": "AxPXE2XkPSDhElLW",
    "Creature Comprehension": "4h4YWb2g2Svtwz85",
    "Crisis Management": "4X59Gjodqz87nMsa",
    "Culinary Knowledge": "mMnPYQB0HIHd5tQu",
    "Curved Throw": "FouRyvPDgamUwzuh",
    "Cybertech Contraptions": "FUZ9odAGALk33wGh",
    "Dance Of Death": "yQ3P80xIfnf999Hg",
    "Darkness Charges": "s3zxpmEoABHG6fJN",
    "Dazzling Steps": "pPKLvM4RC2l1oLQi",
    "Death Strike": "gLqYREO8Q8p6DPRT",
    "Debilitating Barrage": "A3adZpDPMyLDiqqj",
    "Debilitating Strike": "8m0voKhTkgLeitkp",
    "Deceptive Strike": "7cDCGTD6Zi8u9u8C",
    "Dervish": "sMap3pJ2eaRKjLhs",
    "Discoveries (Archaeologist)": "squXPxLSakcrSOBA",
    "Discoveries (Chef)": "1XEpeh0EPWD74pBp",
    "Discoveries (Explorer)": "xdWQ4OuCVA0ZPS3U",
    "Discoveries (Geneticist)": "3NOg28znKOJczSZi",
    "Discoveries (Slicer)": "sTy1MsBoX23ucs5S",
    "Discoveries (Zoologist)": "deJ8sUHUVQaOsVBM",
    "Disorienting Kinetics": "YQjndSMMsWAJSeMy",
    "Disruptive Resonance": "CwGDUo8eoohFesJx",
    "Disruptive Shock": "wAKt9PO3BZLziVzj",
    "Dosage Control": "NHLCKgLZAe3MP0dT",
    "Double Swing": "rkooXE8vPLT1zs0j",
    "Double Tap (Operative: Scrapper)": "t55c7OyiSdmENJIM",
    "Double Up": "K3RcWiIghOqlEkaI",
    "Droid Companion": "3wNWE9KjkFD76PuW",
    "Droid Defense": "jKYj9wLY1UMLTvYG",
    "Dual Wielder": "28peWa7ad8J7FIF7",
    "Duplicitous Force": "3paFYzEDFl0XWuO8",
    "Dynamic Attachment": "wfigLmIQg03vIbxP",
    "Elegant Maneuver": "iR6lT9P7fEJmv7j9",
    "Emergency Planning": "6Y9hwUuoPL64JXCv",
    "Emergency Supplies": "nJptqQFdwgm0KG76",
    "Empowered Connection": "L0cbGVkfx8S6vWW3",
    "Enduring Focus": "KXwYzrlSl36gvwxM",
    "Energized Kinetics": "WMnnRU6adjSwGio4",
    "Enforcer": "ktNY0EzlYaTBkNs1",
    "Enhanced Shot": "YnM0Nxhfsvkr01Vh",
    "Epicenter": "wR9uAGEnSdKoVvYo",
    "Ethereal Vision": "7cMRK9MsjCVJGzcE",
    "Event Cascade": "JE61hlD3B3IIfcLo",
    "Ever-ready Shot": "gnRErzmAIMcmICTM",
    "Exploit Weakness": "BZmfefaWp7Qi2sVz",
    "Explosive Charge": "uXm28JTQwru6y0tj",
    "Explosive Resilience": "gYcsvSxo8CDpcCEK",
    "Extort Truth": "TqPqxo9tACj5943r",
    "Eye Of The Storm": "4xxqmHwlwgyQjfrT",
    "Feral Ferocity": "iyNPFk7HtqHlPsgR",
    "Ferocious Charger": "jXtDOdvSBQHnodmF",
    "Field Advantage": "kDILnXslDQTvng3W",
    "Fighting Spirit": "QoSoggniLQlVPh3D",
    "Final Countdown": "CnVQJRpnRpsY0OFA",
    "Fists Of Fury": "ryOcrJD1zMIca1s6",
    "Flexible Body": "fcIW8kGypXVaSBwM",
    "Fling People": "mY6mOTYRUXAGEfaE",
    "Flow-walking": "4da8QNAWRrgGCkt3",
    "Flurry Of Light": "Pxp7SMeemsCJWgp8",
    "Focused Augmentation": "gm0iK2pPXSGQbJx4",
    "Focused Breathing": "RYV1XXoeZ4GjBpkq",
    "Focused Navigator": "A4hDRsUlTRQxFwq4",
    "Focused Superiority": "047L6iPjOrgNEZ5L",
    "Force Barrier": "1R0GS5nES0BAShSX",
    "Force Carving": "F39XcNVEfV9FHhuq",
    "Force Circuitry": "0aSYHfDlpqooV0b2",
    "Force Deflection": "sUs6idlxKXYU4ba6",
    "Force Resistance": "uAE6iG36liBaddaO",
    "Force Resonance": "qFyuZ0kIXxJoacCW",
    "Force Visions": "kabmw1OtBRVbkeIK",
    "Force-empowered Detonators": "0mVbi9yePHoAjUaD",
    "Force-empowered Kinesis": "yRBX77FduzyjhnaX",
    "Force-empowered Tech": "riPd6LYH9XCBUPbI",
    "Forcecasting (Aing-tii)": "PIdBeZMK89IPNC78",
    "Forcecasting (Fighter: Adept)": "hAfAtfT6c40rpSoE",
    "Forcecasting (Monk: Aing-tii)": "Bk4IMdLkT2sP8JJG",
    "Forcecasting (Scholar: Archaeologist)": "qUiOXv1Kv6r9W7Md",
    "Forcecasting Secrets (Engineer: Artificer)": "JSIXdNE2Tlipguvv",
    "Forcecasting Secrets (Scout: Inquisitor)": "WZa0WPiWbWOVscPT",
    "Forcecasting Secrets": "IGcZhZ4P27qH3rU5",
    "Form Basics (Ataru)": "7u4ivAWUJpqE9096",
    "Form Basics (Jar'kai)": "6QEvSr6jJjATZguf",
    "Form Basics (Juyo/vapaad)": "DxPXLhKth1RoxabZ",  # TODO: Fix caps
    "Form Basics (Shii-cho)": "HNSfcrOoizwfHN4U",
    "Form Basics (Sokan)": "9Rj0q3Pannh6qLnH",
    "Form Basics (Trakata)": "PSiGWs9DVviM78K3",
    "Form Basics (Vonil/ishu)": "vd1BMUHvQoWbo2j6",  # TODO: Fix caps
    "Form Basics (Ysannanite)": "fobWSSCWmjZ6Fjg9",
    "Freedom Through Slavery": "nT6AfpQXSZ4IeChO",
    "Frenzy": "b3uHUpwxSYCU0iLM",
    "Fuel The Rampage": "xzRNHB2M2HdOZzr7",
    "Fundamentals Of Mechu-deru": "XbKJYpFuGAllR1Ih",
    "Furious Throw": "eVSjRR9ibtm6kDfT",
    "Fury": "rg7zEbgvpGalvpQC",
    "General Practice": "OZImqRmAk5aeBX2o",
    "Genesplicer's Methods": "SDBNDY8CTCA0W0pq",
    "Geneticist's Resilience": "ZZIIY5ZE7nGrwWHV",
    "Got Your Back": "f11Wex2VzoorFTfN",
    "Growing Momentum": "CVjLxp8kGxZCNrS8",
    "Guardian Spirit": "rcdavmTFmTdnKHww",
    "Guarding Weapon": "Rmny9eQ9fR6sINL4",
    "Guided Strikes": "R5H3i6PfQEzdXyz9",
    "Hawk-bat Swoop": "J9dmq1HlKuOXtSo6",
    "Heroes's Feast": "YfR2xFy4SDFa31MN",
    "Hold The Line": "OB1x8g1MwGm2HA26",
    "Holographic Decoy": "4hfinmcJC9pqVDhD",
    "Hostiles Negotiations": "0k66wdRfVf8bxEd5",
    "Human Shield": "RShVKT9JGm5zHXU3",
    "Humanoid Companion (Consular: Tutelage)": "hnH0YDjXRbWGgsDY",
    "Humanoid Companion (Guardian: Vonil/ishu)": "qVV2qok1jL1xDZZi",  # TODO: Fix caps
    "Humanoid Companion": "x41qlxJPclXaeCkH",
    "Hunting Party": "AiDxbNfTgy2yiznn",
    "Imposter": "AIPQfRUQTdR3unU6",
    "Improved Decoys": "v1GPZX7JZ4lh2Bhy",
    "Improved Force-empowered Shots": "V2395mykGG37TJr7",
    "Improved Force-empowered Tech": "bfmpE9LUMpZ4l2ax",
    "Industrious Tech": "KaTv7hNRXKx0m8Fo",
    "Inquisitor's Wrath": "3g7tveozmCHAkd5R",
    "Instant Acceleration": "CXdc4zrwfnZVGnAK",
    "Instinctive Combat": "hWXqMs5J6dTyyKKx",
    "Intercept": "7kDUPPzg3zbMm02U",
    "Interconnectedness": "mYAWcD7bouvWCW5d",
    "Intimidating Presence": "oSSRYaeVsdcZQ5KW",
    "Invasive Presence": "zztRtikqjZ4bFjV0",
    "Ion Pulse": "D1da9OmAYYMq59gg",
    "Ionized Weave": "Qdbzi0NO5FVsmFXd",
    "Iridescent Strikes": "5Fh5O4hQO1zEfI4B",
    "Isolate": "Bk7Jrs3QNtMChqPa",
    "Kinetic Bastion": "vh8gpSCT41sZMONL",
    "Kinetic Bulwark": "F2rWFG8dQ3ftwCZ7",
    "Kinetic Ward": "ZM7V1WpNbiY9XbzE",
    "Kiss The Wall": "0SvWfvOHIppxi5FP",
    "Knowledge Is Power": "inwAnLXgAASMAyUA",
    "Legendary Coda": "Kmzg1HQwVzvwiVqP",
    "Lethal Strikes": "FunIeNcKviL8ilS8",
    "Life Eternal": "ze0ZnVMlv6x0IpS4",
    "Luck Of The Fool": "qrAYa9BeKBamaauT",
    "Maniacal Rage": "eXjxkCg9Iqs5KekN",
    "Manipulate Life Force": "ne50wp4wQ8CIDccd",
    "Mark Of The Artillerist": "BoUKWKXObZsOR6If",
    "Mark Of The Deadeye": "ptnCEo5giZPvVded",
    "Mark Of The Illusionist": "MqxXP3oYCwIaiFKE",
    "Mark Of The Inquisitor": "GcmkGFhQ0c8EWBc3",
    "Mark Of The Meticulous": "gsw3asysi2xekW3l",
    "Mark Of The Predator": "s7L1KzijyPgWkRng",
    "Mark Of The Teleporter": "CJuUHZlFy4eF40B5",
    "Master Duelist": "xkGpjUxmL8wQYEW9",
    "Master Of Aggression": "Aic1hLLhk3cIH4QI",
    "Master Of Dance": "pqpMDla2xTiLKmQz",
    "Master Of Deception": "1QqM6EmrNj4Mvcjw",
    "Master Of Determination": "cQ6XePAjRAw2Zm0c",
    "Master Of Domination": "Im0RXSNpKTuOE42u",
    "Master Of Ferocity": "21IcHCEbQXjzQ8kr",
    "Master Of Persistence": "PSsCniigbIjrk6EX",
    "Master Of The Unorthodox": "fJOMvX0p6D3Uklrr",
    "Master Of Unity": "HmfdajaZCOjIwtQQ",
    "Masterful Mixtures": "XZkExfmmCLzuAxjz",
    "Mercurial Mind": "1J5AObombhRl1GuB",
    "Mighty Blast": "rtq7PyIfmJQ0lGX9",
    "Mighty Leap": "EG0jeAxDE6oyzQez",
    "Mindless Rage": "ra5ZfIpyUpOuRd3A",
    "Modified Biochemist's Pack": "acOlNws5mitLSSuE",
    "Modified Instrument": "Nz8stfh2Fy7b9hq5",
    "Modified Lightsaber": "1f9cw6pS3RiiF8DZ",
    "Modified Self": "tZiE3SNBeoRftTYD",
    "More Machine Than Man": "SpinvKUCtlRLkJ8C",
    "Mutagenic Analysis": "y6sNfiGJFAddwfcb",
    "Mutagenic Transformation": "RU8Tb8fY6GOfyhIb",
    "My Ally Is The Force": "KKcNBEZD1ypeV1cl",
    "Mystical Connection": "hBggwD5K1VNpqBRW",
    "Mystical Erudition": "r3JUIhug7HSPicod",
    "Nature's Vigor": "zbCDtd1DzA3bhJwV",
    "Neck Snap": "qgHRPomaepStE22s",
    "Nimble Step": "OACrI8TxI9AYZ3v0",
    "Now I Am The Master": "pPyeqnE1GnMeG1og",
    "On The Hunt": "QiK8clUuVuTqq9YB",
    "One With Darkness": "mL3FpyONz4Ota9J8",
    "One With The Force (Monk: Whills)": "8d2b9T3Zxw49RGmR",
    "One With The Force": "WzpooBDyQYg1uFcT",
    "Opportunist": "VmtA5IyhcBM7UDxe",
    "Out Of Touch": "3wmpa2PloRYvU2na",
    "Overclock Body": "hCb9yeW3WppnYUA3",
    "Overwatch": "M2bObVPZABsSjW3H",
    "Overwhelming Cleave": "sbYfAu9t8TUNR5hp",
    "Painkiller": "56rZNAyhWtZrxiWp",
    "Panache": "JyXrmho5GP3SHYpB",
    "Pass The Blade": "LAXaRKVfudFryUkp",
    "Perfected Purposing": "SIrtFoj8ngOsd37n",
    "Personal Teleporter": "nQap8Befe2Snu9JE",
    "Phasestorm": "o8xQO9rBLDUXqoq3",
    "Poisoner": "WpVq5WXzlDOAQxKu",
    "Potent Amplitude": "NrSFm2gkpzm3tMeD",
    "Potent Integration": "2N5w1alVvT1VcSau",
    "Potent Mixtures": "eDuhGAzyp5GtSQ1h",
    "Potent Programming": "1aM4u82TO5GRRKhl",
    "Potent Techcasting": "n1nSwzit7F7yg7dh",
    "Power Surge": "Iv5MsHSDXerTQQ89",
    "Powered Ambush": "Xs7cWfBnM2YbgDro",
    "Powerful Mind": "KsUKtTRpay1eibt9",
    "Predator's Resolve": "bxplvoz7hgvle27O",
    "Preternatural Counter": "7TppyPEkrnorRw70",
    "Prey On The Weak": "i5kHSWxRLzlIOhsP",
    "Primal Avatar": "V0x1tf4l58GW5VVd",
    "Prismatic Step": "D57C2zBfdLIZCe7s",
    "Protector": "zb4QnZTseq74tpHT",
    "Psychometric Analysis": "yDmXVFAILTKe2ET5",
    "Quantum Entanglement": "E67Bd24TAx1TYKOn",
    "Quick Escape": "yTnJWJlddkvLIiOG",
    "Quick-release Stimulant": "vztjE89CZfhFYbOl",
    "Raging Bulwark": "Q3DHegz5ZbV7rA7m",
    "Raging Whirlwind": "3lqydI4v73szourv",
    "Rakish Audacity": "2MW5NKHVg2sLjPne",
    "Rapid Strike": "Fw5ULAWvA3jJIghs",
    "Reckless Strikes": "QW2GcMjunyXuGZXe",
    "Redirect Error": "sZbz4ionDvaecDde",
    "Redirected Shot": "Ob4SKH2kAglyDbkk",
    "Reflective Shield": "GnOt6LNfEOoKjLl7",
    "Release The Beast": "GbJDWzoTKWL7sEpR",
    "Relentless Assault (Berserker: Juggernaut)": "pq8vFXNw4RsrMQd2",
    "Relentless Assault (Monk: Kyuzo)": "CT1EKxMq7XkNmKDB",
    "Relentless Assault": "hwww57Bl4DAqvd5q",
    "Reprisal": "WxaVGJlPlo1kCQ4w",
    "Repulsing Wave": "kVQncmFiwUOVc14J",
    "Residual Warp": "pzqCxV7BEjZ6UN1h",
    "Resilient Fighting": "byZ3LtPPfMXxiVNI",
    "Resilient Retainer": "3AZcaWJypiKyjbDo",
    "Resonating Recovery": "O8As6HltmtDQV1SE",
    "Retaliation Strike": "M30wW5NGiow6RlDH",
    "Retaliation": "0NxbCrcn4Ty81wWf",
    "Returning Attacks": "nal6YefqnoMzxubD",
    "Rising Whirlwind": "rwlSmbnx9YtbWOI8",
    "Saber Storm": "20qc66rPhmC7wXDm",
    "Sabotage": "hfJ9bRUFa6D2oKle",
    "Sapping Storm": "hPn1UOSEPn94LbGV",
    "Sarlaac Sweep": "c3xsQBfsxcbhhGRw",
    "Scattering Stance": "o3GycrtP08UoO2s0",
    "Scavenger's Reach": "I7nWhcvXvcnaVk0r",
    "Seeing Sound": "3jqPPd5qJBBnonPw",
    "Self-sustain": "IBxXS7o4VV3znf5i",
    "Sense Force": "0gfyFmgoOlnrAEkc",
    "Shattering Strikes": "W7rRMa4gTsSc0VIq",
    "Shielded Thoughts": "pn1DjMFXPNTfFIME",
    "Shoot First": "74fME4fE9ljQozFI",
    "Size Matters Not": "YND5s9bZK1Fp05dX",
    "Skilled Grappler": "MZWGENUJx8b2PETJ",
    "Sleight Of Foot": "kqAjfLAtsOo8xdrX",
    "Slythmonger Savvy": "efOA0nrvUqKJOOeP",
    "Smooth Rhythm": "FWa4glBf9vs5iW3Z",
    "Special Ammunition": "uVj65irpjyXXnU6M",
    "Spirit Guide": "4lbz6IOCT4Ls6lgC",
    "Staggering Stratagem": "DuckPKni4u8oONVl",
    "Stop Hitting Eachother": "pNxTO7UhVKYIbDkz",
    "Stormcaller": "5v2aXZyPOFOSUuAV",
    "Strength Before Death": "WayeFkeZ0UZogQXl",
    "Strength Flows From The Force": "XXcUvD6i0qHESHIH",
    "Studied Shooter": "cuge2tnNcZL0TKkO",
    "Superior Droid Defense": "oYss1VOh4MUYVx09",
    "Survey Master": "ZcaltXfSW00wZfRn",
    "Surveyed Area": "sB7WR4Mow93lkPYh",
    "Swift Surgery": "2r0D2PHtMsms77Mk",
    "Symbiot Spirit": "1uSK1vNVR9ZlWeBa",
    "Synthetic Understanding": "s0tgfPdqVbfeTu8X",
    "System Override": "ws4yTZAFTaHvuYht",
    "Systems Hijack": "eB11052O9iV8tFYK",
    "Teamwork": "Xjqp6SkY1VZZINmp",
    "Techcasting (Berserker: Industrial)": "yYfFFOgfllndNqWr",
    "Techcasting (Operative: Saboteur)": "QMnzEKetcEbpg8pZ",
    "Techcasting (Scholar: Slicer)": "N6Z5ICg4rsix6OnA",
    "Techcasting Secrets (Consular: Technology)": "Lcp1bCLqq990O7UN",
    "Techcasting Secrets (Sentinel: Synthesis)": "0HwMR1NLvJV7vuRC",
    "Techcasting Secrets": "7I2mlmAOF7bzSAId",
    "The Force Is With You": "SBBlwVaJDwCADC5f",
    "The Force Unleashed": "dLHFgesahAtfy7SH",
    "The Way Of The Acklay": "LikGN9l3CnK2HMpZ",
    "The Way Of The Hawk-bat": "0oPBXA3TimKUKez3",
    "The Way Of The Hydra": "EmiCBDAZDJcTTBfb",
    "The Way Of The Monkey-lizard": "RS5OG9YXnbEwkFqO",
    "The Way Of The Sarlaac": "SsvfSQlHuA3UiyIU",
    "The Way Of The Varactyl": "2nd8f6jyBtaKRMJq",
    "The Way Of The Vornskr": "5G5BbnJq7kguaZAD",
    "The Way Of The Yerdua": "WLkMLz9u8Hdy1Bt5",
    "Throw Anything": "96o60BuVGiClsZuE",
    "Tireless Spirit": "RhtkuvE1lcDsocvR",
    "Tornado": "D2dpEvNZhLDsArYf",
    "Totem Creation": "zdQodeYfWZauJ3Mv",
    "Totemic Might": "mBAKzGlZCTBHXE9K",
    "Tracker Droid Companion": "YdwjtKxTKAL8WBQl",
    "Turret Companion": "6dNqHrdwSTmPLbu8",
    "Tutaminis Mastery": "iiae3ARlngOX8BvF",
    "Twisting Winds": "Z7Ku1V9dXCInJ6eK",
    "Unarmored Defense (Fighter: Blademaster)": "y4La6YmQxB9QOoQQ",
    "Unhindered Charge": "1VKKJFetDqCF5GfT",
    "Unpredictable Motion": "XblRy31agdu3pY8p",
    "Unrelenting Resilience": "iYeeOLaQtoosQjZ1",
    "Unstoppable Adventurer": "0jBmCBoW623YCBK3",
    "Unstoppable Force (Berserker: Juggernaut)": "H00QpZIVvyleKRdW",
    "Unstoppable Force (Fighter: Adept)": "FmMAwvAS1CYxbJoQ",
    "Unwavering Mark": "7f0fHaZm1rAQrPqj",
    "Unwavering Self": "1zsB6yknq4JxRzNR",
    "Upheld By The Force": "RC7hvuuU3CIRZUOd",
    "Upper Hand": "A01Ne3M1XizO3m49",
    "Vengeance": "z5s3mctvvQbG2Yh4",
    "Vicious Hunting": "A4W8o8JAm3ghEdnq",
    "Vigilant Defender": "u7MxfRLGGRYAy04z",
    "Visions Of The Past": "APoyxRAifvAM5Y6O",
    "Volatile Reflexes": "WU5tBnC8EgUZV5xj",
    "Warding Maneuver": "HohmusWCWzTc00cS",
    "Whirling Weapons": "UNoJQm1l6ho9QEHR",
    "Whirlwind Attack": "prxRkZuc0ZzVhJxt",
    "Wild Power": "q2CS3xB1EIG0E7Jt",
    "Wilderness Expert": "aGA8MRFycUwVLNFa",
    "You Have That Power Too": "Cx9JxWK5jOf19IUQ"
}
