feats_Ids = {
    # PHB
    "Ace Pilot": "8rcm51F8jpbNXWs3",
    "Acrobat": "Qv2nJWPLJ2klIEbQ",
    "Actor": "FF1sNY6xNbDsAnh1",
    "Alert": "K7DJqRZNotfWGZMK",
    "Animal Handler": "VxSLc899DPLmuepp",
    "Athlete": "E1VLUKO9e7wb4mHm",
    "Battle Scarred": "HMtPma2N0myiF2il",
    "Blade Specialist": "YrUXpp1j01lHSmxG",
    "Bountiful Luck": "fz4xeG1EtHJNBHQy",
    "Brawny": "T4oYkzdxQmcbHG6G",
    "Casting Specialist": "YhvSSzW56SuR7Kja",
    "Charmer": "Of8IhnbIiID6sUt4",
    "Crafter": "vxDwtMysjVevQ9RN",
    "Crushing Weapon Specialist": "qW28id0DXW7FjT6V",
    "Dungeon Delver": "odprUVlMYRnJ4OOJ",
    "Durable": "WtF8rN7cxIc3D86D",
    "Empathic": "1DSm47d3mNU1rgya",
    "Entertainer": "m5FKO0ltZGdxtadH",
    "Fanatic": "ckcrU1ZRdKmq4hQY",
    "Feigned Confidence": "RDN5JNfiKs59xcGt",
    "Fighting Master": "W15mnFHa0xq3tXL1",
    "Fighting Stylist": "HG3tsJyWM7X7fVIv",
    "Force Guidance": "ai5BTh0VA5FpLVtu",
    "Force Of Personality": "NMzjgUDUPBVVJJdP",
    "Force-Sensitive": "dSjQBf5jwukcGDfY",
    "Forceful Vigor": "LzF6ijAkhkIkiZdJ",
    "Galvanizing Presence": "D02rvwCBbp6mIwlH",
    "Haggler": "y09iFQHd9gACYeKn",
    "Healer": "UUaYVEXcwbVHv2sr",
    "Heavily Armored": "cHFXtjcgWLkCTAea",
    "Heavy Weapon Specialist": "5YRWESEfVwbZC2Y6",
    "Inspiring Leader": "gQDk0fGDlFDVl9Uj",
    "Investigator": "BaXJ9OO3GUF33Plg",
    "Keen Mind": "E89ZF9cltOGagy6F",
    "Lightly Armored": "EEMJ3UEwesgxC78X",
    "Linguist": "aYMhiCMRBwH1WomL",
    "Loremaster": "tzePc2J19K2YB4Mt",
    "Lucky": "4DuaFCbiBxqL9eL3",
    "Medic": "fohQLLoe5AnkvvaC",
    "Mobile": "sC2RPRGuIXbzP4Vc",
    "Moderately Armored": "Xqo6KzAFPtLdW9YS",
    "Naturalist": "YJOdr43nmsPXAxp3",
    "Observant": "32xXZ9VyqvvuqX2O",
    "Perceptive": "Gg5CP1rrrqslUvtd",
    "Performer": "JoDZj9iDHOq1K0L8",
    "Polearm Specialist": "a4Id4dk3ov3dYw7X",
    "Power Adept": "BGgoW3Cwxj28VTwz",
    "Practiced": "Gm5pE7iTE74ITJlK",
    "Promising Commander": "WaO9gKAZN43oQrsA",
    "Quick-Fingered": "GlrABR30jRsQnhfg",
    "Quick-Witted": "uYSCaHw1CtA3VJEY",
    "Resilient": "lWHtIoW012u1QQ53",
    "Rifle Specialist": "7WSolr5mmDrV654v",
    "Sidearm Specialist": "VUliXV0a3Owu4yuI",
    "Silver-Tongued": "A3iKF2QaiLp57Kct",
    "Snappy Interjection": "ozWdapIWplYGXv7g",
    "Specialist": "BjWUsjBQzq4w1Q3s",
    "Stealthy": "zp1d7mtK3QWMZX6j",
    "Supreme Accuracy": "9Tv2HgQeSEnALiup",
    "Survivalist": "10KjUfHaOKAiOw6T",
    "Tech Dabbler": "QLLXt6fQiqI1Va2l",
    "Techie": "KmOP744KaU2bOsX2",
    "Threatening": "aujuUebb7f4e6ht8",
    "Tough": "iEFbSjp7DaDSo8Az",
    "Trip Weapon Specialist": "dYGd07LLEJu5RKzH",
    "Weapon Expert": "iiZ66oT6lIqkrOGk",

    # WH
    "Augmented Cyborg": "E8mrRhc4BQEgapcA",
    "Climber": "p22Fu1TzzQ0zG6KI",
    "Customized Droid": "jjAqimaLDJ9GoSSL",
    "Mariner": "J5eAWVCNYRZPsJzq",
    "Prone Combatant": "tc0x7wRpNsW1O2Zz",
    "Savage Shorty": "XuhxzosKJIBWpWHU",
    "Shard Modification": "ua8SMi9eB45JvLvn",
    "Tiny Terror": "q7ahgoAYWA5ghy81",

    # EC
    "Adaptive Training": "XRtb4NmElyRsERrk",
    "Blinding Agility": "vesMmgkOBAQLvIEU",
    "Close Quarters Caster": "VSXqyHXrw1kI3X91",
    "Combat Caster": "dAmUh0ASLU1xshOs",
    "Cunning Intellect": "eqBlqioFPauxq798",
    "Dual Focused Caster": "h9fsZnfh6RP9PiZv",
    "Exalted Awareness": "ccsjgZgwSyw3r0on",
    "Expert Potency": "k316FEnj9NARisTU",
    "Focused Vitality": "YfISDL99fjJ9WYy3",
    "Kinetic Stoicism": "yOhhoeyIfccOM1JQ",
    "Martial Adept": "1ZAghZJQflkZUVuG",
    "Meditative Mindfulness": "cnf7zry702QLzotX",
    "Mounted Caster": "kbN0CSXPaTs3mfan",
    "Overwhelming Presence": "dWfbvXKx0ZDEEY4w",
    "Precision Applications": "4svS5qc5vl445fsU",
    "Quick Caster": "dQzURN2q97jG47Qo",
    "Relentless Pursuer": "p9p9uvgtw0as7ecU",
    "Serene Resolve": "W8VTyuB1D1pa4s4N",
    "Sniping Caster": "3tOeQ7XLC7omOmIc",
    "Tireless Outrider": "ig8TPZw7mt3jQqbi",
    "Titan'S Power": "tVElcveiEV69LpMD",
    "Unnatural Resilience": "T0pMXR5lUepOZWAu",
    "Versatile Design": "drXPCTuKznN8IXBN",
    "War Caster": "l16JW8IL3N6NSivU"
}
