techpowers_Ids = {
    # PHB
    "Absorb Energy": "c17MNNJ8FplU5Txm",
    "Acid Dart": "dmjZqZfUdHSfp0L1",
    "Acid Splash": "gOVe5Qv8Bwkn9gAf",
    "Acid Wind": "KSWB4H5niRz0MjpQ",
    "Acidic Strike": "50NdsRKVmM3FMPH0",
    "Alarm": "ZH0jkLKHJ54BmkYX",
    "Analyze": "PBFbcYIh4DK2EOdq",
    "Antipathy/Sympathy": "8591z42KNanjfP0p",
    "Assess The Situation": "xAgbr9pfUcwf2FjB",
    "Autonomous Servant": "LKTlPR7noRV7VzLN",
    "Bacta Pack": "iG4M6N5PFqj9TfRW",
    "Ballistic Shield": "JixOzwaRnsdf1zKP",
    "Bestow Virus": "NCsr3aIyYdHsjmhe",
    "Buffer": "USt5H36LIw7ma5gh",
    "Cage": "a4nZ05eHgTXZo4TU",
    "Capacity Boost": "fDkDt47dU5nPlvcy",
    "Carbon Fog": "iIB2uiS4UZM0Ylvf",
    "Carbonite Explosion": "YMMEHilPkH2NTrFI",
    "Carbonite": "6iIYMjmyWE2wqgzf",
    "Cloaking Screen": "3SB9A7cFFRezxu8Q",
    "Combustive Shot": "to84bBMy9F4zYZ5I",
    "Concealed Caltrops": "JAKN9PXNLmCSL3Ag",
    "Condense/Vaporize": "Zk697eWSqME5gpkF",
    "Contingency": "8iAgtDKUbONDnAjN",
    "Copy": "7khirDTQvs7rtLbW",
    "Corrosive Sphere": "WOnLRapxYnS99uFT",
    "Countermeasures": "5cvgy3gaZJ0wVt9R",
    "Cryogenic Blast": "SFwBxNBEuVHbgxXi",
    "Cryogenic Burst": "PxJ4AbgjLgZJmXX7",
    "Cryogenic Spray": "NBfknzmSaSJMH89w",
    "Cryogenic Storm": "Nxt6KaBjs9rMal12",
    "Cryogenic Suspension": "ORazBSaHWGmGE8xs",
    "Cryogenic Volley": "AANtnm5ZkutF0eMt",
    "Cryogenic Wave": "MNt1yDoEKf8eytDZ",
    "Darkvision": "NTJFd2LsJJJjXjgv",
    "Debilitating Gas": "TpJV9QdBqbnL7aLQ",
    "Decryption Program": "5jYdyvYl4yY7BwbX",
    "Defibrillate": "73W8rKPEbN60y7L2",
    "Delayed Explosion": "w8aWJGuIPq2kp4Qj",
    "Destroy Tech": "PBnC5HGwf5K0j8nK",
    "Detect Enhancement": "3xMy4RLHPoRmZGjz",
    "Detect Invisibility": "yBnreezRaiZpukCB",
    "Detect Traps": "i60B1Lyu97U0VNCI",
    "Diminish Tech": "g0WJVphRgr0iSG1x",
    "Disintegrate": "F4Q7jJ2ssAKfNHw0",
    "Disintegrate": "F4Q7jJ2ssAKfNHw0",
    "Disperse Energy": "px6DKRGAVjyTh638",
    "Echo Blast": "V0gdMfr4o2iV2AOb",
    "Echo Blast": "V0gdMfr4o2iV2AOb",
    "Electrical Burst": "dDOMCEIMHUrrdvho",
    "Electromesh": "QIbRAvOjWgTFkX7r",
    "Electroshock": "UACmTGjhcYjQyLj3",
    "Electroshock": "UACmTGjhcYjQyLj3",
    "Element Of Surprise": "Rygvn8mB2NySWQ2s",
    "Elemental Accelerant": "7Twjeo1X2oUP9IZo",
    "Encrypted Message": "Jp3f51H4VaRiMLvb",
    "Energetic Burst": "cCxSroyB5NOBFgBe",
    "Energizing Aura": "VPpaedIPR048RLKF",
    "Energy Shield": "c7vvcY0lZDii7SOI",
    "Enhance Droid": "YP3RHcb3X5tj6tIS",
    "Enhance Weapon": "ZgRhvuUTEgv2aZ03",
    "Execute Command": "SCXAO2y6feVJJum3",
    "Expeditious Retreat": "50ViBtuEBJ70CUA1",
    "Explosion": "NWjxsCnJIzNxIUzH",
    "Extinguish": "8tB0qzRHPpaJKOJc",
    "Fabricate Trap": "1IaNYJjpFj6tGXpD",
    "Find The Path": "FsF2hPZPp4Vuo1BD",
    "Firestorm": "3xsY1jAc9qw4t308",
    "Flame Sweep": "6aZ0FG6HwrUO28WF",
    "Flaming Shots": "M2G8hb5ubWzC2ofU",
    "Flash": "lehdnXpBfIxK3c11",
    "Frequency Scan": "cSol0QcQ8XaCtAPU",
    "Friendly Fire": "ILn7Jzn6BVcDnS9i",
    "Gleaming Outline": "zBQIDrnkr3L6URgG",
    "Glide": "tOQpsE1NUokmiUtF",
    "Greater Analyze": "xeBPmKsGTsXqEszc",
    "Greater Explosion": "YzYlv2tK8mS5BS6Z",
    "Greater Hologram": "j9etZuLOpJpFO1Hx",
    "Greater Light": "j3x2v1GJBVVZwwBb",
    "Greater Sabotage Charges": "cBi1Qb9wV9V6eIlb",
    "Greater Salvo": "YD32do4QEG5WATCG",
    "Greater Translation Program": "pMZsusj9lqkzUxlB",
    "Greater Translocate": "yMhKf3Nge4wkvMrB",
    "Group Hologram": "mYhTI7UHdM6MKIM1",
    "Haywire": "0kjpOmlXlauqnZf2",
    "Hold Droid": "qHu258wCccbyajwo",
    "Holding Cell": "PJxftyDxgenF6aj2",
    "Hologram": "9BkVQndzFGxtralV",
    "Holographic Disguise": "mFW2RREnUTmbXX4C",
    "Homing Rockets": "HTozWic37W9iKQSD",
    "Illusory Strike": "XLcIk8WOOrtowBdv",
    "Illusory Terrain": "M4Y5qtO7lMrQbOhG",
    "Immolate": "fc1XTRTpr4FjyCSw",
    "Implant Message": "J5b5g5ZNNUcAZhJz",
    "Incendiary Cloud": "SE3mktWuG9wEE6R5",
    "Infiltrate": "Fb1sIhs7d6YWnF1J",
    "Invisibility To Cameras": "hyh01gHWyf5MVpdm",
    "Invulnerability": "Il5IT5Y2FcEXO59O",
    "Ion Blast": "DjrO5bCUnUHA71jA",
    "Ionic Bond": "53NK4D990c4WsZa5",
    "Ionic Strike": "kWABLhflNvLZbrU3",
    "Jet Of Flame": "HoshRCTHW8vntDCg",
    "Kolto Cloud": "vo6OJqBxuOiyMyxX",
    "Kolto Dispenser": "OqaQ4z628LjBYqnq",
    "Kolto Infusion": "xxrRddwkMSsJbPs0",
    "Kolto Pack": "KQXx0PfcNGX8uuIj",
    "Kolto Reserve": "OkLzEeGi9Gna7dOy",
    "Kolto Waves": "KQklmwaTncQHCZQ0",
    "Light": "q15Watfzi4E5yzUm",
    "Lock": "QKVor2AGtFgrOjox",
    "Magnetic Field": "cOazeFQn9Atja7Wd",
    "Magnetic Hold": "F9vT2fmmbLjQJcWv",
    "Mass Repair Droid": "SZHMFvx9mkPSwUli",
    "Mending": "Aa2O05OQeMjizQXq",
    "Minor Defibrillation": "uLB7E27wecdLLbCE",
    "Minor Hologram": "nKB4KH7zUo3Q1BQh",
    "Mirror Image": "Iw1Hx4qsVyB1ewVR",
    "Mislead": "YjW6V6Qc5XFpC6mG",
    "Mobile Lights": "xW2LoI7JTHMqPcuC",
    "Motivator Boost": "o9i0rEKiH5YLiVzj",
    "Neurotoxin": "0p4YthIRvLrxE1qx",
    "Oil Slick": "bp55Q4R0gBpd0FiM",
    "On/Off": "E6OviwnCfEjRTx3X",
    "Overheat": "JZnbV9hvp3DZ2x49",
    "Overload": "1zfQEQMJqirKT6tR",
    "Override Interface": "NagD6z90jRyd7zOk",
    "Paralyze Creature": "XkEm103IydE75jWD",
    "Paralyze Humanoid": "zXCnz8vBWC4fhvfw",
    "Pheromone Burst": "ef7RW6hQ93EeDCVb",
    "Poison Dart": "d2hRQpNWYK6JxnCu",
    "Poison Spray": "98p1OVwAvz2sbes5",
    "Predictive Ai": "0L0UcVhV3azFXFTm",
    "Preparedness": "wtSlQwtA4N2ewADb",
    "Pressure Crush": "UNgPNWRmkQUNpNny",
    "Programmed Illusion": "OtebMdVF2sD3y23n",
    "Project Hologram": "Cghjrf6rxNrmP1vq",
    "Protection From Energy": "3L7XVAEHR87CYNzH",
    "Pyrotechnics": "5yJQ10UhYzm0bCcy",
    "Radiation": "uKVIsflQoqXlbejy",
    "Read Memory": "Qv9sVYqBifg44aEZ",
    "Reboot": "SDGi4dYAvqZtkMRD",
    "Release": "RCV218zYuFFEyWUY",
    "Remove Virus": "rHq8p2F0XR0H4rMT",
    "Repair Droid": "jBUTIsaIV0l0iFfR",
    "Reprogram Droid": "Nvftn7xKgbvyP7rT",
    "Rewrite Memory": "nHhp6mchLrFTFMoi",
    "Rime Shot": "i6VsaYG9PEr8NP1I",
    "Rime Strike": "95KxKlOqUOkpnotl",
    "Ring Of Fire": "i0Z07joWf3xkBk8C",
    "Sabotage Charges": "YfSDSxySy8ZdOyDB",
    "Salvo": "cWpl0AM6R0DkEbzM",
    "Scan Area": "ZFGBrIjKVhzOE7O0",
    "Scramble Interface": "6oJ07fhBJLXJ7zv1",
    "Scrambling Barrier": "ANUI2G1QqL6Bxs5h",
    "Scrambling Field": "QXBHocnHw8ErKZSK",
    "Security Protocols": "GqlEFPr0SNjeNnXY",
    "Sending": "fdxHYa82RznE46mK",
    "Sensor Probe": "P8cWLNsHqe3OVGO7",
    "Shared Shielding": "c4SsNyGyxVhoTcT7",
    "Shatter": "d0FiFRm54YKcE0Zs",
    "Shocking Ray": "Rs9CicKafsOq5FCa",
    "Short Circuit": "dSH2Y7IKtXWFaE53",
    "Shutdown": "MQnk1dyfbYgXh2Ns",
    "Skill Protocol": "YkRvH2zbzT6CWdpM",
    "Slow-Release Medpac": "MBWJM5CWFyMJSHAY",
    "Smoke Cloud": "K5f18kJ5V2eMqLH7",
    "Smuggle": "d8xd9jPHRHF0WEgv",
    "Sonic Fists": "qIi1DYpjY8198ACL",
    "Sonic Shot": "PmUEhPIaIf8Zva37",
    "Sonic Strike": "aJqCpoejohXYuJ1J",
    "Spectrum Bolt": "Z1iEHe9eYojoiXJ1",
    "Spectrum Ray": "C3E2vGaCO5ZsN55m",
    "Spot The Weakness": "dmMPMnnXdELmOHMI",
    "Stack The Deck": "b0T7rxNgDtGx3mwh",
    "Storming Shot": "7o2xvsn9AVML11ME",
    "Stun Dart": "suitG0utOY2LF7sC",
    "Superior Translation Program": "4s47Qk7bfWOdgDW4",
    "Synchronicity": "XERRPbogZO8ePUxp",
    "Tactical Advantage": "4koE44WAkEHVTwET",
    "Tactical Barrier": "RzBnmCbTfv3atGv3",
    "Tactical Superiority": "P1V3IyTuobCwDV4u",
    "Target Lock": "tAR395yRyPA5bWw3",
    "Targeting Shot": "1yKxIAEkqLdo8DDy",
    "Tech Override": "9Vg5TEwWdVh3NVym",
    "Temporary Boost": "T9yaDZKiKSX8zFud",
    "Tonal Translocate": "o1iXuIwO1nQohMDU",
    "Toxic Cloud": "NKts41q32pX1bJ9O",
    "Toxin Purge": "Xn8F3DKTsC7GD00Q",
    "Toxin Scan": "gu0quvGXQMeqePqd",
    "Tracer Bolt": "PUxPBzpy9TcUbVvh",
    "Tracker Droid Interface": "PopHJSVZq9t1FFf5",
    "Tranquilizer": "PrQodh2dn2Q7jJz7",
    "Translation Program": "i1fB3zDVdoeIc7KB",
    "Translocate": "CdQSEvQtfFsxMiCn",
    "Truth Serum": "DXdtjkn0Zg8JP8YT",
    "Venomous Strike": "xs0igvxRAzGwZqik",
    "Vertical Maneuvering": "7uegZ2qAzqRiE1no",
    "Voltaic Shielding": "zmMsZQr1lwEzLrFB",
    "Vortex Shot": "jWQweA9GtEI825aa",
    "Ward": "tM8bhPs9ehJjv11n",
    "Warding Shot": "N6ohW2LtSCM976xi",
    "Wire Bind": "SOpkOaf7xzF1UTYG",
    "Wire Line": "xXPplfLNPoXvhfjp"
}
