species_Ids = {
    # PHB
    "Bith": "Z3DZq97ItDtrcVLa",
    "Bothan": "yO0y0R00KH6kprMX",
    "Cathar": "XwRWgvFPbrQXjMha",
    "Cerean": "iWfbgl42D7ogk1Hc",
    "Chiss": "cRqoLZOEd6813W08",
    "Devaronian": "y9JI1QTRHlvbWDwB",
    "Droid, Class I": "05Qnk7HLSTjoGyr2",
    "Droid, Class Ii": "jJbuBlZaAMdqDXcT",
    "Droid, Class Iii": "6dUPGIldzOLY7WA8",
    "Droid, Class Iv": "VAD3Pi9aFD88GbVL",
    "Droid, Class V": "bHNVgsazMaG6xhwn",
    "Duros": "GExUpA4NmRaxS8Gm",
    "Ewok": "AUXWviDOa1PWlgq4",
    "Gamorrean": "2BNSCGmptb5qjY3a",
    "Gungan": "93AxC8HrUSpclwzY",
    "Human": "4Tv04yssJ5sMngne",
    "Ithorian": "yUyuGaX7LClJqmwl",
    "Jawa": "l6kJ5abjFcZtwGSK",
    "Kel Dor": "1PvtK2y2eATLf8et",
    "Mon Calamari": "97bNdvsykO011CBK",
    "Nautolan": "Hn49Nhj4Rk4rf1oX",
    "Rodian": "C4nEg4sz7WoOOLm3",
    "Sith Pureblood": "4AqE2ekCPh6jAOCe",
    "Togruta": "qS5HklGyCBanHFyI",
    "Trandoshan": "2Vo8yHWlGIHj8hau",
    "Tusken": "v19hw62cqU3qCYUO",
    "Twi'Lek": "zQoxcJ5iQXQozMgm",
    "Weequay": "mRTpYQFJkZtF0fXy",
    "Wookiee": "2OAuMEI1zxPGdeOy",
    "Zabrak": "FixqnQKxrYLnNyo2"
}
