adventuringgear_Ids = {
    # PHB
    "Antitoxkit": "c1fsl0zNO2jbQDjy",
    "Aquatic Rebreather": "d508bDYXnIHgIRYL",
    "Backpack": "QloC8FAAaq8wJFgf",
    "Bandfill": "CTKBssCmPYPIjOBP",
    "Bandolier": "xQQs7o1UkKcIcftB",
    "Basic Poison": "DjhVaMp7y9kv8huC",
    "Biochemist's Kit": "5Hm6nv1vS3fYq8rp",
    "Bipod": "y4BGQwOX4ZifcFtA",
    "Breaching Charge": "g1Xig6pkFygVTs01",
    "Chef's Kit": "pHOnHawoE6CLWNey",
    "Chest": "Np1QPOCE9EMfTTTY",
    "Chindinkalu Horn": "gr4iELayxqZtxg7q",
    "Code Cylinder": "5uYoOu7FyOQ4O7BZ",
    "Comm Jammer": "fGHNS8jAO97FoOj4",
    "Commlink": "KNtbo1StdsDm135s",
    "Crate": "kuCbaQRvtvExVI6D",
    "Dart": "S5MMoZO0A8FiGFIo",
    "Datacard": "EUATVxP9x6mPT8x6",
    "Datacron": "IN4aom0cLi0kmpsD",
    "Datapad": "At8RCEDvMZ94O6QC",
    "Demolitions Kit": "oH2HgXxSM0EFnj7A",
    "Disguise Kit": "fSb6sQtBYBvrKfon",
    "Drum": "A8KyyUNLReS4nJ9W",
    "Emergency Battery": "Z0YM3aYCyCRhL6cx",
    "Enviro-suit": "hf7WTDBfO8zCt2HQ",
    "Fanfar": "hQsuUhExnWS9qpCO",
    "Fizzz": "o6IpY0vJ9aGvgBQ8",
    "Flight Suit": "T9zF8WmPgy1NJBUr",
    "Flute": "0rXtxM4H9wfh4NnA",
    "Forgery Kit": "uoNaJRSb7ocwldUu",
    "Friction-grip Gear": "8sX023Ca4gIn1gbU",
    "Grenade, Electrostun": "RTr0nZ7oGStuqH8d",
    "Grenade, Fragmentation": "pp05gqbvmncpHgV3",
    "Grenade, Gas": "nrSoJ33rycJm1tYJ",
    "Grenade, Ion": "272qKqEN2znXm9Ye",
    "Headcomm": "zHERdLuCUPpxzaSJ",
    "Holocomm": "4SzhraHgsIKXoDu3",
    "Holocron, Jedi": "eWWgW7KKG7T9xPQi",
    "Holocron, Sith": "nEqd3Yt653yCbHed",
    "Holorecorder": "n8VDbaI6MzaxWSkO",
    "Holotrace Device": "kaV6ehRv2KaHOj5n",
    "Jetpack": "vuxf6Qbd5pMj2gCH",
    "Kloo Horn": "txKO9MDEwindPjME",
    "Lute": "HDCRyHCl9BoJU8dj",
    "Mandoviol": "IkEwux444DkKp4QJ",
    "Mechanic's Kit": "kxtdNQ3crFH9UCuw",
    "Medpac": "Ipew2cMqiiKVSAgW",
    "Mine, Plasma": "zrSOUA8dUg9lHVdS",
    "Missile, Fragementation": "Ojkrl5msPVueqyXm",
    "Ommni Box": "I7meEgjaaG2fzHtX",
    "Pocket Scrambler": "J13oK71qmUiWYym8",
    "Poisoner's Kit": "zaLzNlsfzRf71Xpl",
    "Pouch": "ms32a7hpt43RJUeV",
    "Power Cell": "VUkO1T2aYMuUcBZM",
    "Projector Canister, Carbonite": "gH8V1Lvp60X2b2FT",
    "Projector Canister, Flame": "QKzanDFaJdhqdY0r",
    "Remote Detonator": "Sbe5QkH8xd9jU9AY",
    "Repair Kit": "HOQqmAhZvaKBPoXM",
    "Respirator": "EDuNz0jxDB750uB1",
    "Rocket Boots": "x2SznYftRVTKCXAa",
    "Security Kit": "usVyAnJZ5vf3kWf6",
    "Shawm": "wS3DLDX5AIMLhJ84",
    "Slicer's Kit": "16V3E2zNGzP77JdU",
    "Slitherhorn": "lPG1Di7j4RzvmdMG",
    "Slug Cartridge": "u4xaL0xLRJobIj30",
    "Stealth Field Generator": "Exm15q29p3U8Gg33",
    "Stylus Pen": "8DAKXuUkVeZBF36X",
    "Thermal Detonator": "qiLWpJa33pythE4J",
    "Tracker Utility Vest": "4F4ppZsYeYU1N8mH",
    "Trauma Kit": "xuU4A9rszdWjOh2A",
    "Traz": "UQu4duMtxYEXKAbo",
    "Valahorn": "KTsNtB8A1CWKPW0G",
    "Wristpad": "mGiqI759C7te33Jw",
    "Xantha": "2pZY5Dw63wPkopPz",

    # WH
    "Andris": "l12esNtvPBB7LoWF",
    "Camtono": "A6aTeaijnzz3I4xQ",
    "Cilona": "qPSOnaMx7dd5Ynzf",
    "Giggledust": "J1KpCMSHmimri4iW",
    "Glitterstim": "uUjV9Ay7TxLOtXVw",
    "Holster": "59Jkji0FuhY9CnkW",
    "Hovercart": "csq3Gy4uUjMMjGMo",
    "Karrak": "GHtBwdTRCHIpi8sz",
    "Muon Gold": "RWrBkt91CAYqzCmX",
    "Power Belt": "dArOs86s3KFujI3A",
    "Propulsion Pack": "XR1obpDj1PqDLfA8",
    "Repulsor Pack": "Ao4Ab7SAkw10TAZq",
    "Shock Gloves": "NRE6RgiMJlZwmo4y",
    "Shoulder Cannon": "m1xOrZbVJXy9jrQg",
    "Smugglepack": "Zlj5z56A4oVQ5iEC",
    "Yaladai": "NfFT6edC8csXH2l3",
    "Yarrock": "uSzMnQlBpw5rhDcF"
}
