adventuringGear_IDs = {
	# PHB
	"Flute": "0rXtxM4H9wfh4NnA",
	"Slicer's Kit": "16V3E2zNGzP77JdU",
	"Grenade, Ion": "272qKqEN2znXm9Ye",
	"Xantha": "2pZY5Dw63wPkopPz",
	"Tracker utility vest": "4F4ppZsYeYU1N8mH",
	"Holocomm": "4SzhraHgsIKXoDu3",
	"Biochemist's Kit": "5Hm6nv1vS3fYq8rp",
	"Code Cylinder": "5uYoOu7FyOQ4O7BZ",
	"Stylus Pen": "8DAKXuUkVeZBF36X",
	"Friction-grip gear": "8sX023Ca4gIn1gbU",
	"Drum": "A8KyyUNLReS4nJ9W",
	"Datapad": "At8RCEDvMZ94O6QC",
	"Bandfill": "CTKBssCmPYPIjOBP",
	"Basic Poison": "DjhVaMp7y9kv8huC",
	"Respirator": "EDuNz0jxDB750uB1",
	"Datacard": "EUATVxP9x6mPT8x6",
	"Stealth field generator": "Exm15q29p3U8Gg33",
	"Lute": "HDCRyHCl9BoJU8dj",
	"Repair Kit": "HOQqmAhZvaKBPoXM",
	"Ommni Box": "I7meEgjaaG2fzHtX",
	"Datacron": "IN4aom0cLi0kmpsD",
	"Mandoviol": "IkEwux444DkKp4QJ",
	"Medpac": "Ipew2cMqiiKVSAgW",
	"Pocket Scrambler": "J13oK71qmUiWYym8",
	"Commlink": "KNtbo1StdsDm135s",
	"Valahorn": "KTsNtB8A1CWKPW0G",
	"Chest": "Np1QPOCE9EMfTTTY",
	"Missile, Fragementation": "Ojkrl5msPVueqyXm",
	"Projector Canister, Flame": "QKzanDFaJdhqdY0r",
	"Backpack": "QloC8FAAaq8wJFgf",
	"Grenade, Electrostun": "RTr0nZ7oGStuqH8d",
	"Dart": "S5MMoZO0A8FiGFIo",
	"Remote detonator": "Sbe5QkH8xd9jU9AY",
	"Flight Suit": "T9zF8WmPgy1NJBUr",
	"Traz": "UQu4duMtxYEXKAbo",
	"Power Cell": "VUkO1T2aYMuUcBZM",
	"Emergency Battery": "Z0YM3aYCyCRhL6cx",
	"Antitoxkit": "c1fsl0zNO2jbQDjy",
	"Aquatic Rebreather": "d508bDYXnIHgIRYL",
	"Holocron, Jedi": "eWWgW7KKG7T9xPQi",
	"Comm Jammer": "fGHNS8jAO97FoOj4",
	"Disguise Kit": "fSb6sQtBYBvrKfon",
	"Breaching Charge": "g1Xig6pkFygVTs01",
	"Projector Canister, Carbonite": "gH8V1Lvp60X2b2FT",
	"Chindinkalu horn": "gr4iELayxqZtxg7q",
	"Fanfar": "hQsuUhExnWS9qpCO",
	"Enviro-suit": "hf7WTDBfO8zCt2HQ",
	"Holotrace Device": "kaV6ehRv2KaHOj5n",
	"Crate": "kuCbaQRvtvExVI6D",
	"Mechanic's Kit": "kxtdNQ3crFH9UCuw",
	"Slitherhorn": "lPG1Di7j4RzvmdMG",
	"Wristpad": "mGiqI759C7te33Jw",
	"Pouch": "ms32a7hpt43RJUeV",
	"Holorecorder": "n8VDbaI6MzaxWSkO",
	"Holocron, Sith": "nEqd3Yt653yCbHed",
	"Grenade, Gas": "nrSoJ33rycJm1tYJ",
	"Fizzz": "o6IpY0vJ9aGvgBQ8",
	"Demolitions Kit": "oH2HgXxSM0EFnj7A",
	"Chef's Kit": "pHOnHawoE6CLWNey",
	"Grenade, Fragmentation": "pp05gqbvmncpHgV3",
	"Thermal Detonator": "qiLWpJa33pythE4J",
	"Kloo Horn": "txKO9MDEwindPjME",
	"Slug Cartridge": "u4xaL0xLRJobIj30",
	"Forgery Kit": "uoNaJRSb7ocwldUu",
	"Security Kit": "usVyAnJZ5vf3kWf6",
	"Jetpack": "vuxf6Qbd5pMj2gCH",
	"Shawm": "wS3DLDX5AIMLhJ84",
	"Rocket boots": "x2SznYftRVTKCXAa",
	"Bandolier": "xQQs7o1UkKcIcftB",
	"Trauma Kit": "xuU4A9rszdWjOh2A",
	"Bipod": "y4BGQwOX4ZifcFtA",
	"Headcomm": "zHERdLuCUPpxzaSJ",
	"Poisoner's Kit": "zaLzNlsfzRf71Xpl",
	"Mine, Plasma": "zrSOUA8dUg9lHVdS",

	# WH
	"Holster": "59Jkji0FuhY9CnkW",
	"Camtono": "A6aTeaijnzz3I4xQ",
	"Repulsor Pack": "Ao4Ab7SAkw10TAZq",
	"Karrak": "GHtBwdTRCHIpi8sz",
	"Giggledust": "J1KpCMSHmimri4iW",
	"Shock Gloves": "NRE6RgiMJlZwmo4y",
	"Yaladai": "NfFT6edC8csXH2l3",
	"Muon Gold": "RWrBkt91CAYqzCmX",
	"Propulsion pack": "XR1obpDj1PqDLfA8",
	"Smugglepack": "Zlj5z56A4oVQ5iEC",
	"Hovercart": "csq3Gy4uUjMMjGMo",
	"Power Belt": "dArOs86s3KFujI3A",
	"Andris": "l12esNtvPBB7LoWF",
	"Shoulder Cannon": "m1xOrZbVJXy9jrQg",
	"Cilona": "qPSOnaMx7dd5Ynzf",
	"Yarrock": "uSzMnQlBpw5rhDcF",
	"Glitterstim": "uUjV9Ay7TxLOtXVw"
}
