speciestraits_Ids = {
    # PHB
    "Aing-Tii: Ability Score Increase": "ykJQTCMd8hA6cJKb",
    "Aing-Tii: Age": "5rsP1wR5wmzKvZ0y",
    "Aing-Tii: Alignment": "lcXGZmbN4hPfU9vl",
    "Aing-Tii: Armored Plates": "KCfMMQXXxQPEGDEl",
    "Aing-Tii: Closed Mind": "cVmuyocVuUHauY55",
    "Aing-Tii: Force-Sensitive": "9wmqnuNHaUS1g5OA",
    "Aing-Tii: Languages": "Yk4d57W38W66ibVM",
    "Aing-Tii: Prehensile Tail": "EbCcH2U7B0lUqRI6",
    "Aing-Tii: Size": "12nZLY8HDhYKLqLF",
    "Aing-Tii: Speed": "JS2topEnWnrOiJGx",
    "Aing-Tii: Wisdom Of The Elders": "CKiJ3avUKmYMy72c",
    "Aleena: Ability Score Increase": "0Z6i5olaBdivyez9",
    "Aleena: Age": "KaulyR8lwPdEHUB3",
    "Aleena: Alignment": "v4Lor03KZz2dHIXG",
    "Aleena: Bite": "AWosW9HCck0dqoqQ",
    "Aleena: Cosmopolitan": "GjuteDdiyFEtBMQW",
    "Aleena: Languages": "nkKlpdiLXFQRDQmO",
    "Aleena: Nimble Escape": "dGRbJvFzHKcPna20",
    "Aleena: Nimbleness": "emc1dPKJWAPn0D6k",
    "Aleena: Racer’S Reflexes": "FcNz0rR5dh4TI7Wm",
    "Aleena: Size": "bcxqBVct7uMw26BW",
    "Aleena: Speed": "rlrwzPdZ5MfhrUye",
    "Aleena: Undersized": "I1bqxmWpaRdIcAx7",
    "Anzellan: Ability Score Increase": "nXzaofEi03lNCqJh",
    "Anzellan: Age": "i0gxBkhJESumVJMF",
    "Anzellan: Alignment": "8ISgBANWO0YHs0tg",
    "Anzellan: Crafters": "AmdrmseeogRsC4EZ",
    "Anzellan: Detail Oriented": "ZAWe2Z29WM3rVCKe",
    "Anzellan: Languages": "MUiHFVGZUd3N1ucu",
    "Anzellan: Pintsized": "xquxIkYmetrTTcci",
    "Anzellan: Puny": "AFRgq791r6mkDMeP",
    "Anzellan: Size": "7R7RW6H938bgON9m",
    "Anzellan: Small And Nimble": "VTHfbp4BAlH7Vy2r",
    "Anzellan: Speed": "NgjyMBh55Xlg5o9C",
    "Anzellan: Tanned": "nHzVDanVSDfCj1y0",
    "Anzellan: Technician": "nyFJvnhbdRSYqbQp",
    "Anzellan: Tinker": "36SG2aexQb6fuZLr",
    "Aqualish: Ability Score Increase": "rFHob6ASIQaPgIVt",
    "Aqualish: Age": "Wh2Y5qsaIyvuM3j1",
    "Aqualish: Aggressive": "b5u4esMUUSN0hLys",
    "Aqualish: Alignment": "i2CE6JByG9YuH6KP",
    "Aqualish: Arms Dealers": "75JKt34I1qnWSDgc",
    "Aqualish: Darkvision": "OAam0kP83q2kIs7o",
    "Aqualish: Languages": "cNp7sSb0rkUO43Ol",
    "Aqualish: Menacing": "1YDKv64RmhjnxUgC",
    "Aqualish: Size": "cjGJTivcBKHiENGV",
    "Aqualish: Speed": "W5h6dfR73qifRpr2",
    "Aqualish: Swim": "SCPCBZOs3yooOpqn",
    "Arcona: Ability Score Increase": "hKexm1xFmz7avF0u",
    "Arcona: Age": "JHCXiR6C3IkLjC8s",
    "Arcona: Alignment": "hNTvPYipKfW0uoVS",
    "Arcona: Claws": "OEj2LSUSzjHgyBuw",
    "Arcona: Clever": "LG3JXXG9vpFwkEHV",
    "Arcona: Easily Addicted": "JqO8hHNwU9poQxXd",
    "Arcona: Hide": "9juLTPwkH3alGzKg",
    "Arcona: Keen Smell": "mmkW91HSaIVuNXz4",
    "Arcona: Languages": "hB76VdcLgwB5dK9p",
    "Arcona: Reptilian Senses": "OBJOHaAmsKNhZGEv",
    "Arcona: Size": "pkoX0uPsJ2Yqa4sh",
    "Arcona: Speed": "98oECR8sNqN54BEo",
    "Ardennian: Ability Score Increase": "FB1Xa43pqsKNx9tV",
    "Ardennian: Age": "HrWdzEqzusLBsyVn",
    "Ardennian: Alignment": "lVuUunrUiVN0eeId",
    "Ardennian: Darkvision": "Ol86VJ75Z10bztuL",
    "Ardennian: Four-Armed": "WJgaZFk26vUddClM",
    "Ardennian: Jungle Dweller": "vn2QxEVvLlslSiAm",
    "Ardennian: Languages": "fvHN0IzPpcGBsTAf",
    "Ardennian: Mask Of The Wild": "lvOeH66QTQ3TVQvB",
    "Ardennian: Prehensile Feet": "3loVHY5Y5KxtB0DM",
    "Ardennian: Size": "ov2jtAFrTA8XvqRK",
    "Ardennian: Speed": "9PTd6UYh1Xjd4dgT",
    "Ardennian: Strong-Legged": "yZhe7jHwrFPUhpB2",
    "Ardennian: Treeclimber": "qSR44pdE8jctJbF2",
    "Arkanian: Ability Score Increase": "2aGkVI0OywZiYZRg",
    "Arkanian: Age": "L0hz6JyQyuVzEJx4",
    "Arkanian: Alignment": "2BazmeYmzdX0hHvQ",
    "Arkanian: Arkanian Brilliance": "Pl84rtd4gyLEvjuf",
    "Arkanian: Darkvision": "TTUMitk4Ied9V0Rg",
    "Arkanian: Honed Mind": "XAaSKcuDqpIUsqVR",
    "Arkanian: Infrared Sight": "CsaZx2cbXOIK7qLZ",
    "Arkanian: Languages": "91jKqxX64BWgasZD",
    "Arkanian: Size": "63kZWuimeJ62cEdA",
    "Arkanian: Speed": "ZlWTZkymL8OLuua0",
    "Arkanian: Sunlight Sensitivity": "czRfEQTp07z1REjT",
    "Balosar: Ability Score Increase": "ZuDDYz6pYw5bfzdh",
    "Balosar: Age": "jAfdvXUCUCiUjBwu",
    "Balosar: Alignment": "oIQb9Ytxyg6f7Bhj",
    "Balosar: Keen Hearing": "3NMiK78QGVIpMWcD",
    "Balosar: Languages": "PPKkAe8VVTiPNWHj",
    "Balosar: Size": "cnk5OZfufk1nIvgU",
    "Balosar: Snap Senses": "rG9X3Xt4EiffQ1sj",
    "Balosar: Speed": "O7lbxNVb7SYtQEdA",
    "Balosar: Spicer": "xggPcKaZlrvgfycY",
    "Balosar: Toxin Resistance": "8qUFsn4zRklE7hvc",
    "Barabel: Ability Score Increase": "g3zWQhDPhDZZuw17",
    "Barabel: Age": "hJnBk1Q23Vhykywi",
    "Barabel: Alignment": "dZWrPJK3HsniwDbO",
    "Barabel: Darkvision": "3FYqRK4kkljK8ZH4",
    "Barabel: Hide": "WnVhNSrTg7UqLcGR",
    "Barabel: Hunter": "4PZDcXIcPKtksFhU",
    "Barabel: Languages": "8vPlTaN6Dg3yj1gT",
    "Barabel: Prehensile Tail": "SWD6n0inCElCUJq2",
    "Barabel: Size": "5cEbHtULoLceFeYI",
    "Barabel: Speed": "Kt47PEOnL6TWT2Hg",
    "Barabel: Tooth And Nail": "pTqZUF11pKyAs49J",
    "Besalisk: Ability Score Increase": "bkKS8oP93gzrTvEp",
    "Besalisk: Age": "SXrDFhuWfkCRS0WU",
    "Besalisk: Alignment": "xFlOw1W11NlKpnfC",
    "Besalisk: Four-Armed": "86K7CcHDuvjXyaRK",
    "Besalisk: Languages": "lu7Mms7SiMrt3bxc",
    "Besalisk: Long-Limbed": "jmSprI7fgIfRDlk0",
    "Besalisk: Powerful Build": "VhAelxACpVohsiua",
    "Besalisk: Size": "rHeJJS6ZTkH3JtoG",
    "Besalisk: Speed": "YPf7ULbTxMYnO1uh",
    "Bith: Ability Score Increase": "t8gPp0MsdVlbSMH2",
    "Bith: Age": "LJ322DjqYSlWp6OU",
    "Bith: Alignment": "ETG8NpvhO97kAJMQ",
    "Bith: Detail Oriented": "owyUsCySalqp1qZt",
    "Bith: Keen Hearing And Smell": "KwQJpjZlrM7zOrB8",
    "Bith: Languages": "orRhnAWPTytzYvqO",
    "Bith: Musician": "qLzGhJRkdsGOwHKj",
    "Bith: Programmer": "Rs7p3X3QZesKwKw9",
    "Bith: Size": "kLUh7LwjjvGvpnxH",
    "Bith: Speed": "W5MEmDXI33eX45kc",
    "Bothan: Ability Score Increase": "mp4LgWxy7DMDqhAf",
    "Bothan: Age": "MRpzVaef53QArE2V",
    "Bothan: Alignment": "L003j5JLntr7U1FA",
    "Bothan: Languages": "ksDykFEtVcYWdUj6",
    "Bothan: Naturally Stealthy": "CL5XRHejnXvnf9SQ",
    "Bothan: Nimble Escape": "bhBKNqnPyVQzqVAy",
    "Bothan: Shrewd": "VwWup5RS6ygCgNB0",
    "Bothan: Size": "w29VlVDUNktokeh2",
    "Bothan: Speed": "eXikQhGAQVYt53B7",
    "Cathar: Ability Score Increase": "U5Rsx93WY9bOOoM6",
    "Cathar: Age": "LgtuJPzPfiF9H2Sp",
    "Cathar: Alignment": "3IDnlsErBj5hpDti",
    "Cathar: Cat’S Claws": "9PFEeo5HJuD5YEYS",
    "Cathar: Cat’S Talent": "IANAECpkOQq4ZESc",
    "Cathar: Darkvision": "iUfXFnfs6turAA39",
    "Cathar: Languages": "mmFX6YHVXEgnM9sl",
    "Cathar: Leonine Agility": "rwxDQ0Sli6794SiJ",
    "Cathar: Size": "Jq5Dak4KeKG6oQ0v",
    "Cathar: Speed": "jcR7iqutr64S44ny",
    "Cerean: Ability Score Increase": "hDerbpshNZAU24Rh",
    "Cerean: Age": "sfkmdABExRmcqs4T",
    "Cerean: Alignment": "q7V6VXGckPYAprrU",
    "Cerean: Closed Mind": "cEOH5jE1AHSShTlE",
    "Cerean: Intuitive Initiative": "Fg8k2A4vULcXGHBs",
    "Cerean: Languages": "IJXaLVNLV0u6G3ui",
    "Cerean: Perceptive": "Q99pLXPrQRYbC6Gc",
    "Cerean: Size": "pxgQwKEYoOpfCmBX",
    "Cerean: Speed": "UOtklihCAVl0oKAY",
    "Cerean: Strong-Legged": "ekDWgJouYAqZ9VvD",
    "Cerean: Trance": "sGDXPFIo482HkxhF",
    "Chadra-Fan: Ability Score Increase": "W0Wz7tLRsBBm3UW1",
    "Chadra-Fan: Age": "6JBqo7dUQKI4RjdG",
    "Chadra-Fan: Alignment": "PvGFcH1i7UEiQxtb",
    "Chadra-Fan: Climb": "CCN8Mr9fxpWs7kJU",
    "Chadra-Fan: Keen Hearing And Smell": "bBbcSzWZlHSniUVX",
    "Chadra-Fan: Languages": "YyedgGII1Nho2Z8E",
    "Chadra-Fan: Second Heart": "NejG12ObtlMbVSbm",
    "Chadra-Fan: Size": "Psq4mLRrOC5vSMsJ",
    "Chadra-Fan: Speed": "ULWpmsTT7jWtU82J",
    "Chadra-Fan: Tinker": "JU5qVeN691bmuLKT",
    "Chadra-Fan: Trance": "Zrvgz0e8M2G9OyhD",
    "Chadra-Fan: Undersized": "dVIEiaBz2JZiFHGY",
    "Chagrian: Ability Score Increase": "AX85oDCjpIDf6P9l",
    "Chagrian: Age": "KVZupIumhky9OnFV",
    "Chagrian: Alignment": "VguQjLJaV9gy37Ur",
    "Chagrian: Amphibious": "SjHmbxxoHxtjmg9J",
    "Chagrian: Darkvision": "6hGRcoChCK5itEIG",
    "Chagrian: Languages": "tI6Wn9EoSICN3Veq",
    "Chagrian: Natural Resistance": "XLtlIUnnTOdDHmTx",
    "Chagrian: Size": "1xeTQrV7Saemfytb",
    "Chagrian: Speed": "tbejLA14SoaTGhvJ",
    "Chagrian: Swim": "3O6BN5iifojrhfvn",
    "Chevin: Ability Score Increase": "e1qf9XBilzMQg07D",
    "Chevin: Age": "zXop73F6tXVcLZO9",
    "Chevin: Alignment": "n2jBrzx5AaJSSyY2",
    "Chevin: Hide": "jPfhPLbitmPDO0fd",
    "Chevin: Keen Hearing": "SwVc8YdpNUBcCYXA",
    "Chevin: Languages": "sbtZ4HZn42EMklca",
    "Chevin: Nomadic": "M457n7CzkRJpEOht",
    "Chevin: Size": "oMLeMOt4VEFSzVxy",
    "Chevin: Speed": "5D2aqfpX2G6SC9vf",
    "Chevin: Thick Skull": "no9ArSNhieiJ2Fl4",
    "Chironian: Ability Score Increase": "b9zYl6I8haYMAdqz",
    "Chironian: Age": "IIqfYd6372tfw6Ar",
    "Chironian: Alignment": "KAHh0ms0YPcHMDZM",
    "Chironian: Cultured": "obLTuoumXEtoGOIa",
    "Chironian: Equine Build": "evmPubJKoldEOYeS",
    "Chironian: Hooves And Horns": "5GzB4CKuf3zgBVxX",
    "Chironian: Languages": "Bu5yBUmXXIYbCidZ",
    "Chironian: Powerful Charge": "Q4WNWccPRa5pCk1j",
    "Chironian: Size": "CPzO4aUcMm42gBDO",
    "Chironian: Speed": "HLwfpYYf09LD8EQn",
    "Chiss: Ability Score Increase": "7UbgZ4qC69Q1pbAx",
    "Chiss: Age": "vvr5teJPtAiJjL28",
    "Chiss: Alignment": "KwOGPFMSmuJPsKsT",
    "Chiss: Darkvision": "8FmAR1r9yWawJDUO",
    "Chiss: Languages": "BHEO73MX4XMMrb5X",
    "Chiss: Martial Proficiency": "DMcSLiFMbWA9JLWW",
    "Chiss: Size": "a7oXmdm6iX3h04of",
    "Chiss: Speed": "VTRAs9YazIsbcyTy",
    "Chiss: Tech Resistance": "KNdwF7xscZWjoTcm",
    "Clawdite: Ability Score Increase": "bIdIih9pP0bPm7Ma",
    "Clawdite: Age": "oCQwBy0tAHib0EHu",
    "Clawdite: Alignment": "p7lv3JjBc1qn7Zrn",
    "Clawdite: Changeling Instincts": "MkFSIXvGsmLjfMRd",
    "Clawdite: Languages": "JDtYZnWrew14EdQs",
    "Clawdite: Shapechanger": "ZeRScynaBNU962kh",
    "Clawdite: Speed": "mfMkQFx5YsZYob5X",
    "Clawdite: Unsettling Visage": "CxTXpb0kvFgyBc3u",
    "Codru-Ji: Ability Score Increase": "RvGMAPAX2iPbZtv0",
    "Codru-Ji: Age": "ZnE6vqvfiqdXQTSq",
    "Codru-Ji: Alignment": "BZYngoxrciLGtR15",
    "Codru-Ji: Four-Armed": "NfLgaDXOzY7ZcavX",
    "Codru-Ji: Hide": "RHRd6wFO3vtDYjD8",
    "Codru-Ji: Keen Hearing": "EBDbgCjO6INZWLoH",
    "Codru-Ji: Languages": "z0qZUYyA69XRonfj",
    "Codru-Ji: Natural Grappler": "QtFQSIYe3KytoBxh",
    "Codru-Ji: Size": "Qtj9mV0JM9F7PSPr",
    "Codru-Ji: Speed": "xatajoatKM10U6Qp",
    "Codru-Ji: Trance": "cGiLYFKCWdwrRom1",
    "Colicoid: Ability Score Increase": "4Y4l430wBHFWfnLO",
    "Colicoid: Acute Senses": "EdnmjvNfdXyW01T3",
    "Colicoid: Age": "AN0H0EixmX8EXWxg",
    "Colicoid: Alignment": "Ix7tenuBQU3Z78Ap",
    "Colicoid: Cannibalize": "Jl05PryCPdCOyZy4",
    "Colicoid: Closed Mind": "D8Wvmic1Y4B2zJkZ",
    "Colicoid: Defensive Ball": "bomf2609hbaNvc6F",
    "Colicoid: Languages": "FNc95XUKHy0NCyW9",
    "Colicoid: Natural Armor": "AdSn2gG3sPTY5Jtb",
    "Colicoid: Size": "bxPkaabv5ZUHxhcc",
    "Colicoid: Speed": "yIrfVwXdY21JlyNI",
    "Colicoid: Stinger": "Qu1pV7lCzPQX1Ueq",
    "Dashade: Ability Score Increase": "miDlpzTNsFLhqjyq",
    "Dashade: Age": "EodkPVEXDlr5UIKE",
    "Dashade: Alignment": "ysJ5MllE3Zo8kDnA",
    "Dashade: Claws": "AQEjvFimGuJ22dhS",
    "Dashade: Force Contention": "Hi448NwxWfCpSgGp",
    "Dashade: Heat Dissipation": "rq5fQRah79HHNvVw",
    "Dashade: Languages": "u930sysOADgdia9p",
    "Dashade: Menacing": "6D98PqlYSxE9JcF8",
    "Dashade: Radiation Resistant": "O4j8ulc8IAb4jSer",
    "Dashade: Size": "u9l6WPKLLSeNjnic",
    "Dashade: Speed": "l4tajluT29dkxqw6",
    "Defel: Ability Score Increase": "Tpxf1sK4KRip4fOw",
    "Defel: Age": "heReraiT2cBncP6E",
    "Defel: Alignment": "EQ1aWrCXr581Am0R",
    "Defel: Claws": "AJNX9uTKnidJxRGf",
    "Defel: Darkvision": "fFen2N3lEw4YmoE1",
    "Defel: Hidden Step": "bFS45iaT1dktLXtJ",
    "Defel: Languages": "P1bePCNU0uv5pUjK",
    "Defel: Miners": "zoltmjpbxyiDx5e1",
    "Defel: Size": "4pFV5153nioRn9gP",
    "Defel: Sneaky": "LTL54KS7PW0U8arq",
    "Defel: Speed": "QzaNiVXFTwa8Q7mH",
    "Defel: Sunlight Sensitivity": "zJhhqfjjJbDfCrzz",
    "Defel: Surprise Attack": "kGTqj6HbxSUbNOS9",
    "Defel: Undersized": "Ll3aT01MKfAK7PsM",
    "Devaronian: Ability Score Increase": "9W8SSEsFqWhMgdZC",
    "Devaronian: Age": "79Ocp5yfVE5oPJyS",
    "Devaronian: Alignment": "OkdLltn6obeUh3pq",
    "Devaronian: Jungle Dweller": "bYuDHGNd6vC0wIDT",
    "Devaronian: Languages": "Jw82PctSkF1Fws0w",
    "Devaronian: Size": "bJXGRs1bQL6i3qM9",
    "Devaronian: Speed": "RE197mYw0ZRkfnCU",
    "Devaronian: Tech Resistance": "m8hTzHGz8Bt0fjCa",
    "Devaronian: Two Livered": "rhY2LLs73PuDyzC8",
    "Draethos: Ability Score Increase": "gXgwEeOTzlkRqJcS",
    "Draethos: Age": "8YkgaK6PFyr60C9g",
    "Draethos: Alignment": "gVS314Is1QihlQqM",
    "Draethos: Darkvision": "F3CYFnoiZ3mirCQK",
    "Draethos: Languages": "xs2n592TXBagtGFD",
    "Draethos: Size": "R2exSJFV4Ifyn3hU",
    "Draethos: Speed": "25SvVH1Wlz6EvOFu",
    "Draethos: Telepathy": "BkxroIaHRuXMllkm",
    "Draethos: Way Of The Warrior": "5FhB6qwt7nhCFfPi",
    "Droid, Class I: Ability Score Increase": "792Sr0pfyWgYesL7",
    "Droid, Class I: Age": "wWprekMv1k3hSG6g",
    "Droid, Class I: Alignment": "7tO8qkQdsfBoMCtZ",
    "Droid, Class I: Armor Integration": "rkc8FmVni5sX7chL",
    "Droid, Class I: Droid Resistances": "hBr0Pt99BuxOoBk8",
    "Droid, Class I: Droid Systems": "Fzi8gKuyZQID9bhh",
    "Droid, Class I: Droid Vulnerabilities": "ukaXSb37ehTfrezD",
    "Droid, Class I: Force Insensitive": "uW05mtzaSQCpdu55",
    "Droid, Class I: Knowledge Protocol": "7XqLfMmhQ6NDR7sp",
    "Droid, Class I: Maintenance Mode": "9waNGo5ltlvjhKde",
    "Droid, Class I: Size": "gngx1864PGvD1m6h",
    "Droid, Class I: Speed": "67mXzQcqJZbXQm23",
    "Droid, Class I: Type": "MJBnM10HZ35tvin3",
    "Droid, Class Ii: Ability Score Increase": "o2IidCYSlWICLBPb",
    "Droid, Class Ii: Age": "h0mxuXcJGwr1fQjI",
    "Droid, Class Ii: Alignment": "YpJFsNDxA30lOa0y",
    "Droid, Class Ii: Armor Integration": "Qrv6yfNtCBlUKif2",
    "Droid, Class Ii: Droid Resistances": "ZxinMxHfOtSrnBF2",
    "Droid, Class Ii: Droid Systems": "rYSrRzfy0JkMWE29",
    "Droid, Class Ii: Droid Vulnerabilities": "zmQitBDmsCovbEWu",
    "Droid, Class Ii: Force Insensitive": "GRkTWtzIUxL05Cox",
    "Droid, Class Ii: Integrated Engineering": "MP3gMQQXZQ4zZKvR",
    "Droid, Class Ii: Maintenance Mode": "6de0JPZpTGpL5NYA",
    "Droid, Class Ii: Rapid Reconstruction": "sa3WBlUEf8ninSlE",
    "Droid, Class Ii: Retractable Arms": "eXPfiDvtAWJkbA8H",
    "Droid, Class Ii: Size": "wvMh2Y8HJBqCftE2",
    "Droid, Class Ii: Skill Protocol": "2SMQwfDctN0DOrAN",
    "Droid, Class Ii: Speed": "b3d5d3XfU68MKsLp",
    "Droid, Class Ii: Type": "xLbkVbEENmIrhWWM",
    "Droid, Class Iii: Ability Score Increase": "HWVSMZCSezig32WP",
    "Droid, Class Iii: Age": "4HnKi4dmSmOeRLHv",
    "Droid, Class Iii: Alignment": "CDGlvpLB1Jl45ZxK",
    "Droid, Class Iii: Armor Integration": "iQsxOTxzHc9A839W",
    "Droid, Class Iii: Droid Resistances": "lUzy2bxWRHfBALLZ",
    "Droid, Class Iii: Droid Systems": "qoLeFKNQFUY6UIl2",
    "Droid, Class Iii: Droid Vulnerabilities": "dhifT2ODV726Vzrz",
    "Droid, Class Iii: Force Insensitive": "zT3664CLQaNjz3pE",
    "Droid, Class Iii: Knowledge Protocol": "NKHNC12CqBJ1AkLV",
    "Droid, Class Iii: Maintenance Mode": "tXlJWWWkt7ClQJV0",
    "Droid, Class Iii: Size": "BSeIVF3xSsgveY49",
    "Droid, Class Iii: Speed": "xIQFlK33sDREKF0y",
    "Droid, Class Iii: Type": "aIeqXMZfPLh26hlj",
    "Droid, Class Iv: Ability Score Increase": "vfImUTS8tyXU2Xr3",
    "Droid, Class Iv: Age": "SYlIheXZza50LA9x",
    "Droid, Class Iv: Alignment": "INyptgSlNOszqRta",
    "Droid, Class Iv: Armor Integration": "0MubAAnicaWRxhAc",
    "Droid, Class Iv: Droid Resistances": "H1qEVkQVdSced71G",
    "Droid, Class Iv: Droid Systems": "mYirez7bGq2SdDHQ",
    "Droid, Class Iv: Droid Vulnerabilities": "9H0ZkCoOk07m6e8L",
    "Droid, Class Iv: Force Insensitive": "NVJMiXTvjDCxfeU8",
    "Droid, Class Iv: Maintenance Mode": "QcZMirTnweNnfrcy",
    "Droid, Class Iv: Martial Protocol": "h2Z2ZQkOteDveMuk",
    "Droid, Class Iv: Size": "ZiazrACNGd4DmIkH",
    "Droid, Class Iv: Speed": "enIrAH6UNXd8aMJv",
    "Droid, Class Iv: Type": "0lqE8P4vehCNtqHF",
    "Droid, Class V: Ability Score Increase": "MLWVXP1vKTHwU3Zk",
    "Droid, Class V: Age": "AmJ4cHdAKLvSCPoT",
    "Droid, Class V: Alignment": "Q0cBLmgI3Op5qWLD",
    "Droid, Class V: Armor Integration": "PhrCYI9cgOUPkm9q",
    "Droid, Class V: Droid Resistances": "EytmvRyqT80p1T2f",
    "Droid, Class V: Droid Systems": "TcxteD8uLGBNdqJn",
    "Droid, Class V: Droid Vulnerabilities": "UBycBOGG8zaHsgI0",
    "Droid, Class V: Force Insensitive": "sm0np8x0O1bK6g81",
    "Droid, Class V: Maintenance Mode": "mvsEJlI4AYyOCVrH",
    "Droid, Class V: Manual Laborer": "XOVRj6jvm8PIyX25",
    "Droid, Class V: Powerful Build": "t1dd25WrVI9AEv97",
    "Droid, Class V: Size": "5kgwBia0jAadcovX",
    "Droid, Class V: Speed": "WahhVgc9cLVSekj9",
    "Droid, Class V: Type": "2qDHzrf4AV5IXqHT",
    "Dug: Ability Score Increase": "bfHkOqrepHgyJoGV",
    "Dug: Age": "VZIf95XNsr1XN9EW",
    "Dug: Alignment": "lDS32I41nh9YkNzB",
    "Dug: Courageous": "II9IENb7Er1BIqL1",
    "Dug: Fisticuffs": "XGdgm3UDCdoHpwWG",
    "Dug: Fury Of The Small": "UjCnM7a5Rcrx2exP",
    "Dug: Languages": "zNVxgjfjNiNeCpLX",
    "Dug: Menacing": "JKVhaI2g9fVDug1d",
    "Dug: Powerful Build": "siQxGYRoWBUAWRRE",
    "Dug: Size": "9NzAgOjYGplObNhH",
    "Dug: Speed": "lZCm32KOm6birpBE",
    "Dug: Strong And Small": "ALjLheBg8n1q1OkS",
    "Dug: Undersized": "33kOvUh0fDkPyY9x",
    "Duros: Ability Score Increase": "NwEwOl7dUbIH8oHM",
    "Duros: Age": "qv1FKyOApe3qSSnj",
    "Duros: Alignment": "v1GYD333SLnUX5UO",
    "Duros: Darkvision": "OpPLECzkk05haTNI",
    "Duros: Galactic Traveler": "hiZx2SEQOHOymVE5",
    "Duros: Languages": "suOB9CjpiE9yXyym",
    "Duros: Pilot": "BRaGPCE7gOiESjFz",
    "Duros: Size": "E1xVQBjZwifK6Z4K",
    "Duros: Speed": "1FbotdqUhNGPoAgJ",
    "Duros: Tech Resistance": "1mS1sNpFVgrienpw",
    "Echani: Ability Score Increase": "hOKQYetrhsehSTyj",
    "Echani: Age": "EADB8KxwiNMmg9oz",
    "Echani: Alignment": "X0f3aym0aAoiGMO1",
    "Echani: Allies Of The Force": "0x6q14DuHcr6PQJL",
    "Echani: Combative Culture": "rwzxOXDbuewUXgfy",
    "Echani: Echani Art": "pDXTxP0ZJJYT1Lu4",
    "Echani: Languages": "IP85FsW1FVwaZ7PL",
    "Echani: Martial Upbringing": "rIkYyxvESil7HfVh",
    "Echani: Size": "D6M2CDkGoVdQVXck",
    "Echani: Speed": "QYr4bngqjeuHGQmK",
    "Echani: Unarmed Combatant": "tV1nzQNIZhVKnRdk",
    "Esh-Kha: Ability Score Increase": "pbOsKtGQPT3fTYNx",
    "Esh-Kha: Age": "kmsaJqby4fffL0wh",
    "Esh-Kha: Alignment": "PjzRt3XQYBmJV4Nh",
    "Esh-Kha: Darkvision": "JfJIydJjgiCRLYKK",
    "Esh-Kha: Force-Sensitive": "o8CVmwWyb9e5alSC",
    "Esh-Kha: Inquisitive": "HLmjaTK1YvHEnjqw",
    "Esh-Kha: Languages": "kl7kdhpFAIlfahUg",
    "Esh-Kha: Savage Attacks": "PiJTlIoj78EvUebV",
    "Esh-Kha: Size": "SCY2q5xfsG4onGRq",
    "Esh-Kha: Skill Versatility": "ouv7K8ww8EJ6CmJh",
    "Esh-Kha: Speed": "rEjEmCHrNept63lG",
    "Esh-Kha: Weapon Training": "XzbYWQlJ1VF49Jzb",
    "Ewok: Ability Score Increase": "JskzmMntBvSgfbJ1",
    "Ewok: Age": "y0jAwwfvMKmQJ266",
    "Ewok: Alignment": "7HB6n9QkOr7XF1ce",
    "Ewok: Crude Weapon Specialists": "htbAHofVYeO0gDoZ",
    "Ewok: Keen Smell": "hhfRRJp8nDRowXpZ",
    "Ewok: Languages": "egdAFPDoVsdoNApg",
    "Ewok: Mask Of The Wild": "71NnCTvlMaTYfpgQ",
    "Ewok: Musical Culture": "yZTsBLmkAidmPn9d",
    "Ewok: Natural Survivalist": "S3QAQIcZS1TdUzop",
    "Ewok: Size": "sGC8IZWHJOJcQ808",
    "Ewok: Speed": "vn3waADu2IF7FvYz",
    "Ewok: Treeclimber": "P3M8d0bNOwi0IKVP",
    "Ewok: Undersized": "o9yQruDKWTvqTpzc",
    "Falleen: Ability Score Increase": "jOjRF9hMTIgaeJ3O",
    "Falleen: Age": "aw8O4yCGmeu18cFT",
    "Falleen: Alignment": "EXQL8fwV5aLFZ8fV",
    "Falleen: Closed Mind": "SulxkG5NjxWJpeyJ",
    "Falleen: Enthralling Pheromones": "bJkmyY4PP6bA8Z3T",
    "Falleen: Hold Breath": "RgONvCv1q0ALf2Tj",
    "Falleen: Languages": "NWLZpMjnVPJnoTCb",
    "Falleen: Mask Of The Wild": "yiZLw83pgjh2mAUE",
    "Falleen: Size": "2faIt1aMQHlXq1Hx",
    "Falleen: Speed": "glHebh4e3OTmLQou",
    "Felucian: Ability Score Increase": "bB3RtU3TTVDJR7bb",
    "Felucian: Age": "iJdvFmy0setg1nYr",
    "Felucian: Alignment": "P5ODaDJeWKML3cAD",
    "Felucian: Amphibious": "7TfAKPAhoaBKvhHP",
    "Felucian: Force-Sensitive": "54rF2wJC70rD5uus",
    "Felucian: Languages": "CcfGJDrPTnKhUBWm",
    "Felucian: Mask Of The Wild": "gvaQE96uf9ane4Ta",
    "Felucian: Size": "0a4XtsuTeV3fGLJy",
    "Felucian: Speed": "lps30KUEIQXxqnSp",
    "Felucian: Stealthy": "m3bbWqoIlwM3MDFF",
    "Flesh Raider: Ability Score Increase": "WRT7fmDLte2rRwr1",
    "Flesh Raider: Age": "0SCliGVlylxzU23W",
    "Flesh Raider: Aggressive": "afquRwdlix2TEUP2",
    "Flesh Raider: Alignment": "UQ7KNyloA1IR2383",
    "Flesh Raider: Cannibalize": "0NqWQ64Il9nh2HMz",
    "Flesh Raider: Darkvision": "htDiuL7mbgKApyXy",
    "Flesh Raider: Force Contention": "PIhN7pTeQxSi0U3N",
    "Flesh Raider: Hunters": "6givFH3bMpiHwApX",
    "Flesh Raider: Languages": "DQH06DaCn3rxSGeR",
    "Flesh Raider: Menacing": "hilfLtavLRcvePiS",
    "Flesh Raider: Size": "RGAt8MhZN09ZuCtw",
    "Flesh Raider: Speed": "cRCG0nyrMqIgv3rj",
    "Gamorrean: Ability Score Increase": "ceZOglYrx6k7gimh",
    "Gamorrean: Age": "9FC2jhv7RGP2cWlX",
    "Gamorrean: Alignment": "HirQm7rwSmjUbQim",
    "Gamorrean: Gamorrean Toughness": "kvLqu1G3VImgLz1C",
    "Gamorrean: Gamorrean Weaponry": "VqMOMX98AQQK7IfO",
    "Gamorrean: Languages": "xpNplyxnEAUJANKV",
    "Gamorrean: Savage Attacks": "zkHV8TjViegXdVhl",
    "Gamorrean: Size": "3DOvK7l3QNpZiDYe",
    "Gamorrean: Speed": "cIXE5AsDrknicc0P",
    "Gand: Ability Score Increase": "SpXh9C7E4Ffyj4vX",
    "Gand: Age": "duNWOEygJBYFxiyA",
    "Gand: Alignment": "sLkv1C8aXqRRFye2",
    "Gand: Exoskeleton": "X7gCzNLSUU5C278D",
    "Gand: Gand Resilience": "bXQlolvPGwu8fTL8",
    "Gand: Languages": "h8bqG9GjATLdgxFt",
    "Gand: Lungless": "9BH6j92PjvToEu53",
    "Gand: Regenerative": "qJN1hZnPZsOEsLb1",
    "Gand: Size": "fIz4nLr3bS9UTecY",
    "Gand: Speed": "lfHfuUY1i5gQP0UK",
    "Geonosian: Ability Score Increase": "TJet2yXl0Clx6Cbd",
    "Geonosian: Age": "Gi6vEwurKq4RgOO7",
    "Geonosian: Alignment": "b1kSnDrRzpxx53fo",
    "Geonosian: Crafter": "bYT6Ainn9MA9F1HL",
    "Geonosian: Exoskeleton": "8Kw2ZnQrUCjRmWkX",
    "Geonosian: Flight": "ozAjdMafaeH7zjpX",
    "Geonosian: Geonosian Weaponry": "NiYGsDC4ZXJPM26e",
    "Geonosian: Languages": "Hyye5NuZH0EaDHQm",
    "Geonosian: Size": "c2vSgTPQjm6qdb5P",
    "Geonosian: Speed": "3gZRvngAYVx259fi",
    "Givin: Ability Score Increase": "P6ZonhMI9Co1QsjG",
    "Givin: Age": "vCcUkKJbWaR0oIBV",
    "Givin: Alignment": "AQybq7iTritOEN6C",
    "Givin: Hardened Exterior": "IPIEovexjyMVxxXK",
    "Givin: Languages": "GpjfWVzwdML2T0OW",
    "Givin: Mathematical Savants": "POJ72OFKSt92BYaJ",
    "Givin: Size": "G3IxSwi38CT91DMf",
    "Givin: Speed": "N749p3BAlpq6lK09",
    "Givin: Stargazer": "g8ep5etHSUolAfWn",
    "Givin: Vacuum Sealed": "YwhT07T5GHPb3vVl",
    "Gotal: Ability Score Increase": "ebwq8d9jYqvy8QdT",
    "Gotal: Age": "XXU2qnTUv0G4SDqL",
    "Gotal: Alignment": "uJ2LZ76MqQ38Ao7b",
    "Gotal: Energy Sensors": "JFiqqytkXUXOwujh",
    "Gotal: Hunter": "gX9prpICCtIuTwH8",
    "Gotal: Languages": "oEB1ilLkyKNytbVN",
    "Gotal: Natural Empathy": "zjCTGmQixsAcqavT",
    "Gotal: Size": "aSgIAFMdN0IwC4Ya",
    "Gotal: Speed": "x92QudcqSll8pJ5A",
    "Gran: Ability Score Increase": "Wo5Y5jhumj5H7cFK",
    "Gran: Age": "Oef3gtND5O1tujI5",
    "Gran: Alignment": "w3Ah06ZwpsCsO8nT",
    "Gran: Keen Sight": "aVgSugqIOAofeiib",
    "Gran: Languages": "9SwM7ByEYVu1vqqX",
    "Gran: Reader Of Hearts": "RuGqqr2PvSJlEz4E",
    "Gran: Size": "Jx9KaDLB2LeYLFtC",
    "Gran: Slow Metabolism": "c6zrMgFVAuZmCNmt",
    "Gran: Speed": "HOwOUjznUo03tFgC",
    "Gran: Toughness": "Xm7iqs7FxbvgsFsh",
    "Gungan: Ability Score Increase": "FUybagx2vWPwETpi",
    "Gungan: Age": "5KTh1nWAE5PHvIYA",
    "Gungan: Alignment": "vWTMOtua9uBRcBFc",
    "Gungan: Amphibious": "bfRaVFPJMYF23FdS",
    "Gungan: Darkvision": "fh5twXIkjxfpWMZ4",
    "Gungan: Languages": "1XQDZ7xbGAWISG8l",
    "Gungan: Martial Proficiency": "8VDvwHyOVa7bMiqm",
    "Gungan: Size": "ITFAprM5fffeOfkb",
    "Gungan: Speed": "nhmM7vBhbxCeItd0",
    "Gungan: Strong-Legged": "SHTQFZiBifi9zhxh",
    "Gungan: Swim": "xwcvUmKof5itOIwB",
    "Half-Human: Ability Score Increase": "VnNkVFRHDFCgVyKh",
    "Half-Human: Age": "xAneQ07MDMKoKfd6",
    "Harch: Ability Score Increase": "XOplb3IhwEDA5MRc",
    "Harch: Age": "dcz0vaFhT3pwLqI6",
    "Harch: Alignment": "w8O42zVETkD5lnhE",
    "Harch: Bite": "EJNXsi10V1825Z3V",
    "Harch: Darkvision": "pYSSIYHhZVRJolWH",
    "Harch: Languages": "0NYohK511YwAtvdA",
    "Harch: Six-Armed": "SY1RDZHfn7FxSvS4",
    "Harch: Size": "YBelsD7idVVmgkZJ",
    "Harch: Speed": "BDLJRBux1YYhYl5S",
    "Harch: Spider Climb": "RhxXpTVSZjJV4M7A",
    "Herglic: Ability Score Increase": "i3MWYpvHHWN5DPmd",
    "Herglic: Age": "y3RhYYXDkFooAdKx",
    "Herglic: Alignment": "pg4pVu5CmmP0WF12",
    "Herglic: Hold Breath": "6X4s2MbJDOGsfHvr",
    "Herglic: Languages": "7aTUZcJZfL1Ewhxr",
    "Herglic: Powerful Build": "FuWmnVmshObiTO08",
    "Herglic: Size": "TOOpwwoVFKgNPBbS",
    "Herglic: Speed": "Ljjupo4eCquwPNUK",
    "Herglic: Swim": "0eoamS7mMLyf7SUF",
    "Herglic: Technician": "4TAsBXPXbGKIrpQY",
    "Herglic: Toughness": "LiLiCZY0lC1xBcBs",
    "Human: Ability Score Increase": "9pShGSyosWELOO3j",
    "Human: Age": "yT0fYuhRrI2IVyq0",
    "Human: Alignment": "FZFTohqAUiQKRYTY",
    "Human: Defiant": "PYoMlYnSirNMGqZH",
    "Human: Languages": "hLjVF2aywj2pvefY",
    "Human: Proficiency": "TYr21H7kj19WHlOC",
    "Human: Size": "5moDm5vzDS4ZSUH0",
    "Human: Speed": "vVvS7KEkU9ODJljJ",
    "Iktotchi: Ability Score Increase": "mVfFpSRoARUsq4dA",
    "Iktotchi: Age": "IFDUusVaEsktLTQN",
    "Iktotchi: Alignment": "UsSaq7Zn7SkNVNhK",
    "Iktotchi: Horns": "QdFSnMNYZpLfNYNs",
    "Iktotchi: Languages": "rJYEkFlq2JyV30Mf",
    "Iktotchi: Pilot": "prVyzvROuzaZovbL",
    "Iktotchi: Precognition": "BKxU9whb3dBgnUd0",
    "Iktotchi: Size": "yRwFOy88JYyvPdnC",
    "Iktotchi: Speed": "4r1YbmpxI6wHM3N4",
    "Iktotchi: Telepathy": "mGA51XZg7YqhHG5Q",
    "Ithorian: Ability Score Increase": "0RMFdZbh6fGPK3LN",
    "Ithorian: Age": "YpaKmn70AaXab5Dp",
    "Ithorian: Alignment": "4rj8mJNGMJIZ68Cb",
    "Ithorian: Hold Breath": "fYdCcCoti63IWpA6",
    "Ithorian: Languages": "oBWBXzDlfABaPPmt",
    "Ithorian: Size": "Exrk7V9d8s5cglX4",
    "Ithorian: Sonic Resistance": "Uvh1nN9I27Iwdlfd",
    "Ithorian: Sonic Scream": "DsThU7MLdD5TpPNA",
    "Ithorian: Speed": "1kgG6CrNHozdc0WF",
    "Jawa: Ability Score Increase": "g3pL3gFHNEiTaF9F",
    "Jawa: Age": "61DdCgdYlBn1WIno",
    "Jawa: Alignment": "1LXsg59fSDfNIclc",
    "Jawa: Darkvision": "sHCXSg7sHbc8Qg61",
    "Jawa: Grovel, Cower, And Beg": "40dIy0KjY0eBmruh",
    "Jawa: Languages": "A5P9TSgWdtvCbCah",
    "Jawa: Size": "fWF9HBjqTyW2g7Jp",
    "Jawa: Speed": "uAKTSAnIpFBkQAnZ",
    "Jawa: Tech Dabbler": "kemD76X8YGHVGZsN",
    "Jawa: Thieves": "j3ZWAWgAw5R9Qwmu",
    "Jawa: Tinker": "DWdkXUkf5DVnTaJU",
    "Jawa: Undersized": "16Uu8g3qDla4W2xS",
    "Kage: Ability Score Increase": "g2Adj33UAt1x7lXu",
    "Kage: Age": "mLOBR0DSB9JvnhP4",
    "Kage: Alignment": "PRHM5Ye0XRUKnP4N",
    "Kage: Animal Handler": "90ZvqbFBHaLAPRqA",
    "Kage: Athletic": "wgMpUQ5y79UrwK9e",
    "Kage: Languages": "MgUzJHPOpcDYShyr",
    "Kage: Size": "fffi6vYsf4uq7pSY",
    "Kage: Speed": "lH9dGoMx7JojFpOO",
    "Kage: Strong-Legged": "QlaXjMfCGII4YCna",
    "Kage: Sunlight Sensitivity": "mtMiAzYJqAcXmdvR",
    "Kage: Superior Darkvision": "Efk7jMGsc1pD9EYh",
    "Kage: Unarmed Combatant": "z3VxvZw658nd4ULa",
    "Kage: Weapon Training": "6txVQXEPIZYmY4UF",
    "Kaleesh: Ability Score Increase": "UDl4r6c5Z58qroZk",
    "Kaleesh: Age": "34gSt5lX7kTh4ZUe",
    "Kaleesh: Alignment": "NK5pbuc7Hsli4UdH",
    "Kaleesh: Darkvision": "7tfdgOuQq0uuMFUM",
    "Kaleesh: Keen Smell": "QU6W20ao6UYaHLjM",
    "Kaleesh: Languages": "97Ws97epxmvfBSNG",
    "Kaleesh: Size": "RqCDE5BDFtnghR6z",
    "Kaleesh: Speed": "IuQ28jWNCdHDqUOP",
    "Kaleesh: Tracker": "z4L2zEdXf9TmMTuj",
    "Kaleesh: Weapon Training": "7nPjLlEMCupLUzie",
    "Kaminoan: Ability Score Increase": "4ltDsxOWe5jKkoCe",
    "Kaminoan: Age": "zX9PEX5oKC5Y01fe",
    "Kaminoan: Alignment": "BFs1rQBZyytvzpT4",
    "Kaminoan: Geneticist": "YW0qIfDQEuYudfl0",
    "Kaminoan: Languages": "FyBzXdME2wakHYIt",
    "Kaminoan: Long-Limbed": "3sJrPtcgbVQ8gZi9",
    "Kaminoan: Size": "4X1T1mLwBOBz4jPt",
    "Kaminoan: Speed": "KuAKAGXfh3dIWXcQ",
    "Kaminoan: Tech Dabbler": "xZAh5W6DFPsk7BD3",
    "Kaminoan: Ultraviolet Sight": "2fuVafVV8vk8mT8F",
    "Karkarodon: Ability Score Increase": "xocYxeDf5xrYjSSv",
    "Karkarodon: Age": "BPJKvQUJ0Qwj0Py6",
    "Karkarodon: Aggressive": "e9Bgj9gX9kUfvDAU",
    "Karkarodon: Alignment": "UzeTxoPcsAVQ3G5L",
    "Karkarodon: Amphibious": "ilg0GhcIJYML5ie1",
    "Karkarodon: Bite": "XsW9ncnYlsF9klyd",
    "Karkarodon: Languages": "jX6ATLLvdDXMoMV0",
    "Karkarodon: Size": "fh4zYZgiqo13jxIK",
    "Karkarodon: Speed": "bMgZkNwVFjhgFOjn",
    "Karkarodon: Swim": "qPwHJTNzuUd9au8H",
    "Kel Dor: Ability Score Increase": "W3jXKJ4psFIQZiRg",
    "Kel Dor: Age": "f78lOg0OZY9lqYu1",
    "Kel Dor: Alignment": "9XvaWetjdV20EHvw",
    "Kel Dor: Darkvision": "73OU2kXiPB4DdNWt",
    "Kel Dor: Foreign Biology": "OtQAf8xlwNaq1zWU",
    "Kel Dor: Languages": "54iQEunZT5d8unvP",
    "Kel Dor: Life In The Void": "b3PDXGN9WYWAktkU",
    "Kel Dor: Size": "dyBtZ7LHa0VNJhg7",
    "Kel Dor: Speed": "MhwUXmS3gbVsSwoN",
    "Kel Dor: Telepathy": "DJoRAribT9hxOPD6",
    "Killik: Ability Score Increase": "qe0yM2PNpqQDmjrP",
    "Killik: Age": "fEgNMWHJ5wWm9aHi",
    "Killik: Alignment": "En1uDqai5vOpx07f",
    "Killik: Four-Armed": "ldc5RhkKO1AcUNHI",
    "Killik: Hardened Carapace": "St27etSQ4gWh5r8t",
    "Killik: Languages": "Tm42Tydd6DL2jMlf",
    "Killik: Size": "deoPHGaepe12Ctjp",
    "Killik: Speed": "ZtKNfOySgWy3PSDj",
    "Killik: Strong-Legged": "VAG5TFMzWMcEBgsG",
    "Killik: Telepathy": "veAcSxCJ1mhcUHVS",
    "Klatooinian: Ability Score Increase": "WUeeI1WAUReRx4EF",
    "Klatooinian: Age": "urOCKvk4BsOGWjBV",
    "Klatooinian: Alignment": "YeG8iChQm6CUp3Mf",
    "Klatooinian: Enforcer": "mYI8Y3DjArW6LvHN",
    "Klatooinian: Languages": "fZfw58F3pY0wUNpu",
    "Klatooinian: Size": "lLTb3dg9d0dvQypB",
    "Klatooinian: Speed": "YfpXgWNvgpBDR8wu",
    "Klatooinian: Toughness": "VbYKG1YtK2nJ7Umy",
    "Klatooinian: Weapon Training": "NGoevNp9gwZIUd15",
    "Klatooinian: Wisdom Of The Elders": "E1RO8XvQJHp0gxVV",
    "Kubaz: Ability Score Increase": "6HAuGOLhHx5mWIrX",
    "Kubaz: Age": "uFgxdmzesPSKnJN2",
    "Kubaz: Alignment": "Upz2a4mR7EisV1Mu",
    "Kubaz: Art Obsession": "hcNlsxT9UimknpwN",
    "Kubaz: Darkvision": "ekVKhvAypeUHKjw3",
    "Kubaz: Deft Hand": "bYlCMArnL2ntSW3l",
    "Kubaz: Keen Smell": "zVpYgnGsw4ttvf5t",
    "Kubaz: Languages": "fwvGEYbnbQskvJmH",
    "Kubaz: Size": "8jInqsAw59ZsOYli",
    "Kubaz: Slicer": "wbN9tkGqgGy40KK4",
    "Kubaz: Speed": "fg6lf9xMh5jYgVjd",
    "Kubaz: Sunlight Sensitivity": "ntRTXPBQNsirfQJQ",
    "Kushiban: Ability Score Increase": "sw2JdfnY2PhPKIES",
    "Kushiban: Age": "RgLkQATwwbjAtOi7",
    "Kushiban: Alignment": "66o8vr45b0pHSL5X",
    "Kushiban: Grovel, Cower, And Beg": "AkBUKZ2hemrUUkZ0",
    "Kushiban: Hide": "i777vAmBuXPnhkoB",
    "Kushiban: Languages": "t5zuZjgySmsAEYIZ",
    "Kushiban: Mask Of The Wild": "5BMLnvwVfUFlZcgx",
    "Kushiban: Nimble Agility": "MrzfqIOMNZOdSf1w",
    "Kushiban: Size": "xqvPcw6Yk8FI9FSZ",
    "Kushiban: Speed": "SvU4XLxMLCThs0EE",
    "Kushiban: Stealthy": "lhAUXavTSzktClSU",
    "Kushiban: Undersized": "ym63GZiLZEBJqgBA",
    "Kyuzo: Ability Score Increase": "7UIYIhsWuswcVrl2",
    "Kyuzo: Age": "OVIKOpv8UGm4kFsl",
    "Kyuzo: Alignment": "jrtpxGjqu1cFWF5A",
    "Kyuzo: Darkvision": "C15yp9OQ3O7C58AK",
    "Kyuzo: Foreign Biology": "EJsJsCsel9RRbSHv",
    "Kyuzo: Languages": "2du4lpo6K508QEhL",
    "Kyuzo: Long-Limbed": "yfpCcVAW17FUwgL5",
    "Kyuzo: Size": "r8I7Mao1g87B0Khn",
    "Kyuzo: Speed": "wkUwuV5b9KkpT8od",
    "Kyuzo: Strong-Legged": "amIXMBFj7aqIwQNB",
    "Lannik: Ability Score Increase": "6cPHqFfuhqhmVlHI",
    "Lannik: Age": "rm46QcQUIE9eDA16",
    "Lannik: Alignment": "zU5sMiT3Gnb1OKYh",
    "Lannik: Closed Mind": "rhIiaiYZ7IrmQfOS",
    "Lannik: Force-Sensitive": "vXx2P1chWdrNDCTy",
    "Lannik: Keen Hearing": "I99Mo5q7VMwZP4cN",
    "Lannik: Languages": "8M5mbWcQe4FhDaKa",
    "Lannik: Size": "DD3Zqud0MximVIT6",
    "Lannik: Speed": "WMpMkH5CyJbni9DI",
    "Lannik: Undersized": "le3SOqAZYi4BhSoN",
    "Lannik: Wisdom Of The Elders": "084QrUV6JKm0noC3",
    "Lasat: Ability Score Increase": "TNShqUBjycAeowqU",
    "Lasat: Age": "XzqQPdEyyZTZitUS",
    "Lasat: Alignment": "gNeU3NueXe5zBxjw",
    "Lasat: Bo-Rifle Training": "SL67JXLZhLWmxG3k",
    "Lasat: Climbing": "rBUteWvbRx63JZYc",
    "Lasat: Darkvision": "aaBseL3cMXjrXaln",
    "Lasat: Keen Hearing And Sight": "NZyVQzlTtD0ZmeV0",
    "Lasat: Languages": "jQdCAUh0rTtPiUpE",
    "Lasat: Powerful Build": "1OuZUDUtKuq71I9Z",
    "Lasat: Size": "IiHORcwEgTC4AdBl",
    "Lasat: Speed": "iR07UfBG8QTxaPJf",
    "Miraluka: Ability Score Increase": "O5iIaCf18yFw769A",
    "Miraluka: Age": "b6HoXsihIPzdbE4x",
    "Miraluka: Alignment": "u6vhCKKLq64I9DUR",
    "Miraluka: Force Sight": "0Rukcdxt5JZ335mg",
    "Miraluka: Force-Sensitive": "jPIyFzBofCNp02Xr",
    "Miraluka: Languages": "kGYhQoe8pC4xcH0c",
    "Miraluka: Size": "bbge3F2ps1wQz3eD",
    "Miraluka: Speed": "aHZU8TbvdmduThOb",
    "Mirialan: Ability Score Increase": "XP4gJO0zghK7SFv7",
    "Mirialan: Age": "cp7Uwe419PXMbqTF",
    "Mirialan: Alignment": "zBPo23fxev5Zrt52",
    "Mirialan: Languages": "Fe0sZITtAy0tSXUN",
    "Mirialan: Size": "6lTuX27aJOJs15Pj",
    "Mirialan: Speed": "XCprJ8shktLYRQwJ",
    "Mirialan: Spiritual": "MiRFu4Dx957QqY4E",
    "Mirialan: Surprise Attack": "Z1xze7UznOj0Ty2t",
    "Mirialan: Unarmed Combatant": "Bo8nb4urlVzjCZPa",
    "Mon Calamari: Ability Score Increase": "IwYMjW11f5PCzSrF",
    "Mon Calamari: Age": "4HiP0Xa2JnTjhJIV",
    "Mon Calamari: Alignment": "qZsWWQSjbUnpB1nX",
    "Mon Calamari: Amphibious": "5uQZH1XbDrmESST4",
    "Mon Calamari: Darkvision": "xf24Ke55vyz6nHLe",
    "Mon Calamari: Languages": "olhAhqSvOkmmo3jP",
    "Mon Calamari: Mon Calamari Resistance": "yYyvbbbmZrKiVAqm",
    "Mon Calamari: Musical": "c6W7cqt1g0EF7NY2",
    "Mon Calamari: Size": "YkYRT3YD9rrkgDQG",
    "Mon Calamari: Speed": "BxOSHE56tgwYlIGB",
    "Mon Calamari: Swim": "pLn1OlblCt1K7qvm",
    "Mustafarian: Ability Score Increase": "norhoBzxYJGnxsj5",
    "Mustafarian: Age": "JxibmpQpQxPY8iF2",
    "Mustafarian: Alignment": "1ig41i4QjzaoXOsE",
    "Mustafarian: Darkvision": "ckz8XgtEV8ZC24mm",
    "Mustafarian: Hide": "yQMcTTqIrcJYbr4J",
    "Mustafarian: Languages": "Q2oFs7dEjOhNoFTA",
    "Mustafarian: Lava Dweller": "YJbBmv6QUxo4zM8O",
    "Mustafarian: Refinery Specialist": "nw9FWBLi4AZcZzqs",
    "Mustafarian: Size": "SRCG0cJbcqlQ3DZe",
    "Mustafarian: Speed": "bEOBciVg0g0dfs94",
    "Muun: Ability Score Increase": "2KY9CIO2lQaO9x9G",
    "Muun: Age": "pMZCTcmmZXSdbHVK",
    "Muun: Alignment": "1nUjReQpek8u4cAS",
    "Muun: Finance Savvy": "y9PpiyV71N1304Oo",
    "Muun: Languages": "W5AcEnMoUHlekLIu",
    "Muun: Long-Limbed": "3YMEbObytCVtJRuD",
    "Muun: Size": "HAnu7ZJLFWTyC13F",
    "Muun: Speed": "yCw0wq8gL0Gog87R",
    "Muun: Three Hearts": "IeqDMLSFj4qHnoNV",
    "Nautolan: Ability Score Increase": "Bt5ReHZf75T7VncE",
    "Nautolan: Age": "PMSgKvvNJO3faFHo",
    "Nautolan: Alignment": "EG1FgSI6iX6TBXkI",
    "Nautolan: Amphibious": "fRDUvHJBzSOf0BI3",
    "Nautolan: Darkvision": "iPrfZja0sBxPukP9",
    "Nautolan: Insightful": "NowrmCyybW2OWVdP",
    "Nautolan: Languages": "2nFnCb8syFO2DXON",
    "Nautolan: Size": "fzE5zQOU3jqEZA7e",
    "Nautolan: Speed": "8RjXeAP2Z5icUkxU",
    "Nautolan: Swim": "06WRji4E3ZmHSvMS",
    "Neimoidian: Ability Score Increase": "GPI3XrgWGaBSi5R8",
    "Neimoidian: Age": "IcgqiwJ5zQYzI6mz",
    "Neimoidian: Alignment": "gYsquy132AWDkG50",
    "Neimoidian: Darkvision": "6cUUCMg1qjvvgtKG",
    "Neimoidian: Grovel, Cower, And Beg": "9vwWaIwnpymuAecz",
    "Neimoidian: Languages": "ybmoCrJulJQSHxUa",
    "Neimoidian: Size": "dkbGg8TZiUQJjGXn",
    "Neimoidian: Smooth Talker": "iYMNig0OFNJsuJxz",
    "Neimoidian: Speed": "KhDWVdqejt1SFDUU",
    "Neimoidian: Wealthy": "6s69Fv1afXTAdQMS",
    "Noghri: Ability Score Increase": "xdhvoHddImGovF0x",
    "Noghri: Age": "9XdHPsho5jVoDzHy",
    "Noghri: Alignment": "LCfaUgcW78pLnXEL",
    "Noghri: Hunter": "cNf4yVgqEuKy4Jcy",
    "Noghri: Keen Smell": "EnHBC2EaNTPOVC74",
    "Noghri: Languages": "JCUmN6Jwj3lzCE9j",
    "Noghri: Powerful Leap": "LmfeW15IN0y0bwSe",
    "Noghri: Size": "twfDuQKCzv04Tl7I",
    "Noghri: Speed": "X5dH6ADPH84kbAso",
    "Noghri: Strong-Legged": "Wa9ThdaFQfAH3ibX",
    "Noghri: Unarmed Combatant": "RZto8qr1sUD7NCIW",
    "Ortolan: Ability Score Increase": "6QRpmalPvybFIiZk",
    "Ortolan: Age": "BHsCJZmNzghzq2my",
    "Ortolan: Alignment": "xUh0lC4GfyUY4ec1",
    "Ortolan: Foragers": "FmjUSJtnYWypSnhG",
    "Ortolan: Grovel, Cower, And Beg": "UYGrL5doEbwpCJy3",
    "Ortolan: Hide": "bsKZmytZ6S2bVLP0",
    "Ortolan: Keen Hearing And Smell": "7Thp195UPImFNXpk",
    "Ortolan: Languages": "xIEWkzGLLxhAD20s",
    "Ortolan: Musical": "dKPcUvLm4mDxupUC",
    "Ortolan: Size": "quUIdimvrSwtQSzo",
    "Ortolan: Speed": "ito1Z5xcAmcSu2hx",
    "Ortolan: Undersized": "Pqc2ggTjqCZoMf85",
    "Pa'Lowick: Ability Score Increase": "e3hXcBn92U4Im84d",
    "Pa'Lowick: Age": "r87kJEKjjhJzD5L0",
    "Pa'Lowick: Alignment": "VIUsw3377DkS1TeH",
    "Pa'Lowick: Hold Breath": "38dEZRUb1vETkBOs",
    "Pa'Lowick: Languages": "skLw1J4HEyvwgF5y",
    "Pa'Lowick: Proud Performer": "Ptfx5KvoZd7KkY5G",
    "Pa'Lowick: Size": "VDjSXWTnLN7nyjgx",
    "Pa'Lowick: Snout": "Gw2oZnCTKMyF8uNv",
    "Pa'Lowick: Sonic Scream": "yaV4vZw8JAABus2E",
    "Pa'Lowick: Speed": "3nb3D7glq2UoDzS4",
    "Pa'Lowick: Swim": "30RYpnvoZ6FtfOZt",
    "Pau'An: Ability Score Increase": "oSNRHYfvKOKGxLtF",
    "Pau'An: Age": "j0mU4ictjfZvCp5d",
    "Pau'An: Alignment": "oFjHvMrbJiczfoJ3",
    "Pau'An: Authoritative": "NjtdrqjMNyIDILA1",
    "Pau'An: Cultured": "lVu6PLGUI7cVYFBv",
    "Pau'An: Darkvision": "iNnTZFrQWGAQcBx1",
    "Pau'An: Hypersensitive Hearing": "WnFiOXK3ZePuBSpz",
    "Pau'An: Languages": "EZ7mWEooVnzm4RmI",
    "Pau'An: Size": "THseTKG1ZUGLxswJ",
    "Pau'An: Speed": "YnqadOuroDIoaFsI",
    "Pau'An: Vigilant": "CxRDrouq3D2X2GGJ",
    "Pyke: Ability Score Increase": "U6YOblefUc6b8zRV",
    "Pyke: Age": "poOrbzoFlTZibnGt",
    "Pyke: Alignment": "nPb5r8wcB1VniLpS",
    "Pyke: Languages": "78QO7Jblp4KkWkZK",
    "Pyke: Long-Limbed": "Rvx2FBLW4cTOya7a",
    "Pyke: Mercantile": "3T0QDtOO4h3nbc8u",
    "Pyke: Notorious Slavers": "8Vkynhoksgmc5rPk",
    "Pyke: Size": "spr83BTKuf34yx9c",
    "Pyke: Speed": "p6083ulwVoxq9CSr",
    "Pyke: Spicer": "frEQxEA5ArTXSIOs",
    "Quarren: Ability Score Increase": "8NBO9T1XLQmx7DFJ",
    "Quarren: Age": "SttCOOkbHTOzLe6H",
    "Quarren: Alignment": "G6zfEn2RmrsZwZlD",
    "Quarren: Amphibious": "ez7Ycdu3cYOdz4D0",
    "Quarren: Climb": "WpCyrdEHUbUNZbqq",
    "Quarren: Darkvision": "SzsaWBLfClLrK6VU",
    "Quarren: Ink Cloud": "DDsXYt8YsCVNZUEI",
    "Quarren: Keen Hearing": "jarZtiwbMi4lKQUI",
    "Quarren: Languages": "EIwhkUJ4eeWrmfFZ",
    "Quarren: Size": "8Y2nfybnNAYyR6GJ",
    "Quarren: Speed": "g0LuMomHkCH8L9yy",
    "Quarren: Swim": "8YjItoLiHsVrjba7",
    "Rakata: Ability Score Increase": "xqXvPPZK7UK6FigK",
    "Rakata: Adaptive Resilience": "vQWieULr6mH2B4m6",
    "Rakata: Age": "4Ydk4YHYKRdsbbF2",
    "Rakata: Alignment": "euGlDESi4y8F0X5H",
    "Rakata: Amphibious": "QlaiwHPoxhtm7k1Q",
    "Rakata: Cannibalize": "Xi2H8noXPc8VCIgB",
    "Rakata: Claws": "KgOOajT15BHWcBEF",
    "Rakata: Darkvision": "czLiQdWYlCaS0D6o",
    "Rakata: Force Insensitive": "OS7e7KEkbTKPbvjr",
    "Rakata: Languages": "YFzsknOv0x589MGV",
    "Rakata: Size": "Fx18t1YfUuI8USgu",
    "Rakata: Speed": "JWvKCdUHEnEFBI6o",
    "Rakata: Swim": "k57qJAAhlijYoqlp",
    "Rakata: Technician": "7jTRiBIxvdV5KycS",
    "Rattataki: Ability Score Increase": "7wumLZuKVA60MbU4",
    "Rattataki: Acrobatic": "vb0rekjLJ3LqXYsL",
    "Rattataki: Age": "YDASkbwUHUKmAKiR",
    "Rattataki: Alignment": "46c6MoRJ8FOb0lpg",
    "Rattataki: Intimidating": "g1EiHa85qqbM3LdB",
    "Rattataki: Languages": "ukj4wMoHUxAN3vl8",
    "Rattataki: Size": "a8svU6tLkEnHxhCU",
    "Rattataki: Speed": "Ci36KPG4Lhxz51l0",
    "Rattataki: Surprise Attack": "Nrjra2GTYY4ES6dW",
    "Rattataki: Unarmed Combatant": "zuM4GLC5OkHGp0lV",
    "Rishii: Ability Score Increase": "oP1l2JeRv9R9XcAG",
    "Rishii: Age": "dNGWnbFRLIFLDbl3",
    "Rishii: Alignment": "Cb5aMG247oQkoeOe",
    "Rishii: Flight": "Vwr32IkG1IwKryWh",
    "Rishii: Keen Hearing And Sight": "kZAhy2y7bys9NkCi",
    "Rishii: Languages": "ZjG6CCai396qhJ7Q",
    "Rishii: Mimicry": "sib4ZwIoc2DZrvY3",
    "Rishii: Size": "JS7CpicpukNxe57i",
    "Rishii: Speed": "GuntQNH1jOFcpVUa",
    "Rodian: Ability Score Increase": "XXkpDowQWh6YplSx",
    "Rodian: Adept Climbers": "cfQ6GpInX01jnQH8",
    "Rodian: Age": "jNDLGSX5sstD9Ur1",
    "Rodian: Alignment": "StyTYghRU9QCMUt3",
    "Rodian: Darkvision": "Osr4x9ZH0fW9zuYb",
    "Rodian: Hunter": "p7sEP2wxapPh17Uj",
    "Rodian: Keen Hearing And Smell": "KJDVDDsYc47EXkcL",
    "Rodian: Languages": "AbfVXeGOKGbU2rlN",
    "Rodian: Size": "0rA2pr6p8WnFBVLl",
    "Rodian: Speed": "DawH6EM4TBKm0v4Q",
    "Ryn: Ability Score Increase": "w9rNqR4L4DNpN5FG",
    "Ryn: Age": "qtHdfjImvPo5bLGX",
    "Ryn: Alignment": "fyTp5ugEJ9WPzF9g",
    "Ryn: Con Artist": "HgmmQXKDaTMKrkGL",
    "Ryn: Darkvision": "c6LWRJXFO69b0NzO",
    "Ryn: Divination": "imDeRGSukJwgppB4",
    "Ryn: Eternal Nomads": "UvDpHqhdehtJyGjy",
    "Ryn: Languages": "AZK9GUUpUnXILM7Y",
    "Ryn: Musical": "Anv2RsNTIviNgJxX",
    "Ryn: Prehensile Tail": "5Uk0tiOesd0fz65l",
    "Ryn: Size": "SphEGk3p5fLjx8yt",
    "Ryn: Speed": "1AgkO9058z2j6jek",
    "Selkath: Ability Score Increase": "2TXPwt47Ug1FOAiu",
    "Selkath: Age": "VjYb1w4h2QBlg3Cz",
    "Selkath: Alignment": "9wnYg5u1O74IYqS9",
    "Selkath: Amphibious": "4b45TeYGz9nQ52KM",
    "Selkath: Claws": "Bjz04HZxTnR6sejS",
    "Selkath: Gift Of The Progenitor": "4rJTYmnk0ymzyo9q",
    "Selkath: Languages": "OVav5ZN6fdU32dMT",
    "Selkath: Size": "oiA0BjVKEUuBh6va",
    "Selkath: Speed": "Op0CEF1DxzAl9UPq",
    "Selkath: Swim": "WwDsZbQaW8xfZjLc",
    "Shistavanen: Ability Score Increase": "yS7RmRT1ThLbnJBc",
    "Shistavanen: Age": "L2jzBexIvqOMuWfl",
    "Shistavanen: Alignment": "uF16QVMJc4rx4xBg",
    "Shistavanen: Darkvision": "BqxFkgowlEZJVGBt",
    "Shistavanen: Forced March": "X8KBCg2e55Q5EtuV",
    "Shistavanen: Keen Hearing And Smell": "oISAy9tftlKWhJPZ",
    "Shistavanen: Languages": "4e6Uo2hVOuer7kGD",
    "Shistavanen: Regenerative": "EsbwyLjZTdVzjFzm",
    "Shistavanen: Size": "70PSbsFE3km27uf3",
    "Shistavanen: Speed": "XcSw98P6JG9IRqzK",
    "Shistavanen: Tooth And Nail": "zj3t9TDsaXBoRYAA",
    "Sith Pureblood: Ability Score Increase": "pmUsea7gvFewasFz",
    "Sith Pureblood: Age": "5uwnCCTBzBlOyjtC",
    "Sith Pureblood: Alignment": "6HEZWCO77Zt2Oz9p",
    "Sith Pureblood: Darkvision": "yA9ezvSnW9RnU0I9",
    "Sith Pureblood: Force-Sensitive": "ReCXzSinnWr2Jkz9",
    "Sith Pureblood: Languages": "KeS3cfj5o3S90LGx",
    "Sith Pureblood: Menacing": "IiZY5NbfbqAWtkvZ",
    "Sith Pureblood: Sadistic": "dUh3lofk3eGxAipN",
    "Sith Pureblood: Size": "S35mifKMhpb6LDso",
    "Sith Pureblood: Speed": "IAZU4sSrsR3tQlg9",
    "Squib: Ability Score Increase": "mU3afRgENeDF1bT6",
    "Squib: Age": "FPpyG6t2DLE92dVF",
    "Squib: Alignment": "DMXWXkYTmDpbnBRw",
    "Squib: Bite": "TFUtxDcsCx7S4a8v",
    "Squib: Business Savvy": "bhijJISrBEYKRdY1",
    "Squib: Flexible Cheeks": "wxNkX4dD8QdJzw6G",
    "Squib: Hide": "txqLXMO3bXZd6Ay9",
    "Squib: Keen Smell": "NralJ7sKmvYhe5qC",
    "Squib: Languages": "fOEdbncV8GRgr9Jw",
    "Squib: Sensitive Fur": "WzCanr2hbJHZ22kt",
    "Squib: Size": "OY1fnCyEolVVbC4u",
    "Squib: Speed": "ImQFOuGPGV6xyDJ5",
    "Squib: Undersized": "Yciq6l7diWIbNAmd",
    "Ssi-Ruu: Ability Score Increase": "F2GRhbreKoM9JyVs",
    "Ssi-Ruu: Age": "FpHBvbpY3G8LJlms",
    "Ssi-Ruu: Alignment": "ra8dLjup5QYs93bP",
    "Ssi-Ruu: Force Insensitive": "yPc0AkCAU50RVffu",
    "Ssi-Ruu: Hunter": "b3XTUVzDyKwwP89i",
    "Ssi-Ruu: Keen Smell": "WqJ46uStgWNBeCk8",
    "Ssi-Ruu: Languages": "3FVxkGIIdw1di0Ho",
    "Ssi-Ruu: Natural Empathy": "rqhywmEhyVWXidtS",
    "Ssi-Ruu: Size": "9CrGiepiuqAw4kMx",
    "Ssi-Ruu: Speed": "xevnR4ETABlpEKid",
    "Ssi-Ruu: Sunlight Sensitivity": "50oLvHqy5mqMjqmL",
    "Ssi-Ruu: Thick Skin": "FQG7yP5iJryecI0m",
    "Ssi-Ruu: Tooth And Nail": "VWjN0h1b44Qp4Ljf",
    "Ssi-Ruu: Type": "TOWCWdUwro3i8TRM",
    "Sullustan: Ability Score Increase": "9tlVGp76TIFU8SAw",
    "Sullustan: Age": "gs90MsjQRRNm1EkC",
    "Sullustan: Alignment": "1KiT8NC75ziXeJbN",
    "Sullustan: Darkvision": "mvyyf8ETs0CBEomz",
    "Sullustan: Keen Hearing": "SSHo4CV6JpXfAVdN",
    "Sullustan: Languages": "9BIgsqgf5WSxzkNQ",
    "Sullustan: Mercantile": "uLRJ0RrKWMPr7rpp",
    "Sullustan: Pilot": "kH61vjMMD5nshW7s",
    "Sullustan: Size": "2p3MFBUB26GG7F2W",
    "Sullustan: Speed": "uvrFmG2Pa6Hw8Hhk",
    "Talz: Ability Score Increase": "jhlsD0kZELU26Bi2",
    "Talz: Age": "jJIbdMeRUb6SkaFS",
    "Talz: Alignment": "K8PMi8ZEtKST6Njr",
    "Talz: Darkvision": "rLR0RTNUQuvju6BO",
    "Talz: Hide": "SaZLijZ3EDDGpIwW",
    "Talz: Languages": "eaq2l0ACN8ANUoM3",
    "Talz: Long-Limbed": "8rjWQ3M2zIFmBE6Z",
    "Talz: Size": "duftya1h41lNuOIC",
    "Talz: Speed": "ljghMRGIq2vPVTf7",
    "Thisspiasian: Ability Score Increase": "YXEJpqu4FJzM96MI",
    "Thisspiasian: Age": "cnRNfnKlFkhxmvm2",
    "Thisspiasian: Alignment": "okmUGIMAjad7HaKK",
    "Thisspiasian: Claws": "UbGEJJSJiygAiDFb",
    "Thisspiasian: Cultured": "aDbdbSq259WaXFFB",
    "Thisspiasian: Four-Armed": "y8fvBDo3GIa5QTg4",
    "Thisspiasian: Inscrutable": "R04xTGTH1dCVZtAS",
    "Thisspiasian: Languages": "QR69oMR5rqjqM1UJ",
    "Thisspiasian: Prehensile Tail": "C72qBzU8VjQqIYTk",
    "Thisspiasian: Size": "2Fcua4rPf17poeyn",
    "Thisspiasian: Speed": "FkcExlaTdoHEnlyP",
    "Thisspiasian: Trance": "EmZiuR92NsTY0kCc",
    "Togorian: Ability Score Increase": "MAjmhpZmLDDYIC0a",
    "Togorian: Age": "zezIsvlCA0G8fjh1",
    "Togorian: Alignment": "rbqFpMk9IIVWZagU",
    "Togorian: Claws": "XO1HcoiIHit93mP6",
    "Togorian: Languages": "Kb5GeNzNvWMv4tlv",
    "Togorian: Savage Attacks": "4dO2w8L25SHDwiiz",
    "Togorian: Size": "efi7lU5dz2H1x5zR",
    "Togorian: Speed": "5hOu5DCl9bS2ky9K",
    "Togorian: Stealthy Hunter": "LwsJVhMmJCohojAB",
    "Togorian: Toughness": "ScqUYc3oYYehbC4J",
    "Togruta: Ability Score Increase": "PnEval9dadJvwoWz",
    "Togruta: Age": "Oj1MPr59EuyZqYxj",
    "Togruta: Alignment": "mBiJ01ZVylRoJSsE",
    "Togruta: Darkvision": "SPsOjjHHPxv17wF2",
    "Togruta: Languages": "vv3zsZwbyz01PwGS",
    "Togruta: Montral Reception": "ZrYj0RwnaoqWWCmR",
    "Togruta: Size": "i6Ts075Iw52RugTB",
    "Togruta: Speed": "WyHZtYcl3i7awyY4",
    "Togruta: Wild Hunters": "lOlH6fVY1uN9UU6G",
    "Toydarian: Ability Score Increase": "yAw3zz5HtsOWD4Uh",
    "Toydarian: Age": "CCFQWdKwub96y64w",
    "Toydarian: Alignment": "YOeLGXmZXlTjUdEs",
    "Toydarian: Business Savvy": "lnCGjuFfWrWQyn73",
    "Toydarian: Closed Mind": "JetlcAq0SgKMP0mp",
    "Toydarian: Flight": "RLYjzHg2Vq9Bcssa",
    "Toydarian: Languages": "FALFCDJtT0I66Jri",
    "Toydarian: Shrewd Demeanor": "rTX8xCR2GkOt0dv5",
    "Toydarian: Size": "Mb2PuTMdNiKwpcOm",
    "Toydarian: Speed": "nrSK0UmIzMga8mL8",
    "Toydarian: Undersized": "i8mGDWx7PkG16M9U",
    "Trandoshan: Ability Score Increase": "9aVXQC6kNzzYZR48",
    "Trandoshan: Age": "tH0YSB4l7D9biukE",
    "Trandoshan: Alignment": "4xV38KyOjbpaftb5",
    "Trandoshan: Darkvision": "DDiNtkGaIByY3x9m",
    "Trandoshan: Hold Breath": "9OovfxQoJvOqsHui",
    "Trandoshan: Languages": "cBd89Yasu1vTRIoH",
    "Trandoshan: Regenerative": "OuUFiyxdRgPXLV03",
    "Trandoshan: Saving Face": "H991dA82qr1zFzLe",
    "Trandoshan: Size": "TNASoP8KXRspQryd",
    "Trandoshan: Speed": "0VyEhLNimbPCGtRZ",
    "Tusken: Ability Score Increase": "O6JqufavqSaFwr0X",
    "Tusken: Age": "Sxh8pFB3OCO5T3Zs",
    "Tusken: Aggressive": "Ww2ihXYy8xoGdxxP",
    "Tusken: Alignment": "rS8XFD299RQZ01GM",
    "Tusken: Animal Handler": "NqfyAmWJj8crAym3",
    "Tusken: Intimidating Roar": "iKwzVeyLSN8Cno60",
    "Tusken: Languages": "2aijdxRc2OUS5min",
    "Tusken: Size": "aVjSt3bNuQnQayoS",
    "Tusken: Speed": "1LUQWUlI8nUdrA6B",
    "Tusken: Survivors Of The Sands": "j3q1TO8PeILeywgT",
    "Tusken: Tusken Weaponry": "jncl6l5D6c8E6IlT",
    "Twi'Lek: Ability Score Increase": "vLNVReyDpiYXPkDP",
    "Twi'Lek: Age": "fY036HTL8yFC911o",
    "Twi'Lek: Alignment": "BqCiG7Ohrq8ImFz9",
    "Twi'Lek: Darkvision": "vK0BOpsTJDxTODfi",
    "Twi'Lek: Elegant Dancers": "WmqrwQUA5pxlmBzp",
    "Twi'Lek: Languages": "mXmOLkHPQsz1LrHh",
    "Twi'Lek: Natural Antitoxins": "10TzxpZ5l41IH2SH",
    "Twi'Lek: Size": "QlA0T1pE6BngHl0b",
    "Twi'Lek: Speed": "1YPDB2kJlFm5fBTE",
    "Twi'Lek: Unarmed Combatant": "c4IIThf5MQGZ6INE",
    "Ugnaught: Ability Score Increase": "F0cSoATLkabixgD4",
    "Ugnaught: Age": "L2pqN2TKwkPDpznA",
    "Ugnaught: Alignment": "lLqCOpfXPUAKFJcW",
    "Ugnaught: Bite": "Cg6YuOOee9kBDy8u",
    "Ugnaught: Crafters": "SiHHWlVw0bCXRZBK",
    "Ugnaught: Darkvision": "nRMHYthX7TVERy22",
    "Ugnaught: Industrial Hazards": "yV76rw7LjknIbwaM",
    "Ugnaught: Languages": "m46FsWYVQPQmOIPy",
    "Ugnaught: Size": "Q13shoGGJ02NByik",
    "Ugnaught: Speed": "B41vzBcB1PpBWbhH",
    "Ugnaught: Tech Dabbler": "MxUoyQRnJPMc9Sf4",
    "Ugnaught: Tinker": "yQJvR2lGcNBzjZaJ",
    "Ugnaught: Undersized": "q5E1pj7eKuBuN9JL",
    "Umbaran: Ability Score Increase": "JYu0aUQV8ZvEQbnu",
    "Umbaran: Age": "4Sj4jHTeUUr1jPft",
    "Umbaran: Alignment": "hckMoh7TWf9gtOZs",
    "Umbaran: Languages": "QXqJhZVrsz3WJorr",
    "Umbaran: Shadow People": "HhFoBNqaiI4qaHXL",
    "Umbaran: Size": "MUnRJBKZnKuYg5hM",
    "Umbaran: Speed": "zvfGFatmHqbCV8CT",
    "Umbaran: Sunlight Sensitivity": "e9bb10iuBKzmZNNN",
    "Umbaran: Superior Darkvision": "h5gKuBYCJnk0TVCX",
    "Umbaran: Tech Dabbler": "64GxHRRq6r8Zm0mm",
    "Umbaran: Umbaran Specilization": "pD6qxD9bXbxMG5Qm",
    "Verpine: Ability Score Increase": "Pr8kZ3BYl6KNAZaU",
    "Verpine: Age": "aOrRKTGTBKGgRaer",
    "Verpine: Alignment": "FBuRd6qjW0jOaDU0",
    "Verpine: Crafters": "vqvAGJjDsns4e7xw",
    "Verpine: Hardened Carapace": "JXzudrATzlVmsd6M",
    "Verpine: Languages": "fnpITLI5qXZ49vJY",
    "Verpine: Size": "wqxdCctMPiaH6H7D",
    "Verpine: Speed": "XlUGxmcQ4XFVU3y9",
    "Verpine: Tympanic Antennae": "A1eRQrQjuYQc4XhR",
    "Voss: Ability Score Increase": "n1M5Cic52EMLeovQ",
    "Voss: Age": "eJ5eXaWtuK71Dsao",
    "Voss: Alignment": "G2nGXNo58J4rs0pG",
    "Voss: Darkvision": "IXGewRb8OTHoWIsF",
    "Voss: Inscrutable": "HXnZzbdwaEqzjusz",
    "Voss: Languages": "NvuyGlGzA3LJ0hfL",
    "Voss: Mystic Healing": "44LvJiEjCa8TFcA6",
    "Voss: Precognition": "p3ZfGRoJ9sMjWpnA",
    "Voss: Size": "ynKqnz7E9A6Kgqph",
    "Voss: Speed": "WEhTLJnD6KZ2ni4A",
    "Voss: Voss Weapon Training": "dWsosDxYnupEpoG5",
    "Vurk: Ability Score Increase": "TRAdGo9GEjXDMDup",
    "Vurk: Age": "Ei283Wq0loU0pIkV",
    "Vurk: Alignment": "ciDYGS6fYdqL5Ilr",
    "Vurk: Amphibious": "eWOZ6AubOQCJmiY3",
    "Vurk: Athletic": "XmpHvbC4rEXwLBzo",
    "Vurk: Darkvision": "l5npn6OM6Y7r1yds",
    "Vurk: Head Crest": "3QieLLF10oOQ7wXo",
    "Vurk: Languages": "ZJHlWasITcvkfLNb",
    "Vurk: Size": "owbaCl3RZt1k7Dpj",
    "Vurk: Speed": "aWsgXfVIbUcQKDBa",
    "Vurk: Swim": "5etOv02nzuLB1Bwn",
    "Weequay: Ability Score Increase": "C3ePXfnhMnvO1X6o",
    "Weequay: Age": "vJWTc1OoUQLiyj8X",
    "Weequay: Alignment": "07dlB61NLrUiZV5X",
    "Weequay: Charming": "Twg98NTQsprdocGf",
    "Weequay: Darkvision": "WEy0KH6QrOhujfK2",
    "Weequay: Keen Smell": "CI3HF3FSZAjy7vXr",
    "Weequay: Languages": "ThZO9pSLtzExndHP",
    "Weequay: Size": "hTiGwCuvTldGxTcf",
    "Weequay: Speed": "FnzcomFUHwoo0FmH",
    "Weequay: Tanned": "EDVDWXiojJ2xFOYY",
    "Wookiee: Ability Score Increase": "uXxuLXlsQnlDVp1t",
    "Wookiee: Age": "E2yrm6GxiMoHKQaH",
    "Wookiee: Alignment": "QjEikAXVuxguGplO",
    "Wookiee: Claws": "wy7DbVTTGvl6Vbs1",
    "Wookiee: Darkvision": "NZVS4kVSQYcgKliI",
    "Wookiee: Hide": "WAJiSse6v8jWjU5m",
    "Wookiee: Languages": "AO4yy06V1zewq1r7",
    "Wookiee: Powerful Build": "iJDOxhGMUdULbdGh",
    "Wookiee: Size": "suXve4QCiZcsmKeC",
    "Wookiee: Speed": "1GsCTpG2BWpCCuqd",
    "Wookiee: Treeclimber": "WIOkrDrpHd5mdfPW",
    "Yevetha: Ability Score Increase": "ZuO1ZlVtZqHlYb5N",
    "Yevetha: Age": "7qGA4TZvvraBrOR3",
    "Yevetha: Aggressive": "pZqSyHFzUzxG48PT",
    "Yevetha: Alignment": "qB0XV5h5QIdKcNkr",
    "Yevetha: Arm Blades": "mJpg6jIuijJhwMeY",
    "Yevetha: Languages": "GYjRVsLx0czQNDZR",
    "Yevetha: Mechanical Memory": "5etoUODtPaIo66PJ",
    "Yevetha: Size": "HjkRsdIDord93OXy",
    "Yevetha: Speed": "iLcr4nnX7uP5Zjss",
    "Yevetha: Toughness": "l6OqqvVR5O8e6mgK",
    "Zabrak: Ability Score Increase": "0EzJ9YlfMESMjBTJ",
    "Zabrak: Age": "sUlIbHPJVAVIZuCB",
    "Zabrak: Alignment": "T5doGD5Mxf6y8ai3",
    "Zabrak: Coercive": "FKd0RzdKd50CYstH",
    "Zabrak: Crafters": "jq3lKHObzfI6Zwef",
    "Zabrak: Darkvision": "K9Rsh4KdZweGTT3S",
    "Zabrak: Languages": "oLOoOreRWk09qDil",
    "Zabrak: Second Heart": "vVYhjidf2UAHNe8F",
    "Zabrak: Size": "3qLRZCmYPwpkG0Kl",
    "Zabrak: Speed": "TmmMkPXMsSDYYoRW",
    "Zabrak: Unarmed Combatant": "IvFZfX7tHEnxgL6X",
    "Zeltron: Ability Score Increase": "YCp6QpRMPd2gO5yL",
    "Zeltron: Age": "bvnq0jKJfrQB4tvL",
    "Zeltron: Alignment": "y9R9DH2AgcoqjZJp",
    "Zeltron: Charismatic": "pk3E3a9SQ5gbR9ei",
    "Zeltron: Enthralling Pheromones": "nUOFimCypj6C2frt",
    "Zeltron: Languages": "1z7CeIReAgHM8FeT",
    "Zeltron: Natural Empathy": "SIChJeiMvHha1bWt",
    "Zeltron: Size": "cuLPQSTcIHl6PuJR",
    "Zeltron: Speed": "qytdkTR1Gx3PvY0R",
    "Zeltron: Two Livered": "md98CHbBObdwVBWz",
    "Zygerrian: Ability Score Increase": "uWuyQ1Rv7aVj71Ly",
    "Zygerrian: Acrobatic": "CtsyFH4IK698OKcC",
    "Zygerrian: Age": "CdVrmR48p3qebkLq",
    "Zygerrian: Alignment": "qNKoElKQHTHs1yWO",
    "Zygerrian: Claws": "1J1uUMrQtPl9JLBm",
    "Zygerrian: Darkvision": "FEZFSaV02Up2o5mh",
    "Zygerrian: Languages": "EYawlzDfq2qrazsd",
    "Zygerrian: Notorious Slavers": "lA1VmRYgUvOkcPjS",
    "Zygerrian: Reputation For Cruelty": "dyiC1IEMxcYeb594",
    "Zygerrian: Size": "Va5CZdel7bnfMK6P",
    "Zygerrian: Speed": "NmdvGIh8lI7mitDi"
}
