module.exports = {
    "Assault Cannon": "2yAiZeQHZbNXjqUs",
    "Blaster Cannon": "atdw9BYBUaq3TBJc",
    "Blaster Carbine": "ff3pk8eoISixRmoS",
    "Blaster Pistol": "rsvtNAd7ynaSl9Vm",
    "Blaster Rifle": "mtFnCiSUAj9kivGi",
    Bowcaster: "1SBIOPVaJBJOzMX3",
    "Carbine Rifle": "ftt2CdiE87E6YH7o",
    Chaingun: "AMHhpY8JNWdgtTxt",
    Chakram: "SHFWAW9vX90h7wy2",
    "Cycler Rifle": "EoDw5dGGjFL26UVF",
    Doubleblade: "FaI2hcLloxVCVhJs",
    Doublesaber: "k9itkDmC1x7Z1K7P",
    Doubleshoto: "5ITBFp9TFfWegA8a",
    Doublesword: "OAgCRzEXmHFrOrrQ",
    Greatsaber: "uH7eKtZhXWCTq28J",
    "Heavy Bowcaster": "S2VEGzRNabUz9Y3v",
    "Heavy Pistol": "xZmrMpjEoVEhiEFp",
    "Heavy Repeater": "dnsnA7btkZWhauhS",
    "Heavy Shotgun": "Rnnty5E35aSfX42x",
    "Heavy Slugpistol": "6CKTZxpD5pCbDvTM",
    "Hidden Blade": "G4XP83WKt0oks972",
    "Hold-Out": "lMx7dwuE5IZtDPtz",
    "Hunting Rifle": "HT9JkoXHsZ6X7W8q",
    "Ion Carbine": "K9ejn3f6GGoY66yW",
    "Ion Pistol": "jGDuLu25eqYklyqv",
    "Ion Rifle": "oZYhBpB4G2pq02Rq",
    "Light Pistol": "TMKqWa3KZKTxiaPB",
    "Light Repeater": "N84CPvAv89ELqgJ7",
    "Light Ring": "pIKgMdXvjQbTqMCx",
    "Light Slugpistol": "J5eex5McFySyg66d",
    Lightclub: "uzeq8Hjm7oFw2rA7",
    Lightdagger: "jQc4ZmyZnEZXDZS7",
    Lightfoil: "tYdQWaOlSm97aYdw",
    Lightsaber: "HtN8KYXXMaJ9L94x",
    "Lightsaber Pike": "ylA99WYUVY8U5z9U",
    "Martial Lightsaber": "thGihwn0AfTo5Wu7",
    Needler: "EFCyA4xJQE25DEbw",
    Net: "j2g1D976omFXUQP1",
    "Repeating Blaster": "zMxfSwEGBrTYbsP3",
    Revolver: "5N3UBYLZf785VxNK",
    Saberspear: "TWL4tclbh0dVt6HR",
    Saberwhip: "6VAWhI8EESUa217M",
    Scattergun: "AXba3svQTMscEGlf",
    Shotgun: "FN8cSlvwnzkIbbNa",
    Shotosaber: "zTg0qnvZJDAht3Zm",
    Slugpistol: "5xtJY3hAPoTGNhuD",
    Slugthrower: "W4G7FhgqrpFE0wdX",
    "Sniper Rifle": "JliFzE6002igf46x",
    Subrepeater: "A7U4bqnbP9tFACPX",
    Techaxe: "G5bjOdE8vxCM8NOq",
    Techblade: "wwumzQvxwoPyyuTX",
    Techstaff: "I6UqxtQec0NXW8gv",
    "Tranquilizer Rifle": "Lw6vUczorCLaGPFe",
    Vibroaxe: "8bcaFVQ91NKjrH2e",
    Vibrobaton: "X3EtJ3JgDWIPiED9",
    Vibroblade: "Axbve7PaSX9obY47",
    Vibrodagger: "XfUEDKVByHe83aSB",
    Vibrodart: "TM1rXOy8GZEbmP6x",
    Vibroknuckler: "omDKHum2Ybu2atpI",
    Vibrolance: "p5URddJqRu3grRQl",
    Vibromace: "jjulP09xLc8oYOZo",
    Vibropike: "JMj0t59NQtIU8Rbo",
    Vibrorapier: "YmIH2FjeQwjzNMFa",
    Vibrospear: "B0hPklxvpHwSxCMJ",
    Vibrostaff: "bNzwxj6dlIjwqTnH",
    Vibrosword: "OrWJNGr3WDulfOO0",
    Vibrowhip: "Rxa18dl0msDmUCB1",
    "Wrist Launcher": "Jbf3fp7lslwSjWbW",
    Wristblaster: "Ax4RQZEjbsHcjfJf"
};
